### ISSUE TITLE
[BUG] Error Updating Metadata

### ISSUE THREAD

**Issue by KridOCaign** [JimmXinu/FanFicFare#1048]
This occurs every time FanFicFare encounters a attempts to fetch metadata for a story where the server returns any HTTP response code of type 300, 400, or 500.
It started on updating to Calibre 7.7.0, which is the latest stable release. Reinstalling it did not affect behavior.
FanFicFare v4.32.3 is installed. Reinstalling it did not affect behavior.

Error log follows:

calibre, version 7.7.0
ERROR: Error Updating Metadata: <p>An error has occurred while FanFicFare was updating calibre's metadata for <a href='https://www.scribblehub.com/series/883461/the-hero-became-a-mousegirl-revised-edition/'>The Hero Became a Mousegirl [Revised Edition]</a>.</p>

Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.dialogs", line 715, in do_loop
    self.foreach_function(book)
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1356, in prep_download_loop
    story = self.get_story_metadata_only(adapter)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1236, in get_story_metadata_only
    adapter.getStoryMetadataOnly(get_cover=False)
  File "/home/krid/.config/calibre/plugins/FanFicFare.zip/fanficfare/adapters/base_adapter.py", line 325, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "/home/krid/.config/calibre/plugins/FanFicFare.zip/fanficfare/adapters/base_adapter.py", line 429, in doExtractChapterUrlsAndMetadata
    return self.extractChapterUrlsAndMetadata()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/krid/.config/calibre/plugins/FanFicFare.zip/fanficfare/adapters/adapter_scribblehubcom.py", line 142, in extractChapterUrlsAndMetadata
    self.story.setMetadata('title',stripHTML(pagetitle))
                                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/krid/.config/calibre/plugins/FanFicFare.zip/fanficfare/htmlcleanup.py", line 71, in stripHTML
    retval = soup.get_text(strip=True)
             ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_text'

**Comment by JimmXinu** [comment]
You are seeing the same thing as #1044.  Fix is out in the test version.  The latest [FanFicFare plugin test version is always posted here](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2).
