### ISSUE TITLE
Literotica request to download all stories by the author youbadboy

### ISSUE THREAD

**Issue by CigarsSmoker** [JimmXinu/FanFicFare#1086]
Run: FanFicFare-4.36.0-py3-none-any.whl

Request:

fanficfare -f html --non-interactive -o "is_adult=true" https://www.literotica.com/authors/youbadboy/works/stories

Output:
Traceback (most recent call last):
  File "c:\users\vehf277\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\vehf277\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\vehf277\AppData\Local\Programs\Python\Python38\Scripts\fanficfare.exe\__main__.py", line 7, in <module>
  File "c:\users\vehf277\appdata\local\programs\python\python38\lib\site-packages\fanficfare\cli.py", line 346, in main
    dispatch(options, urls, passed_defaultsini, passed_personalini, warn, fail)
  File "c:\users\vehf277\appdata\local\programs\python\python38\lib\site-packages\fanficfare\cli.py", line 322, in dispatch
    do_download(url,
  File "c:\users\vehf277\appdata\local\programs\python\python38\lib\site-packages\fanficfare\cli.py", line 393, in do_download
    adapter = adapters.getAdapter(configuration, url)
  File "c:\users\vehf277\appdata\local\programs\python\python38\lib\site-packages\fanficfare\adapters\__init__.py", line 235, in getAdapter
    adapter = cls(config,fixedurl) # raises InvalidStoryURL
  File "c:\users\vehf277\appdata\local\programs\python\python38\lib\site-packages\fanficfare\adapters\adapter_literotica.py", line 39, in __init__
    BaseSiteAdapter.__init__(self, config, url)
  File "c:\users\vehf277\appdata\local\programs\python\python38\lib\site-packages\fanficfare\adapters\base_adapter.py", line 114, in __init__
    self._setURL(url)
  File "c:\users\vehf277\appdata\local\programs\python\python38\lib\site-packages\fanficfare\adapters\adapter_literotica.py", line 91, in _setURL
    lang = m.group('lang')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by JimmXinu** [comment]
`--download-list` option already exists.
