### ISSUE TITLE
Bug: Error pulling metadata for scribblehub.com

### ISSUE THREAD

**Issue by Immortalin** [JimmXinu/FanFicFare#1092]
fanficfare version 4.36.0
` fanficfare --meta-only --json-meta --no-output <fiction url from https://www.scribblehub.com/>` 
```
Traceback (most recent call last):
  File "/Users/user/.local/bin/fanficfare", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/user/Library/Application Support/pipx/venvs/fanficfare/lib/python3.12/site-packages/fanficfare/cli.py", line 346, in main
    dispatch(options, urls, passed_defaultsini, passed_personalini, warn, fail)
  File "/Users/user/Library/Application Support/pipx/venvs/fanficfare/lib/python3.12/site-packages/fanficfare/cli.py", line 322, in dispatch
    do_download(url,
  File "/Users/user/Library/Application Support/pipx/venvs/fanficfare/lib/python3.12/site-packages/fanficfare/cli.py", line 437, in do_download
    adapter.getStoryMetadataOnly()
  File "/Users/user/Library/Application Support/pipx/venvs/fanficfare/lib/python3.12/site-packages/fanficfare/adapters/base_adapter.py", line 325, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "/Users/user/Library/Application Support/pipx/venvs/fanficfare/lib/python3.12/site-packages/fanficfare/adapters/base_adapter.py", line 429, in doExtractChapterUrlsAndMetadata
    return self.extractChapterUrlsAndMetadata()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Library/Application Support/pipx/venvs/fanficfare/lib/python3.12/site-packages/fanficfare/adapters/adapter_scribblehubcom.py", line 169, in extractChapterUrlsAndMetadata
    contents_soup = self.make_soup(contents_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Library/Application Support/pipx/venvs/fanficfare/lib/python3.12/site-packages/fanficfare/adapters/base_adapter.py", line 847, in make_soup
    data = data.replace("<noscript","<fff_hide_noscript").replace("</noscript","</fff_hide_noscript")
           ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by JimmXinu** [comment]
I don't see that happen.  However, I do have to use flaresolverr to download from scribblehub.

Without the story URL, there's not much more I can look at.
