### ISSUE TITLE
"Must restart calibre" even after restarting

### ISSUE THREAD

**Issue by Groxx** [JimmXinu/FanFicFare#1103]
# Fixed
My vendor-packaged / apt-installed `calibre` appears to be missing dependencies, and this failure was happening on older plugin versions as well.

Switching to the official linux install process worked: https://calibre-ebook.com/download_linux

---

# Original report is below:

Greetings!  I'm not entirely sure what else might be useful, so to start I'll just paste the error I get when I try to configure the plugin:
```
calibre, version 7.6.0
ERROR: Must restart: You must restart calibre before you can configure the <b>FanFicFare</b> plugin
```
This appears even after restarting (I've tried both uninstall -> reinstall -> click "restart" after installing, and just a manual "quit" from Calibre).

Since I'm not sure what other logs might exist, or how to diagnose Calibre plugin issues at all... is there anything that would be useful?  I'm happy to go digging around in internals if necessary, I'm a programmer by day and am more than willing to start exploring Calibre/plugins (though I'll be starting from zero, sorry!).

I'm on a relatively-recent fresh-install of Linux Mint, if that helps narrow things down.  Since I see mentions of Python, could that be related somehow?  I believe I only have Python 3.12 installed at the moment.

**Comment by JimmXinu** [comment]
You can run Calibre in debug mode using `calibre-debug -g` from CLI, or by restarting in debug under the Calibre Preferences dropdown.

The current version of Calibre is 7.17 and you're showing 7.6.  Which suggests you're using the linux vendor's packaged version of Calibre.  

Recently, we've seen problems with those versions, see #1079 where I said:
> As a general rule, I only support FFF on the [official calibre releases](https://download.calibre-ebook.com/) for exactly this sort of reason--random dependencies being a problem. The vendor versions are typically out of date, too--current is Calibre 7.12.
> 
> So officially, my answer is to install the [official calibre releases](https://download.calibre-ebook.com/). Come back if it still fails on the official version.

**Comment by Groxx** [comment]
Yep, that seems entirely fair. I'll check out the official release soon and will update :)

Would you still be interested in finding the cause (I'm happy to explore), or is it more of "limited time and energy, would prefer not to" kind of thing?

**Comment by JimmXinu** [comment]
I wouldn't might seeing a debug log of it happening.

**Comment by Groxx** [comment]
Well.  Looks like it's probably the same as #1079 - official 7.17 works and my apt-installed version starts up with:
```
[0.03] Constructing main UI...
Traceback (most recent call last):
  File "/home/groxx/.config/calibre/plugins/FanFicFare.zip/requests_toolbelt/_compat.py", line 48, in <module>
    from requests.packages.urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'requests.packages.urllib3.contrib' (/usr/lib/python3/dist-packages/urllib3/contrib/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/ui.py", line 141, in __init__
    ac = self.init_iaction(action)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/gui2/ui.py", line 159, in init_iaction
    ac = action.load_actual_plugin(self)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.fanficfare_plugin.__init__", line 121, in load_actual_plugin
    return InterfaceActionBase.load_actual_plugin(self,gui)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/customize/__init__.py", line 662, in load_actual_plugin
    ac = getattr(importlib.import_module(mod), cls)(gui,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 207, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 77, in <module>
    from fanficfare import adapters, exceptions
  File "/home/groxx/.config/calibre/plugins/FanFicFare.zip/fanficfare/adapters/__init__.py", line 29, in <module>
    from .. import configurable as configurable
  File "/home/groxx/.config/calibre/plugins/FanFicFare.zip/fanficfare/configurable.py", line 42, in <module>
    from . import fetchers
  File "/home/groxx/.config/calibre/plugins/FanFicFare.zip/fanficfare/fetchers/__init__.py", line 19, in <module>
    from .fetcher_cloudscraper import CloudScraperFetcher
  File "/home/groxx/.config/calibre/plugins/FanFicFare.zip/fanficfare/fetchers/fetcher_cloudscraper.py", line 22, in <module>
    import cloudscraper
  File "/home/groxx/.config/calibre/plugins/FanFicFare.zip/cloudscraper/__init__.py", line 14, in <module>
    from requests_toolbelt.utils import dump
  File "/home/groxx/.config/calibre/plugins/FanFicFare.zip/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/home/groxx/.config/calibre/plugins/FanFicFare.zip/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/home/groxx/.config/calibre/plugins/FanFicFare.zip/requests_toolbelt/adapters/ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "/home/groxx/.config/calibre/plugins/FanFicFare.zip/requests_toolbelt/_compat.py", line 50, in <module>
    from urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'urllib3.contrib' (/usr/lib/python3/dist-packages/urllib3/contrib/__init__.py)
calibre_plugins.koreader.slpp:58: SyntaxWarning: invalid escape sequence '\s'
calibre_plugins.koreader.slpp:59: SyntaxWarning: invalid escape sequence '\w'
Loaded cached store plugin for: Kobo at version: 12
DEBUG:    0.0 koreader:action:KoreaderAction:genesis:start
[0.50] GUI main window shown
```

Since Calibre's site says they're including all dependencies in the install (as they should, since it's Python): does this imply that my packaged version is stripping those, in favor of distro-supplied stuff?  I can certainly see how that'd be problematic / not something a plugin should be addressing...

**Comment by JimmXinu** [comment]
It's something like: a package I've bundled is importing a package that imports a package that it doesn't prerequire in the latest(?) version. 

It's a pretty specific issue to be adding code for.
