### ISSUE TITLE
'cache_dir' is not defined

### ISSUE THREAD

**Issue by Groxx** [JimmXinu/FanFicFare#1104]
It's fairly likely that this is due to me mucking some config up, but the error looks like it's caused by incorrect code:
```
calibre, version 7.17.0
ERROR: Unhandled exception: <b>NameError</b>:name 'cache_dir' is not defined

calibre 7.17  embedded-python: True
Linux-6.8.0-41-generic-x86_64-with-glibc2.39 Linux ('64bit', 'ELF')
('Linux', '6.8.0-41-generic', '#41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024')
Python 3.11.5
Interface language: None
EXE path: /opt/calibre/bin/calibre
Successfully initialized third party plugins: FanFicFare (4, 38, 0) && KOReader Sync (0, 6, 7) && Reading List (1, 15, 4) && Standard Ebooks (1, 0, 0)
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 689, in get_urls_from_page_menu
    frompage = self.get_urls_from_page(url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 712, in get_urls_from_page
    return get_urls_from_page(url,configuration)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/groxx/.config/calibre/plugins/FanFicFare.zip/fanficfare/geturls.py", line 44, in get_urls_from_page
    return adapter.get_urls_from_page(url,normalize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/groxx/.config/calibre/plugins/FanFicFare.zip/fanficfare/adapters/base_adapter.py", line 477, in get_urls_from_page
    data = self.get_request(url,usecache=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/groxx/.config/calibre/plugins/FanFicFare.zip/fanficfare/requestable.py", line 119, in get_request
    return self.get_request_redirected(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/groxx/.config/calibre/plugins/FanFicFare.zip/fanficfare/requestable.py", line 111, in get_request_redirected
    (data,rurl) = self.configuration.get_fetcher().get_request_redirected(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/groxx/.config/calibre/plugins/FanFicFare.zip/fanficfare/configurable.py", line 1089, in get_fetcher
    self.browser_cache = BrowserCache(self.getConfig,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/groxx/.config/calibre/plugins/FanFicFare.zip/fanficfare/browsercache/__init__.py", line 44, in __init__
    os.path.abspath(cache_dir))
                    ^^^^^^^^^
NameError: name 'cache_dir' is not defined
```

This is referring to these lines: https://github.com/JimmXinu/FanFicFare/blob/main/fanficfare/browsercache/__init__.py#L43-L44
which don't have a defined `cache_dir` variable, nor do I see any globals in the module that it could be referencing....

...though it has been a while since I've done any Python, so apologies if I've missed something obvious.

**Comment by JimmXinu** [comment]
Apparently I didn't test turning on `use_browser_cache:true` without setting `browser_cache_path` when I made change 478d2e8f1738fda6b9482fdaad0f88a0a6d4faf3.

**Comment by Groxx** [comment]
Thank you!

This was apparently due to me using librewolf, which does not write caches to disk by default.  (you can enable that in about:config, `browser.cache.disk.enable` change to true)
