### ISSUE TITLE
Login on QQ fails

### ISSUE THREAD

**Issue by Nothorse** [JimmXinu/FanFicFare#1124]
The request for a story on Questionable Questing fails with a login error. I've checked my .ini and the password in there is the correct one. Did I miss something with the xenforo2 upgrade. The ini looks like this:

```
[forum.questionablequesting.com]
is_adult:true
username:nothorse.fanfic@gmail.com
password:######### (password deleted)
```

The error is 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/fetchers/fetcher_requests.py", line 128, in request
    resp.raise_for_status() # raises RequestsHTTPError if error code.
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://forum.questionablequesting.com/threads/a-succubus-at-hogwarts.16492/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/adapters/base_xenforoforum_adapter.py", line 454, in extractChapterUrlsAndMetadata
    (data,useurl) = self.get_request_redirected(useurl)
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/requestable.py", line 111, in get_request_redirected
    (data,rurl) = self.configuration.get_fetcher().get_request_redirected(
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/fetchers/base_fetcher.py", line 133, in get_request_redirected
    fetchresp = self.do_request('GET',
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/fetchers/cache_basic.py", line 122, in fetcher_do_request
    fetchresp = chainfn(
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/fetchers/decorators.py", line 102, in fetcher_do_request
    fetchresp = chainfn(
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/fetchers/base_fetcher.py", line 106, in do_request
    fetchresp = self.request(method,url,
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/fetchers/fetcher_requests.py", line 149, in request
    raise exceptions.HTTPErrorFFF(
fanficfare.exceptions.HTTPErrorFFF: HTTP Error in FFF '403 Client Error: Forbidden for url: https://forum.questionablequesting.com/threads/a-succubus-at-hogwarts.16492/'(403)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/fetchers/fetcher_requests.py", line 128, in request
    resp.raise_for_status() # raises RequestsHTTPError if error code.
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://forum.questionablequesting.com/login/login

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/fanficfare", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/cli.py", line 344, in main
    dispatch(options, urls, passed_defaultsini, passed_personalini, warn, fail)
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/cli.py", line 320, in dispatch
    do_download(url,
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/cli.py", line 435, in do_download
    adapter.getStoryMetadataOnly()
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/adapters/base_adapter.py", line 327, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/adapters/base_adapter.py", line 431, in doExtractChapterUrlsAndMetadata
    return self.extractChapterUrlsAndMetadata()
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/adapters/base_xenforoforum_adapter.py", line 465, in extractChapterUrlsAndMetadata
    self.performLogin(data)
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/adapters/base_xenforoforum_adapter.py", line 216, in performLogin
    d = self.post_request(loginUrl, params)
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/requestable.py", line 102, in post_request
    data = self.configuration.get_fetcher().post_request(
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/fetchers/base_fetcher.py", line 124, in post_request
    fetchresp = self.do_request('POST',
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/fetchers/cache_basic.py", line 122, in fetcher_do_request
    fetchresp = chainfn(
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/fetchers/decorators.py", line 102, in fetcher_do_request
    fetchresp = chainfn(
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/fetchers/base_fetcher.py", line 106, in do_request
    fetchresp = self.request(method,url,
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/fetchers/fetcher_requests.py", line 149, in request
    raise exceptions.HTTPErrorFFF(
fanficfare.exceptions.HTTPErrorFFF: HTTP Error in FFF '400 Client Error: Bad Request for url: https://forum.questionablequesting.com/login/login'(400)
```

**Comment by JimmXinu** [comment]
It's working for me.  Try it with screen name for `username` instead of email address.  That's what I use.

The QQ switch to XF2 was back in May and FFF changed accordingly.  I assume you've updated FFF since then.

**Comment by Nothorse** [comment]
fanficfare is on 4.39.0
```
djinn:~ $ /usr/local/bin/fanficfare --version
Version: 4.39.0
```

I've tried using the screenname but still get the same error.  Is there a deeper debugging option I could use to give you more details?

**Comment by Nothorse** [comment]
I have not downloaded anything for months now, had some issues with my raspi and enough to read anyway, so I don't think it's a blocking issue. (And downloading from SV worked)

Here's the output with -d:
```
djinn:~ $ sudo -u www-data /usr/local/bin/fanficfare -c /home/web/books/lib/ebooklib.ini -d  --update-cover "https://forum.questionablequesting.com/threads/a-succubus-at-hogwarts.16492/" >> /home/web/books/tmp/fff_error.log
FFF: DEBUG: 2024-10-16 17:33:29,120: cli.py(230):     OS Version:Linux-6.1.21-v8+-aarch64-with-glibc2.31
FFF: DEBUG: 2024-10-16 17:33:29,121: cli.py(231): Python Version:3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
FFF: DEBUG: 2024-10-16 17:33:29,122: cli.py(232):    FFF Version:4.28.0
FFF: DEBUG: 2024-10-16 17:33:29,235: configurable.py(1072): use_browser_cache:
FFF: DEBUG: 2024-10-16 17:33:29,238: configurable.py(1092): use_basic_cache:true
FFF: INFO: 2024-10-16 17:33:29,347: base_xenforoforum_adapter.py(451): url: https://forum.questionablequesting.com/threads/a-succubus-at-hogwarts.16492/
FFF: DEBUG: 2024-10-16 17:33:29,350: cache_basic.py(116): 
========== MISS (GET) BasicCache
https://forum.questionablequesting.com/threads/a-succubus-at-hogwarts.16492/
FFF: DEBUG: 2024-10-16 17:33:29,352: fetcher_requests.py(114): 
---------- REQ (GET) RequestsFetcher
https://forum.questionablequesting.com/threads/a-succubus-at-hogwarts.16492/
FFF: DEBUG: 2024-10-16 17:33:29,993: fetcher_requests.py(127): response code:403
FFF: DEBUG: 2024-10-16 17:33:29,997: base_xenforoforum_adapter.py(213): Will now login to URL (https://forum.questionablequesting.com/login/login) as (Nothorse)
FFF: DEBUG: 2024-10-16 17:33:29,999: cache_basic.py(116): 
========== MISS (POST) BasicCache
https://forum.questionablequesting.com/login/login
FFF: DEBUG: 2024-10-16 17:33:30,001: fetcher_requests.py(114): 
---------- REQ (POST) RequestsFetcher
https://forum.questionablequesting.com/login/login
FFF: DEBUG: 2024-10-16 17:33:30,199: fetcher_requests.py(127): response code:400
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/fetchers/fetcher_requests.py", line 128, in request
    resp.raise_for_status() # raises RequestsHTTPError if error code.
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://forum.questionablequesting.com/threads/a-succubus-at-hogwarts.16492/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/adapters/base_xenforoforum_adapter.py", line 454, in extractChapterUrlsAndMetadata
    (data,useurl) = self.get_request_redirected(useurl)
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/requestable.py", line 111, in get_request_redirected
    (data,rurl) = self.configuration.get_fetcher().get_request_redirected(
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/fetchers/base_fetcher.py", line 133, in get_request_redirected
    fetchresp = self.do_request('GET',
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/fetchers/cache_basic.py", line 122, in fetcher_do_request
    fetchresp = chainfn(
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/fetchers/decorators.py", line 102, in fetcher_do_request
    fetchresp = chainfn(
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/fetchers/base_fetcher.py", line 106, in do_request
    fetchresp = self.request(method,url,
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/fetchers/fetcher_requests.py", line 149, in request
    raise exceptions.HTTPErrorFFF(
fanficfare.exceptions.HTTPErrorFFF: HTTP Error in FFF '403 Client Error: Forbidden for url: https://forum.questionablequesting.com/threads/a-succubus-at-hogwarts.16492/'(403)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/fetchers/fetcher_requests.py", line 128, in request
    resp.raise_for_status() # raises RequestsHTTPError if error code.
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://forum.questionablequesting.com/login/login

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/fanficfare", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/cli.py", line 344, in main
    dispatch(options, urls, passed_defaultsini, passed_personalini, warn, fail)
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/cli.py", line 320, in dispatch
    do_download(url,
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/cli.py", line 435, in do_download
    adapter.getStoryMetadataOnly()
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/adapters/base_adapter.py", line 327, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/adapters/base_adapter.py", line 431, in doExtractChapterUrlsAndMetadata
    return self.extractChapterUrlsAndMetadata()
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/adapters/base_xenforoforum_adapter.py", line 465, in extractChapterUrlsAndMetadata
    self.performLogin(data)
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/adapters/base_xenforoforum_adapter.py", line 216, in performLogin
    d = self.post_request(loginUrl, params)
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/requestable.py", line 102, in post_request
    data = self.configuration.get_fetcher().post_request(
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/fetchers/base_fetcher.py", line 124, in post_request
    fetchresp = self.do_request('POST',
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/fetchers/cache_basic.py", line 122, in fetcher_do_request
    fetchresp = chainfn(
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/fetchers/decorators.py", line 102, in fetcher_do_request
    fetchresp = chainfn(
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/fetchers/base_fetcher.py", line 106, in do_request
    fetchresp = self.request(method,url,
  File "/usr/local/lib/python3.9/dist-packages/fanficfare/fetchers/fetcher_requests.py", line 149, in request
    raise exceptions.HTTPErrorFFF(
fanficfare.exceptions.HTTPErrorFFF: HTTP Error in FFF '400 Client Error: Bad Request for url: https://forum.questionablequesting.com/login/login'(400)
```

**Comment by JimmXinu** [comment]
```
FFF: DEBUG: 2024-10-16 17:33:29,122: cli.py(232):    FFF Version:4.28.0
```
I don't know what your setup is like, but apparently you have more than one version of FFF running around.  

v4.28.0 is over a year old and definitely doesn't have the QQ updates for XF2.

**Comment by Nothorse** [comment]
OK, that was weird. I read the debug output and didn't see that. Thanks. No idea how that happened.
