### ISSUE TITLE
FanficFare after installing can't be added to the toolbar because it doesn't show up in the offered actions

### ISSUE THREAD

**Issue by Neloshka** [JimmXinu/FanFicFare#1126]
Hello,
I reinstalled calibre after a full system reinstall and also reinstalled FanficFare. But after installing when I try to add it to the main toolbar calibre doesn't show me FanficFare as an option. So I can't use it. I started Calibre in trouble shooting modus and here is the report from that:

calibre, version 7.6.0

qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre_plugins.count_pages.statistics:415: SyntaxWarning: invalid escape sequence '\D'
calibre_plugins.count_pages.statistics:416: SyntaxWarning: invalid escape sequence '\D'
Traceback (most recent call last):
  File "/home/nele/.config/calibre/plugins/FanFicFare.zip/requests_toolbelt/_compat.py", line 48, in <module>
    from requests.packages.urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'requests.packages.urllib3.contrib' (/usr/lib/python3/dist-packages/urllib3/contrib/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/ui.py", line 141, in __init__
    ac = self.init_iaction(action)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/gui2/ui.py", line 159, in init_iaction
    ac = action.load_actual_plugin(self)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.fanficfare_plugin.__init__", line 121, in load_actual_plugin
    return InterfaceActionBase.load_actual_plugin(self,gui)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/customize/__init__.py", line 662, in load_actual_plugin
    ac = getattr(importlib.import_module(mod), cls)(gui,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 207, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 77, in <module>
    from fanficfare import adapters, exceptions
  File "/home/nele/.config/calibre/plugins/FanFicFare.zip/fanficfare/adapters/__init__.py", line 29, in <module>
    from .. import configurable as configurable
  File "/home/nele/.config/calibre/plugins/FanFicFare.zip/fanficfare/configurable.py", line 42, in <module>
    from . import fetchers
  File "/home/nele/.config/calibre/plugins/FanFicFare.zip/fanficfare/fetchers/__init__.py", line 19, in <module>
    from .fetcher_cloudscraper import CloudScraperFetcher
  File "/home/nele/.config/calibre/plugins/FanFicFare.zip/fanficfare/fetchers/fetcher_cloudscraper.py", line 22, in <module>
    import cloudscraper
  File "/home/nele/.config/calibre/plugins/FanFicFare.zip/cloudscraper/__init__.py", line 14, in <module>
    from requests_toolbelt.utils import dump
  File "/home/nele/.config/calibre/plugins/FanFicFare.zip/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/home/nele/.config/calibre/plugins/FanFicFare.zip/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/home/nele/.config/calibre/plugins/FanFicFare.zip/requests_toolbelt/adapters/ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "/home/nele/.config/calibre/plugins/FanFicFare.zip/requests_toolbelt/_compat.py", line 50, in <module>
    from urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'urllib3.contrib' (/usr/lib/python3/dist-packages/urllib3/contrib/__init__.py)
calibre Fehlerdiagnoseprotokoll
calibre 7.6  embedded-python: False
Linux-6.8.0-45-generic-x86_64-with-glibc2.39 Linux ('64bit', 'ELF')
('Linux', '6.8.0-45-generic', '#45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024')
Python 3.12.3
Interface language: de
EXE path: /usr/bin/python3.12
Successfully initialized third party plugins: Count Pages (1, 13, 6) && FanFicFare (4, 39, 0)
calibre 7.6  embedded-python: False
Linux-6.8.0-45-generic-x86_64-with-glibc2.39 Linux ('64bit', 'ELF')
('Linux', '6.8.0-45-generic', '#45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024')
Python 3.12.3
Interface language: de
EXE path: /usr/bin/python3.12
Successfully initialized third party plugins: Count Pages (1, 13, 6) && FanFicFare (4, 39, 0)
QPA platform: xcb
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 168.1655172413793 x 161.36470588235292
[0.00] Starting up...
[0.01] Showing splash screen...
[0.10] splash screen shown
[0.10] Initializing db...
[0.79] db initialized
[0.79] Constructing main UI...
[3.55] GUI main window shown
[3.73] main UI initialized...
[3.73] Hiding splash screen
[290.97] splash screen hidden
[290.97] Started up in 290.97 seconds with 3350 books

I hope you can help me! As you see I have already used FanficFare to import thousands of books. The Addon is amazingly convenient when it works.

Greetings 
Nele

**Comment by JimmXinu** [comment]
It doesn't look like you are using the [official Calibre release](https://calibre-ebook.com/download).  Try that, as well as getting FanFicFare through Calibre or from the [plugin thread](https://www.mobileread.com/forums/showthread.php?t=259221).

Calibre packages a bunch of dependencies because of how difficult it is to support whatever random setup an individual user may have.

**Comment by JimmXinu** [comment]
I've also found out that Calibre hasn't been ported to python 3.12 yet--the official release bundles it's own version of python.

**Comment by Neloshka** [comment]
I reinstalled Calibre from the official release site and now the plugin works again. Maybe I used the ubuntu software center to install calibre and that's why I had the wrong version?
Anyway, thank you so much!
