### ISSUE TITLE
Fimfiction download broken

### ISSUE THREAD

**Issue by marktaiwan** [JimmXinu/FanFicFare#166]
Attempting to download stories from [Fimfiction.net](https://www.fimfiction.net/) result in the following error.
I have no experience with Python but the problem appears to be caused by the site switching to only allowing https, as replacing all usage of `http` to `https` in adapter_fimfictionnet.py appears to have fixed things on my end.

```` 
D:\Downloads>fanficfare -d https://www.fimfiction.net/story/367354/an-orderly-transfer-of-power
FFF: DEBUG: 2017-03-22 16:22:23,654: base_adapter.py(288): #####################################
pagecache MISS: http://www.fimfiction.net/story/367354/
FFF: DEBUG: 2017-03-22 16:22:24,487: base_adapter.py(288): #####################################
pagecache MISS: http://www.fimfiction.net/story/367354/
FFF: DEBUG: 2017-03-22 16:22:29,036: base_adapter.py(288): #####################################
pagecache MISS: http://www.fimfiction.net/story/367354/
FFF: DEBUG: 2017-03-22 16:22:38,365: base_adapter.py(288): #####################################
pagecache MISS: http://www.fimfiction.net/story/367354/
FFF: ERROR: 2017-03-22 16:22:38,693: base_adapter.py(344): Giving up on http://www.fimfiction.net/story/367354/
FFF: DEBUG: 2017-03-22 16:22:38,694: base_adapter.py(345): HTTP Error 308:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\fanficfare\adapters\base_adapter.py", line 333, in _fetchUrlOpened
    extrasleep=extrasleep)
  File "c:\python27\lib\site-packages\fanficfare\adapters\base_adapter.py", line 293, in _fetchUrlRawOpened
    opened = self.opener.open(url.replace(' ','%20'),None,float(self.getConfig('connect_timeout',30.0)))
  File "c:\python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "c:\python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python27\lib\urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "c:\python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "c:\python27\lib\urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 308:
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\fanficfare.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\fanficfare\cli.py", line 237, in main
    passed_personalini)
  File "c:\python27\lib\site-packages\fanficfare\cli.py", line 327, in do_download
    adapter.getStoryMetadataOnly()
  File "c:\python27\lib\site-packages\fanficfare\adapters\base_adapter.py", line 451, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "c:\python27\lib\site-packages\fanficfare\adapters\adapter_fimfictionnet.py", line 104, in doExtractChapterUrlsAndMetadata
    raise e
urllib2.HTTPError: HTTP Error 308:
````

**Comment by JimmXinu** [comment]
Thanks for the heads up.  Fixed in 15111c6e13aa3734c846d9f4e156449c962bbef1
