### ISSUE TITLE
CLI: SpaceBattles & Sufficient Velocity

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#217]
The CLI seem to not be working in SB and SV
I tried a few links like:

> https://forums.spacebattles.com/threads/respun-a-worm-peggy-sue-story.523987/threadmarks?category_id=1
> https://forums.spacebattles.com/threads/respun-a-worm-peggy-sue-story.523987/
> https://forums.spacebattles.com/threads/worm-dc-comics-fear.537310/unread
> https://forums.sufficientvelocity.com/threads/stacked-deck-or-colin-wallis-vs-single-parenting-worm-persona.33812/page-62#post-9072158

And they all return an error.

In multiple urls each gives a error:
>Failed: Exception ('href'). Run URL individually for more detail.

And for individual stories the error return isQ

> Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\Python27\Scripts\fanficfare.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\fanficfare\cli.py", line 259, in main
    passed_personalini)
  File "c:\python27\lib\site-packages\fanficfare\cli.py", line 355, in do_download
    adapter.getStoryMetadataOnly()
  File "c:\python27\lib\site-packages\fanficfare\adapters\base_adapter.py", line 218, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "c:\python27\lib\site-packages\fanficfare\adapters\base_adapter.py", line 302, in doExtractChapterUrlsAndMetadata
    return self.extractChapterUrlsAndMetadata()
  File "c:\python27\lib\site-packages\fanficfare\adapters\base_xenforoforum_adapter.py", line 275, in extractChapterUrlsAndMetadata
    threadmarks = self.extract_threadmarks(souptag)
  File "c:\python27\lib\site-packages\fanficfare\adapters\base_xenforoforum_adapter.py", line 219, in extract_threadmarks
    threadmark_rss_dom = parseString(self._fetchUrl(self.getURLPrefix()+'/'+threadmarksa['href'].replace('threadmarks','threadmarks.rss')).encode('utf-8'))
  File "c:\python27\lib\site-packages\bs4\element.py", line 1011, in __getitem__
    return self.attrs[key]
KeyError: 'href'

**Comment by JimmXinu** [comment]
This is both duplicate (#199--by you, #203, #207, _and_ #213) and already fixed (f39c9d49f8eb179e82b76f776981fe081b6f7537).

[CLI test version announcement](https://groups.google.com/forum/#!topic/fanfic-downloader/8FqjtxrAaUQ)

**Comment by Twilight666** [comment]
Ok, you are right.
I should have checked if the bug was already closed...
But FYI the duplicate by me (#199) you are referring is about an earlier bug that was already fixed 1.5 months ago back in 2.14
