### ISSUE TITLE
XenForo Error

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#227]
I was trying to download a story in Spacebattles:
https://forums.spacebattles.com/threads/of-blackguards-and-mercenaries-worm-alt-power-overwatch-crossover.506906/

And it gives the following error:
```
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\Python27\Scripts\fanficfare.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\fanficfare\cli.py", line 259, in main
    passed_personalini)
  File "c:\python27\lib\site-packages\fanficfare\cli.py", line 355, in do_download
    adapter.getStoryMetadataOnly()
  File "c:\python27\lib\site-packages\fanficfare\adapters\base_adapter.py", line 218, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "c:\python27\lib\site-packages\fanficfare\adapters\base_adapter.py", line 302, in doExtractChapterUrlsAndMetadata
    return self.extractChapterUrlsAndMetadata()
  File "c:\python27\lib\site-packages\fanficfare\adapters\base_xenforoforum_adapter.py", line 327, in extractChapterUrlsAndMetadata
    self.chapterUrls.append((prepend+tm['title']+append,tm['url']))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 30: ordinal not in range(128)
```

It's the only story that I have seen this error at. Other stories download normally
And it is different than the earlier errors

**Comment by JimmXinu** [comment]
Fixed in d9d776e8d279053fd21cb969d18571af96d5b10f
