### ISSUE TITLE
Stories with over 1000 chapters error out if there is a comma

### ISSUE THREAD

**Issue by ksurl** [JimmXinu/FanFicFare#250]
examples would be Desolate Era on wuxiaworld. I run `fanficfare -u file.epub` and then it spits out this:

```
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\fanficfare.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\fanficfare\cli.py", line 267, in main
    passed_personalini)
  File "c:\python27\lib\site-packages\fanficfare\cli.py", line 387, in do_download
    urlchaptercount = int(adapter.getStoryMetadataOnly().getMetadata('numChapters'))
ValueError: invalid literal for int() with base 10: '1,181'
```

other stories I see with this issue: Emperor's Domination and Warlock of the Magus World

**Comment by JimmXinu** [comment]
Fixed in fb8c9c1.  Test CLI 2.19.1 uploaded to pypitest for pip install.  
Thanks for pointing this out.
