### ISSUE TITLE
Error downloading some fanfics from ficbook.net

### ISSUE THREAD

**Issue by KKido** [JimmXinu/FanFicFare#261]
Most are fine, but for example this one: https://ficbook.net/readfic/456648 gives me error:

```
kido@arch64 ~/b/a/ficbook.net> fanficfare -v
Version: 2.20.0

kido@arch64 ~/b/a/ficbook.net> fanficfare -d -p https://ficbook.net/readfic/456648
FFF: DEBUG: 2018-01-03 06:29:56,562: adapter_ficbooknet.py(77): URL: https://www.ficbook.net/readfic/456648
FFF: DEBUG: 2018-01-03 06:29:56,562: configurable.py(1038): #####################################
pagecache(GET) MISS: https://www.ficbook.net/readfic/456648
.FFF: DEBUG: 2018-01-03 06:29:57,213: adapter_ficbooknet.py(106): Title: (Годайме Хокаге)
FFF: DEBUG: 2018-01-03 06:29:57,219: adapter_ficbooknet.py(114): Author: (katss)
Traceback (most recent call last):
  File "/usr/bin/fanficfare", line 11, in <module>
    load_entry_point('FanFicFare==2.20.0', 'console_scripts', 'fanficfare')()
  File "/usr/lib/python2.7/site-packages/fanficfare/cli.py", line 267, in main
    passed_personalini)
  File "/usr/lib/python2.7/site-packages/fanficfare/cli.py", line 364, in do_download
    adapter.getStoryMetadataOnly()
  File "/usr/lib/python2.7/site-packages/fanficfare/adapters/base_adapter.py", line 231, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "/usr/lib/python2.7/site-packages/fanficfare/adapters/base_adapter.py", line 315, in doExtractChapterUrlsAndMetadata
    return self.extractChapterUrlsAndMetadata()
  File "/usr/lib/python2.7/site-packages/fanficfare/adapters/adapter_ficbooknet.py", line 126, in extractChapterUrlsAndMetadata
    pubdate = translit.translit(stripHTML(chapter.parent.find('span')))
  File "/usr/lib/python2.7/site-packages/fanficfare/htmlcleanup.py", line 63, in stripHTML
    return soup.get_text(strip=True)
AttributeError: 'NoneType' object has no attribute 'get_text'
```

**Comment by JimmXinu** [comment]
Looks like they don't always put the date on the first chapter.  I've fixed it in 4b89d917b4fa69cbbc38f6040c4b43a4d1a2d712, but I'm not dead sure that's correct since I don't read Russian.

You can test this by installing from the pip test area:
`pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare`

**Comment by KKido** [comment]
Works for me. Thank you.

**Comment by arisboch** [comment]
I have the same problem and the proposed solution here doesn't work

```
% sudo  pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare
Looking in indexes: https://pypi.org/simple, https://testpypi.python.org/pypi
Collecting FanFicFare
  Downloading https://test-files.pythonhosted.org/packages/9a/30/322e72cc2d7e9a4a09b3a1efea688a21eec678a1862e9d7c97ad0e13cb1d/FanFicFare-3.12.9.tar.gz (338kB)
    100% |████████████████████████████████| 348kB 765kB/s 
Requirement already satisfied, skipping upgrade: beautifulsoup4 in /usr/lib/python2.7/dist-packages (from FanFicFare) (4.8.0)
Requirement already satisfied, skipping upgrade: chardet in /usr/lib/python2.7/dist-packages (from FanFicFare) (3.0.4)
Requirement already satisfied, skipping upgrade: html5lib in /usr/lib/python2.7/dist-packages (from FanFicFare) (1.0.1)
Collecting html2text (from FanFicFare)
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://test.pypi.org/project/html2text/
```

Maybe my python environment has degraded too much?

**Comment by JimmXinu** [comment]
That problem was over a year ago--that fix has been incorporated into the released version.

I suspect that if you install FanFicFare released version fix, it will pick up all the necessary dependencies:

```pip install --upgrade FanFicFare```

If you are still having a problem with the released version, please open a new issue.
