### ISSUE TITLE
Allow fanficfare -u filename.epub

### ISSUE THREAD

**Issue by mcepl** [JimmXinu/FanFicFare#347]
Every ``.epub`` file contains in its metadata in the property ``dc:source`` URL of the original source file. It could be possible then to add ability for the fanficfare script to pick up this URL from there and check for possible updates without users digging it up manually.

**Comment by JimmXinu** [comment]
Already works that way.  Although if you have seen it not work, I would like to hear about it.

```
  -u, --update-epub     Update an existing epub(if present) with new chapters.
                        Give either epub filename or story URL.
```

**Comment by mcepl** [comment]
Apparently, we have some python3 problem.
```
matej@stitny: fanfiction$ fanficfare -u The\ Accidental\ Animagus-ffnet_9863146.epub 
Updating The Accidental Animagus-ffnet_9863146.epub, URL: b'https://www.fanfiction.net/s/9863146/1/'
Traceback (most recent call last):
  File "/home/matej/.local/bin/fanficfare", line 11, in <module>
    load_entry_point('FanFicFare', 'console_scripts', 'fanficfare')()
  File "/usr/lib/python3.6/site-packages/fanficfare/cli.py", line 284, in main
    passed_personalini)
  File "/usr/lib/python3.6/site-packages/fanficfare/cli.py", line 331, in do_download
    output_filename)
  File "/usr/lib/python3.6/site-packages/fanficfare/cli.py", line 502, in get_configuration
    configuration = Configuration(adapters.getConfigSectionsFor(url), options.format)
  File "/usr/lib/python3.6/site-packages/fanficfare/adapters/__init__.py", line 287, in getConfigSectionsFor
    (cls,fixedurl) = _get_class_for(url)
  File "/usr/lib/python3.6/site-packages/fanficfare/adapters/__init__.py", line 296, in _get_class_for
    fixedurl = re.sub(r"(?i)^[htp]+(s?)[:/]+",r"http\1://",url.strip())
  File "/usr/lib64/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object
matej@stitny: fanfiction$
```

**Comment by hawkrives** [comment]
@mcepl That looks like the same error I had in https://github.com/JimmXinu/FanFicFare/issues/339, which @JimmXinu fixed in 
https://github.com/JimmXinu/FanFicFare/commit/db731e5296dc96b0ef6c678cd9959d540349d200.

(I see different line numbers in your error, so I don't think you're on an outdated version; I just wanted to link the two issues together.)

**Comment by mcepl** [comment]
Yes, it is probably outdated FanFicFare. Sorry.

**Comment by JimmXinu** [comment]
I agree with @hawkrives that this appears to be a duplicate of #339.

I plan to do a v3.1 release this week.
