### ISSUE TITLE
wuxiaworld adapter broken

### ISSUE THREAD

**Issue by ksurl** [JimmXinu/FanFicFare#355]
here is the debug output

```
fanficfare -d https://www.wuxiaworld.com/novel/stop-friendly-fire
FFF: DEBUG: 2018-10-27 14:25:06,676: cli.py(184):     OS Version:Windows-10-10.0.17763-SP0
FFF: DEBUG: 2018-10-27 14:25:06,676: cli.py(185): Python Version:3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
FFF: DEBUG: 2018-10-27 14:25:06,677: cli.py(186):    FFF Version:3.1.0
FFF: DEBUG: 2018-10-27 14:25:06,693: adapter_wuxiaworldcom.py(81): URL: https://www.wuxiaworld.com/novel/stop-friendly-fire
FFF: DEBUG: 2018-10-27 14:25:06,694: configurable.py(1099): #####################################
pagecache(GET) MISS: https://www.wuxiaworld.com/novel/stop-friendly-fire
Traceback (most recent call last):
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python36\Scripts\fanficfare-script.py", line 11, in <module>
    load_entry_point('FanFicFare==3.1.0', 'console_scripts', 'fanficfare')()
  File "c:\users\kevin\appdata\local\programs\python\python36\lib\site-packages\fanficfare\cli.py", line 290, in main
    passed_personalini)
  File "c:\users\kevin\appdata\local\programs\python\python36\lib\site-packages\fanficfare\cli.py", line 402, in do_download
    adapter.getStoryMetadataOnly()
  File "c:\users\kevin\appdata\local\programs\python\python36\lib\site-packages\fanficfare\adapters\base_adapter.py", line 281, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "c:\users\kevin\appdata\local\programs\python\python36\lib\site-packages\fanficfare\adapters\base_adapter.py", line 365, in doExtractChapterUrlsAndMetadata
    return self.extractChapterUrlsAndMetadata()
  File "c:\users\kevin\appdata\local\programs\python\python36\lib\site-packages\fanficfare\adapters\adapter_wuxiaworldcom.py", line 94, in extractChapterUrlsAndMetadata
    self.story.setMetadata('title', ld['headline'])
KeyError: 'headline'
```

same error when using -u to update an existing epub.
the last time it was working for me was Oct 17, 10 days ago.

**Comment by JimmXinu** [comment]
Already fixed in 934ad4a5842be896d8381f486d99d77fd17c4421.  Test versions are in the usual places.
