### ISSUE TITLE
royalroad adapter broken (Story Not Found not working)

### ISSUE THREAD

**Issue by ksurl** [JimmXinu/FanFicFare#356]
debug output:
```
fanficfare -d  https://royalroadl.com/fiction/3442
FFF: DEBUG: 2018-10-28 12:54:16,667: cli.py(184):     OS Version:Windows-10-10.0.17763-SP0
FFF: DEBUG: 2018-10-28 12:54:16,667: cli.py(185): Python Version:3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
FFF: DEBUG: 2018-10-28 12:54:16,669: cli.py(186):    FFF Version:3.1.7
FFF: DEBUG: 2018-10-28 12:54:16,689: adapter_royalroadcom.py(151): URL: https://www.royalroad.com/fiction/3442
FFF: DEBUG: 2018-10-28 12:54:16,689: configurable.py(1099): #####################################
pagecache(GET) MISS: https://www.royalroad.com/fiction/3442
Traceback (most recent call last):
  File "C:\Users\$user\AppData\Local\Programs\Python\Python36\Scripts\fanficfare-script.py", line 11, in <module>
    load_entry_point('FanFicFare==3.1.7', 'console_scripts', 'fanficfare')()
  File "c:\users\$user\appdata\local\programs\python\python36\lib\site-packages\fanficfare-3.1.7-py3.6.egg\fanficfare\cli.py", line 290, in main
    passed_personalini)
  File "c:\users\$user\appdata\local\programs\python\python36\lib\site-packages\fanficfare-3.1.7-py3.6.egg\fanficfare\cli.py", line 402, in do_download
    adapter.getStoryMetadataOnly()
  File "c:\users\$user\appdata\local\programs\python\python36\lib\site-packages\fanficfare-3.1.7-py3.6.egg\fanficfare\adapters\base_adapter.py", line 287, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "c:\users\$user\appdata\local\programs\python\python36\lib\site-packages\fanficfare-3.1.7-py3.6.egg\fanficfare\adapters\base_adapter.py", line 371, in doExtractChapterUrlsAndMetadata
    return self.extractChapterUrlsAndMetadata()
  File "c:\users\$user\appdata\local\programs\python\python36\lib\site-packages\fanficfare-3.1.7-py3.6.egg\fanficfare\adapters\adapter_royalroadcom.py", line 167, in extractChapterUrlsAndMetadata
    title = soup.select_one('.fic-header h1[property=name]').text
AttributeError: 'NoneType' object has no attribute 'text'
```

this is on test version 3.1.7 which included the wuxiaworld fix

**Comment by JimmXinu** [comment]
That story URL _says_ 404 Not Found, but the actual response code is 200 (success), bypassing the code that detects `StoryDoesNotExist` for royalroad.com.

I've added code to also report that as `StoryDoesNotExist` (5be7b3e78847805191466b2f9ddfaa28a01dfd19) and uploaded a new CLI test version.

**Comment by ksurl** [comment]
actually you know what, there is no bug. I did not check until now but the actual story has been deleted by the author from the site. it seems they published on Amazon as a Kindle ebook and removed their free web version
