### ISSUE TITLE
Downloading some stories from adult-fanfiction.org fails

### ISSUE THREAD

**Issue by KKido** [JimmXinu/FanFicFare#375]
```
kido@arch64 ~/temp> fanficfare -d 'http://hp.adult-fanfiction.org/story.php?no=600093890'
FFF: DEBUG: 2019-02-05 00:56:24,415: cli.py(184):     OS Version:Linux-4.19.19-1-lts-x86_64-with-arch
FFF: DEBUG: 2019-02-05 00:56:24,415: cli.py(185): Python Version:3.7.2 (default, Jan 10 2019, 23:51:51)
[GCC 8.2.1 20181127]
FFF: DEBUG: 2019-02-05 00:56:24,415: cli.py(186):    FFF Version:3.4.4
FFF: DEBUG: 2019-02-05 00:56:24,440: adapter_adultfanfictionorg.py(201): URL: http://hp.adult-fanfiction.org/story.php?no=600093890
FFF: DEBUG: 2019-02-05 00:56:24,440: configurable.py(1102): #####################################
pagecache(GET) MISS: http://hp.adult-fanfiction.org/story.php?no=600093890
FFF: DEBUG: 2019-02-05 00:56:24,940: adapter_adultfanfictionorg.py(268): Getting the author page: http://members.adult-fanfiction.org/profile.php?no=1296777934&view=story&zone=hp&page=1
FFF: DEBUG: 2019-02-05 00:56:24,940: configurable.py(1102): #####################################
pagecache(GET) MISS: http://members.adult-fanfiction.org/profile.php?no=1296777934&view=story&zone=hp&page=1
Traceback (most recent call last):
  File "/usr/bin/fanficfare", line 11, in <module>
    load_entry_point('FanFicFare==3.4.4', 'console_scripts', 'fanficfare')()
  File "/usr/lib/python3.7/site-packages/fanficfare/cli.py", line 290, in main
    passed_personalini)
  File "/usr/lib/python3.7/site-packages/fanficfare/cli.py", line 402, in do_download
    adapter.getStoryMetadataOnly()
  File "/usr/lib/python3.7/site-packages/fanficfare/adapters/base_adapter.py", line 287, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "/usr/lib/python3.7/site-packages/fanficfare/adapters/adapter_adultfanfictionorg.py", line 330, in doExtractChapterUrlsAndMetadata
    if page > pages:
TypeError: '>' not supported between instances of 'int' and 'str'
```

**Comment by JimmXinu** [comment]
I pushed a test CLI version.  You should be able to install it with:

> `pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare`

**Comment by KKido** [comment]
I can confirm that it now downloads/updates all the stories from that site that I have in my library. Thank you.
