### ISSUE TITLE
AO3 updates Download utility and FFF couldn't be used to download AO3 stories

### ISSUE THREAD

**Issue by AEliona** [JimmXinu/FanFicFare#381]
Hello, to read more about AO3 update on 24/02/2019 please click [here](https://archiveofourown.org/admin_posts/12386)

Basically, AO3 just release a new update that completely screws how FFF works with getting url and downloading AO3 stories.

I was trying to download several AO3 stories by FFF, no success--all job returned unsuccessful:

example link https://archiveofourown.org/works/12935199

log
`
Status
Title
Author
Comment
URL
Error
Kasta inte sten i glashus
Brian J Christopher (ikudou), Clarisse_McClellan
<urlopen error [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions>
https://archiveofourown.org/works/12935199
` 

detail from job

```
Download 1 FanFiction Book(s)
FFF: INFO: 2019-02-26 04:06:34,286: calibre_plugins.fanficfare_plugin.jobs(50): FanFicFare v3.5.0
FFF: INFO: 2019-02-26 04:06:34,286: calibre_plugins.fanficfare_plugin.jobs(54): Adding jobs for URLs:
FFF: INFO: 2019-02-26 04:06:34,286: calibre_plugins.fanficfare_plugin.jobs(56): https://archiveofourown.org/works/12935199
FFF: INFO: 2019-02-26 04:07:03,512: calibre_plugins.fanficfare_plugin.jobs(92): Logfile for book ID None (Kasta inte sten i glashus)
FFF: INFO: 2019-02-26 04:07:03,513: calibre_plugins.fanficfare_plugin.jobs(93): url:(https://archiveofourown.org/works/12935199) id:(None)
FFF: INFO: 2019-02-26 04:06:38,099: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_archiveofourownorg(147): url: https://archiveofourown.org/works/12935199/navigate?view_adult=true
FFF: INFO: 2019-02-26 04:06:38,099: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_archiveofourownorg(148): metaurl: https://archiveofourown.org/works/12935199?view_adult=true
FFF: DEBUG: 2019-02-26 04:06:38,101: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1092): #####################################
pagecache(GET) HIT: https://archiveofourown.org/works/12935199/navigate?view_adult=true
FFF: DEBUG: 2019-02-26 04:06:38,105: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1092): #####################################
pagecache(GET) HIT: https://archiveofourown.org/works/12935199?view_adult=true
FFF: DEBUG: 2019-02-26 04:06:39,582: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_archiveofourownorg(240): numChapters: (1)
FFF: INFO: 2019-02-26 04:06:40,480: calibre_plugins.fanficfare_plugin.jobs(220): write to C:\Users\JONQUI~1\AppData\Local\Temp\calibre_zr_ngn\fanficfare__xz9kh\Kasta inte sten i glashus-Brian J Christopher (ikudou)_ Clarisse_McClellan-wcb_qr.epub
FFF: INFO: 2019-02-26 04:06:40,483: calibre_plugins.fanficfare_plugin.fanficfare.writers.base_writer(183): Save directly to file: C:\Users\JONQUI~1\AppData\Local\Temp\calibre_zr_ngn\fanficfare__xz9kh\Kasta inte sten i glashus-Brian J Christopher (ikudou)_ Clarisse_McClellan-wcb_qr.epub
FFF: DEBUG: 2019-02-26 04:06:40,486: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_archiveofourownorg(388): Getting chapter text for: https://archiveofourown.org/works/12935199/chapters/29561610 index: 0
FFF: DEBUG: 2019-02-26 04:06:40,499: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1102): #####################################
pagecache(GET) MISS: https://archiveofourown.org/works/12935199/chapters/29561610
FFF: DEBUG: 2019-02-26 04:06:43,592: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1179): Caught an exception reading URL: https://archiveofourown.org/works/12935199/chapters/29561610 sleeptime(0) Exception <urlopen error [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions>.
FFF: DEBUG: 2019-02-26 04:06:44,092: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1102): #####################################
pagecache(GET) MISS: https://archiveofourown.org/works/12935199/chapters/29561610
FFF: DEBUG: 2019-02-26 04:06:46,115: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1179): Caught an exception reading URL: https://archiveofourown.org/works/12935199/chapters/29561610 sleeptime(0.5) Exception <urlopen error [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions>.
FFF: DEBUG: 2019-02-26 04:06:50,118: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1102): #####################################
pagecache(GET) MISS: https://archiveofourown.org/works/12935199/chapters/29561610
FFF: DEBUG: 2019-02-26 04:06:52,141: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1179): Caught an exception reading URL: https://archiveofourown.org/works/12935199/chapters/29561610 sleeptime(4) Exception <urlopen error [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions>.
FFF: DEBUG: 2019-02-26 04:07:01,144: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1102): #####################################
pagecache(GET) MISS: https://archiveofourown.org/works/12935199/chapters/29561610
FFF: DEBUG: 2019-02-26 04:07:03,167: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1179): Caught an exception reading URL: https://archiveofourown.org/works/12935199/chapters/29561610 sleeptime(9) Exception <urlopen error [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions>.
FFF: DEBUG: 2019-02-26 04:07:03,167: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1181): Giving up on https://archiveofourown.org/works/12935199/chapters/29561610
FFF: DEBUG: 2019-02-26 04:07:03,167: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1182): <urlopen error [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions>
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1170, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1129, in _fetchUrlRawOpened
  File "urllib2.py", line 431, in open
  File "urllib2.py", line 449, in _open
  File "urllib2.py", line 409, in _call_chain
  File "urllib2.py", line 1240, in https_open
  File "urllib2.py", line 1197, in do_open
URLError: <urlopen error [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions>
FFF: INFO: 2019-02-26 04:07:03,170: calibre_plugins.fanficfare_plugin.jobs(318): Exception: {u'collision': u'Update EPUB if New Chapters', u'author_sort': [u'Brian J Christopher (ikudou)', u'Clarisse_McClellan'], u'author': [u'Brian J Christopher (ikudou)', u'Clarisse_McClellan'], u'pubdate': datetime.datetime(2017, 12, 6, 0, 0, tzinfo=SafeLocalTimeZone()), u'added': False, u'begin': None, u'timestamp': datetime.datetime(2019, 2, 26, 4, 6, 38, 58000, tzinfo=SafeLocalTimeZone()), u'username': 'NoneGiven', u'good': False, u'comments': u'<div class="userstuff">\n              <p>\u041f\u0435\u0440\u0435\u0432\u043e\u0434 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u044f: \xab\u041d\u0435 \u0431\u0440\u043e\u0441\u0430\u0439\u0442\u0435 \u043a\u0430\u043c\u043d\u0438 \u0432 \u0441\u0442\u0435\u043a\u043b\u044f\u043d\u043d\u043e\u043c \u0434\u043e\u043c\u0435\xbb. (\u0428\u0432\u0435\u0434\u0441\u043a\u0430\u044f \u043f\u043e\u0433\u043e\u0432\u043e\u0440\u043a\u0430)</p><p>\u041d\u0430\u043f\u0438\u0441\u0430\u043d\u043e \u043d\u0430 hartwin fest \u043f\u043e \u0437\u0430\u044f\u0432\u043a\u0435 3.18: "\u0425\u0430\u0440\u0442\u0432\u0438\u043d \u0433\u043b\u0430\u0437\u0430\u043c\u0438 \u0422\u0438\u043b\u044c\u0434\u0435. \u041e\u0442\u043d\u043e\u0448\u0435\u043d\u0438\u044f \u043c\u0443\u0436\u0430 \u0438 \u0435\u0433\u043e \u0431\u044b\u0432\u0448\u0435\u0433\u043e \u043d\u0430\u0441\u0442\u0430\u0432\u043d\u0438\u043a\u0430 \u0435\u0439 \u043f\u043e\u043f\u0435\u0440\u0435\u043a \u0433\u043e\u0440\u043b\u0430, \u043d\u043e \u043e\u043d\u0430 \u043d\u0438\u0447\u0435\u0433\u043e \u043d\u0435 \u043c\u043e\u0436\u0435\u0442 \u043f\u043e\u0434\u0435\u043b\u0430\u0442\u044c. \u0421\u043b\u0435\u0437\u044b, \u0440\u0430\u0437\u0431\u043e\u0440\u043a\u0438, \u043f\u043e\u043f\u044b\u0442\u043a\u0438 \u0441\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u043b\u0438\u0446\u043e \u043d\u0430 \u043b\u044e\u0434\u044f\u0445. \u0412\u0441\u0435\u043c \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0430\u043c \u0442\u0440\u0435\u0443\u0433\u043e\u043b\u044c\u043d\u0438\u043a\u0430 \u043e\u0447\u0435\u043d\u044c \u043f\u043b\u043e\u0445\u043e".</p><p>\u041f\u041e\u0412 \u0422\u0438\u043b\u044c\u0434\u0435. \u0425\u0430\u0440\u0442\u0432\u0438\u043d \u2013 \u043e\u0434\u043d\u043e\u0441\u0442\u043e\u0440\u043e\u043d\u043d\u0438\u0439. \u0427\u0438\u0442\u0430\u0442\u044c \u043d\u0430 \u0441\u0432\u043e\u0439 \u0441\u0442\u0440\u0430\u0445 \u0438 \u0440\u0438\u0441\u043a. \u041a\u0430\u043a \u0438 \u0441\u043a\u0430\u0437\u0430\u043d\u043e \u0432 \u0437\u0430\u044f\u0432\u043a\u0435 \u2013 \u0441\u043b\u0435\u0437\u044b, \u0440\u0430\u0437\u0431\u043e\u0440\u043a\u0438, \u0432\u0441\u0435\u043c \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0430\u043c \u0442\u0440\u0435\u0443\u0433\u043e\u043b\u044c\u043d\u0438\u043a\u0430 \u043e\u0447\u0435\u043d\u044c \u043f\u043b\u043e\u0445\u043e. \u041f\u043e\u043b\u043d\u043e\u0446\u0435\u043d\u043d\u044b\u0439 \u0425\u042d \u043d\u0435 \u043f\u043e\u043b\u0443\u0447\u0430\u0435\u0442 \u043d\u0438\u043a\u0442\u043e.</p>\n            </div>', u'icon': u'dialog_error.png', u'showerror': True, u'series': u'\u0421\u0442\u0435\u043a\u043b\u044f\u043d\u043d\u044b\u0439 \u0434\u043e\u043c [1]', u'all_metadata': {'hits': u'721', 'numChapters': u'1', 'authorUrl': u'https://archiveofourown.org/users/ikudou/pseuds/Brian%20J%20Christopher, https://archiveofourown.org/users/Clarisse_McClellan/pseuds/Clarisse_McClellan', 'series': u'\u0421\u0442\u0435\u043a\u043b\u044f\u043d\u043d\u044b\u0439 \u0434\u043e\u043c [1]', 'ships': u'Harry Hart | Galahad & Gary "Eggsy" Unwin, Tilde/Gary "Eggsy" Unwin', 'formatext': '', 'extratags': u'FanFiction', 'author': u'Brian J Christopher (ikudou), Clarisse_McClellan', 'ao3categories': u'F/M', 'series02Url': '', 'series00Url': u'https://archiveofourown.org/series/959436', 'authorId': u'Brian%20J%20Christopher, Clarisse_McClellan', 'authorHTML': u"<a class='authorlink' href='https://archiveofourown.org/users/ikudou/pseuds/Brian%20J%20Christopher'>Brian J Christopher (ikudou)</a>, <a class='authorlink' href='https://archiveofourown.org/users/Clarisse_McClellan/pseuds/Clarisse_McClellan'>Clarisse_McClellan</a>", 'byline': u'Brian J Christopher (ikudou),Clarisse_McClellan', 'kudos': u'62', 'lastupdate': u'Last Update Year/Month: 2017/12, Last Update: 2017/12/06', 'sectionUrl': u'https://archiveofourown.org/works/12935199', 'series02HTML': u'', 'numWords': u'16,407', 'rating': u'Mature', 'seriesUrl': u'https://archiveofourown.org/series/959436', 'seriesHTML': u"<a class='serieslink' href='https://archiveofourown.org/series/959436'>\u0421\u0442\u0435\u043a\u043b\u044f\u043d\u043d\u044b\u0439 \u0434\u043e\u043c [1]</a>", 'formatname': '', 'version': u'FanFicFare v3.5.0', 'collections': '', 'series01Url': '', 'series01HTML': u'', 'storyUrl': u'https://archiveofourown.org/works/12935199', 'bookmarkprivate': '', 'output_css': '', 'series01': '', 'series00': u'\u0421\u0442\u0435\u043a\u043b\u044f\u043d\u043d\u044b\u0439 \u0434\u043e\u043c [1]', 'series03': '', 'series02': '', 'bookmarkrec': '', 'title': u'Kasta inte sten i glashus', 'language': u'\u0420\u0443\u0441\u0441\u043a\u0438\u0439', 'bookmarktags': '', 'freefromtags': u'Drama, One-sided Harry/Eggsy, POV Tilde, Post-Canon', 'cover_image': '', 'fandoms': u'Kingsman (Movies)', 'site': u'archiveofourown.org', 'series03HTML': u'', 'series03Url': '', 'warnings': u'No Archive Warnings Apply', 'words_added': '', 'status': u'Completed', 'storyId': u'12935199', 'titleHTML': u"<a class='titlelink' href='https://archiveofourown.org/works/12935199'>Kasta inte sten i glashus</a>", 'characters': u'Gary "Eggsy" Unwin, Harry Hart | Galahad, Tilde (Kingsman)', 'dateCreated': u'2019-02-26 04:06:12', 'datePublished': u'2017-12-06', 'freeformtags': u'Drama, One-sided Harry/Eggsy, POV Tilde, Post-Canon', 'bookmarks': u'3', 'bookmarksummary': '', 'comments': u'5', 'description': u'<div class="userstuff">\n              <p>\u041f\u0435\u0440\u0435\u0432\u043e\u0434 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u044f: \xab\u041d\u0435 \u0431\u0440\u043e\u0441\u0430\u0439\u0442\u0435 \u043a\u0430\u043c\u043d\u0438 \u0432 \u0441\u0442\u0435\u043a\u043b\u044f\u043d\u043d\u043e\u043c \u0434\u043e\u043c\u0435\xbb. (\u0428\u0432\u0435\u0434\u0441\u043a\u0430\u044f \u043f\u043e\u0433\u043e\u0432\u043e\u0440\u043a\u0430)</p><p>\u041d\u0430\u043f\u0438\u0441\u0430\u043d\u043e \u043d\u0430 hartwin fest \u043f\u043e \u0437\u0430\u044f\u0432\u043a\u0435 3.18: "\u0425\u0430\u0440\u0442\u0432\u0438\u043d \u0433\u043b\u0430\u0437\u0430\u043c\u0438 \u0422\u0438\u043b\u044c\u0434\u0435. \u041e\u0442\u043d\u043e\u0448\u0435\u043d\u0438\u044f \u043c\u0443\u0436\u0430 \u0438 \u0435\u0433\u043e \u0431\u044b\u0432\u0448\u0435\u0433\u043e \u043d\u0430\u0441\u0442\u0430\u0432\u043d\u0438\u043a\u0430 \u0435\u0439 \u043f\u043e\u043f\u0435\u0440\u0435\u043a \u0433\u043e\u0440\u043b\u0430, \u043d\u043e \u043e\u043d\u0430 \u043d\u0438\u0447\u0435\u0433\u043e \u043d\u0435 \u043c\u043e\u0436\u0435\u0442 \u043f\u043e\u0434\u0435\u043b\u0430\u0442\u044c. \u0421\u043b\u0435\u0437\u044b, \u0440\u0430\u0437\u0431\u043e\u0440\u043a\u0438, \u043f\u043e\u043f\u044b\u0442\u043a\u0438 \u0441\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u043b\u0438\u0446\u043e \u043d\u0430 \u043b\u044e\u0434\u044f\u0445. \u0412\u0441\u0435\u043c \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0430\u043c \u0442\u0440\u0435\u0443\u0433\u043e\u043b\u044c\u043d\u0438\u043a\u0430 \u043e\u0447\u0435\u043d\u044c \u043f\u043b\u043e\u0445\u043e".</p><p>\u041f\u041e\u0412 \u0422\u0438\u043b\u044c\u0434\u0435. \u0425\u0430\u0440\u0442\u0432\u0438\u043d \u2013 \u043e\u0434\u043d\u043e\u0441\u0442\u043e\u0440\u043e\u043d\u043d\u0438\u0439. \u0427\u0438\u0442\u0430\u0442\u044c \u043d\u0430 \u0441\u0432\u043e\u0439 \u0441\u0442\u0440\u0430\u0445 \u0438 \u0440\u0438\u0441\u043a. \u041a\u0430\u043a \u0438 \u0441\u043a\u0430\u0437\u0430\u043d\u043e \u0432 \u0437\u0430\u044f\u0432\u043a\u0435 \u2013 \u0441\u043b\u0435\u0437\u044b, \u0440\u0430\u0437\u0431\u043e\u0440\u043a\u0438, \u0432\u0441\u0435\u043c \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0430\u043c \u0442\u0440\u0435\u0443\u0433\u043e\u043b\u044c\u043d\u0438\u043a\u0430 \u043e\u0447\u0435\u043d\u044c \u043f\u043b\u043e\u0445\u043e. \u041f\u043e\u043b\u043d\u043e\u0446\u0435\u043d\u043d\u044b\u0439 \u0425\u042d \u043d\u0435 \u043f\u043e\u043b\u0443\u0447\u0430\u0435\u0442 \u043d\u0438\u043a\u0442\u043e.</p>\n            </div>', 'series00HTML': u"<a class='series00link' href='https://archiveofourown.org/series/959436'>\u0421\u0442\u0435\u043a\u043b\u044f\u043d\u043d\u044b\u0439 \u0434\u043e\u043c [1]</a>", 'langcode': u'ru', 'genre': u'Drama, F/M, One-sided Harry/Eggsy, POV Tilde, Post-Canon', 'siteabbrev': u'ao3', 'dateUpdated': u'2017-12-06', 'category': u'Kingsman (Movies)'}, u'outfile': u'C:\\Users\\JONQUI~1\\AppData\\Local\\Temp\\calibre_zr_ngn\\fanficfare__xz9kh\\Kasta inte sten i glashus-Brian J Christopher (ikudou)_ Clarisse_McClellan-wcb_qr.epub', u'calibre_id': None, u'updatedate': datetime.datetime(2017, 12, 6, 0, 0, tzinfo=SafeLocalTimeZone()), u'comment': u'<urlopen error [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions>', u'is_adult': True, u'url': u'https://archiveofourown.org/works/12935199', u'uniqueurl': u'https://archiveofourown.org/works/12935199[None-None]', u'title': u'Kasta inte sten i glashus', u'end': None, u'publisher': u'archiveofourown.org', u'site': 'archiveofourown.org', u'status': u'Error', u'listorder': 0, u'tags': [u'Tilde (Kingsman)', u'Harry Hart | Galahad', u'Tilde/Gary "Eggsy" Unwin', 'FanFiction', u'Gary "Eggsy" Unwin', u'One-sided Harry/Eggsy', u'Completed', u'POV Tilde', u'Kingsman (Movies)', u'Harry Hart | Galahad & Gary "Eggsy" Unwin', u'Drama', u'F/M', u'Post-Canon'], u'calibre_columns': {}, u'password': ''}:<urlopen error [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions>
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.jobs", line 222, in do_download_for_worker
  File "calibre_plugins.fanficfare_plugin.fanficfare.writers.base_writer", line 202, in writeStory
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 228, in getStory
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_archiveofourownorg", line 409, in getChapterTextNum
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1293, in _fetchUrl
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1282, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1183, in _fetchUrlOpened
URLError: <urlopen error [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions>

FFF: INFO: 2019-02-26 04:07:03,513: calibre_plugins.fanficfare_plugin.jobs(102): 
Download Results:
https://archiveofourown.org/works/12935199 <urlopen error [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions>

FFF: INFO: 2019-02-26 04:07:03,513: calibre_plugins.fanficfare_plugin.jobs(104): 
Successful:


FFF: INFO: 2019-02-26 04:07:03,513: calibre_plugins.fanficfare_plugin.jobs(105): 
Unsuccessful:
https://archiveofourown.org/works/12935199


```

**Comment by jschpp** [comment]
I can't reproduce this error:

```
Lade 1 FanFiction Bücher herunter
FFF: INFO: 2019-02-26 12:07:49,471: calibre_plugins.fanficfare_plugin.jobs(50): FanFicFare v3.5.0
FFF: INFO: 2019-02-26 12:07:49,471: calibre_plugins.fanficfare_plugin.jobs(54): Adding jobs for URLs:
FFF: INFO: 2019-02-26 12:07:49,471: calibre_plugins.fanficfare_plugin.jobs(56): https://archiveofourown.org/works/12935199

FFF: INFO: 2019-02-26 12:07:58,059: calibre_plugins.fanficfare_plugin.jobs(92): Logfile for book ID None (Kasta inte sten i glashus)
FFF: INFO: 2019-02-26 12:07:58,062: calibre_plugins.fanficfare_plugin.jobs(93): url:(https://archiveofourown.org/works/12935199) id:(None)
FFF: INFO: 2019-02-26 12:07:51,730: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_archiveofourownorg(147): url: https://archiveofourown.org/works/12935199/navigate?view_adult=true
FFF: INFO: 2019-02-26 12:07:51,730: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_archiveofourownorg(148): metaurl: https://archiveofourown.org/works/12935199?view_adult=true
FFF: DEBUG: 2019-02-26 12:07:51,730: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1092): #####################################
pagecache(GET) HIT: https://archiveofourown.org/works/12935199/navigate?view_adult=true
FFF: DEBUG: 2019-02-26 12:07:51,732: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1092): #####################################
pagecache(GET) HIT: https://archiveofourown.org/works/12935199?view_adult=true
FFF: DEBUG: 2019-02-26 12:07:52,305: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_archiveofourownorg(240): numChapters: (1)
FFF: INFO: 2019-02-26 12:07:52,668: calibre_plugins.fanficfare_plugin.jobs(220): write to C:\Users\schoeppj\AppData\Local\Temp\calibre_uk9cxj\fanficfare_md6sbq\Kasta inte sten i glashus-Brian J Christopher (ikudou)_ Clarisse_McClellan-y1syrj.epub
FFF: INFO: 2019-02-26 12:07:52,671: calibre_plugins.fanficfare_plugin.fanficfare.writers.base_writer(183): Save directly to file: C:\Users\schoeppj\AppData\Local\Temp\calibre_uk9cxj\fanficfare_md6sbq\Kasta inte sten i glashus-Brian J Christopher (ikudou)_ Clarisse_McClellan-y1syrj.epub
FFF: DEBUG: 2019-02-26 12:07:52,671: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_archiveofourownorg(388): Getting chapter text for: https://archiveofourown.org/works/12935199/chapters/29561610 index: 0
FFF: DEBUG: 2019-02-26 12:07:52,678: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1102): #####################################
pagecache(GET) MISS: https://archiveofourown.org/works/12935199/chapters/29561610

FFF: INFO: 2019-02-26 12:07:58,062: calibre_plugins.fanficfare_plugin.jobs(102): 
Download Ergebnisse:
https://archiveofourown.org/works/12935199 Herunterladen epub abgeschlossen, 1 Kapitel.

FFF: INFO: 2019-02-26 12:07:58,062: calibre_plugins.fanficfare_plugin.jobs(104): 
Erfolgreich:
https://archiveofourown.org/works/12935199

FFF: INFO: 2019-02-26 12:07:58,062: calibre_plugins.fanficfare_plugin.jobs(105): 
Erfolglos:
```

**Comment by JimmXinu** [comment]
I can't duplicate this either.

I don't see anything in the AO3 Changelog that should cause any problems.

My first thought is that it was a temporary site issue.  Are you still having problems?

My second thought is that perhaps you are behind a firewall or proxy that is preventing normal access?

**Comment by AEliona** [comment]
Hello, thanks for the reply. I think it was the lagging post-update of AO3. Apparently AO3 is slowly deleting old ebook and generating new ebook so download is fussy as hell occasionally. I tried again this morning today, and things were working out again (thank God for that).
