### ISSUE TITLE
Cannot upgrade from fictionhunt.com

### ISSUE THREAD

**Issue by mcepl** [JimmXinu/FanFicFare#388]
```sh
~$ fanficfare -u Knihy/fanfiction/Hermione\ Granger\ and\ the\ Hostile\ Decision-fichunt_11638640.epub 
Updating Knihy/fanfiction/Hermione Granger and the Hostile Decision-fichunt_11638640.epub, URL: http://fictionhunt.com/read/11638640/1
.Traceback (most recent call last):
  File "/usr/bin/fanficfare", line 11, in <module>
    load_entry_point('FanFicFare==3.5.0', 'console_scripts', 'fanficfare')()
  File "/usr/lib/python3.7/site-packages/fanficfare/cli.py", line 290, in main
    passed_personalini)
  File "/usr/lib/python3.7/site-packages/fanficfare/cli.py", line 402, in do_download
    adapter.getStoryMetadataOnly()
  File "/usr/lib/python3.7/site-packages/fanficfare/adapters/base_adapter.py", line 287, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "/usr/lib/python3.7/site-packages/fanficfare/adapters/adapter_fictionhuntcom.py", line 83, in doExtractChapterUrlsAndMetadata
    self.story.setMetadata('title',stripHTML(soup.find('div',{'class':'title'})).strip())
  File "/usr/lib/python3.7/site-packages/fanficfare/htmlcleanup.py", line 71, in stripHTML
    retval = soup.get_text(strip=True)
AttributeError: 'NoneType' object has no attribute 'get_text'
~$
```
The URL is http://fictionhunt.com/read/11638640/ (also, the script doesn't seem to recognize switch from HTTP to HTTPS).

**Comment by JimmXinu** [comment]
Already fixed in ee172fa0af7c4ed8fc9fe7dbf1972c7831ca0f36.  Posted in the latest test versions.
