### ISSUE TITLE
IMAP stopped working

### ISSUE THREAD

**Issue by Edocsil** [JimmXinu/FanFicFare#419]
I just updated fanficfare and now I'm getting this error.

```
$ fanficfare -d --download-imap --update-epub
FFF: DEBUG: 2019-07-28 00:04:27,320: cli.py(184):     OS Version:Linux-3.14.79-x86_64-gd9184e9-i686-with-libc
FFF: DEBUG: 2019-07-28 00:04:27,320: cli.py(185): Python Version:3.7.4 (default, Jul 11 2019, 08:24:41)
[Clang 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf6
FFF: DEBUG: 2019-07-28 00:04:27,320: cli.py(186):    FFF Version:3.10.0
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/fanficfare", line 10, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/fanficfare/cli.py", line 253, in main
    markread)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/fanficfare/geturls.py", line 227, in get_urls_from_imap
    m = re.match(r'^\(.*\) "." "(.+)"$',f)
  File "/data/data/com.termux/files/usr/lib/python3.7/re.py", line 173, in match
    return _compile(pattern, flags).match(string)
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by JimmXinu** [comment]
Python 3 yet again.  I've uploaded v3.10.1 with a fix to pip.  Thanks for pointing that out.
