### ISSUE TITLE
HTTP 400 error on get urls from page with AO3 url

### ISSUE THREAD

**Issue by matjojo** [JimmXinu/FanFicFare#427]
On trying to get all story urls from this page: 
https://archiveofourown.org/works?utf8=✓&work_search[sort_column]=revised_at&work_search[other_tag_names]=&work_search[excluded_tag_names]=&work_search[crossover]=&work_search[complete]=&work_search[words_from]=&work_search[words_to]=&work_search[date_from]=&work_search[date_to]=&work_search[query]=&work_search[language_id]=1&commit=Sort+and+Filter&tag_id=Passengers+(2016)
I get an HTTP 400 error. I assume this might have to do with the length of the URL or the tick emoji that they use in the url for utf8. 

This is the trace:
```
calibre, version 3.48.0
ERROR: Unhandled exception: <b>HTTPError</b>:HTTP Error 400: Bad Request

calibre 3.48 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.15+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: FanFicFare (3, 11, 0) && Count Pages (1, 8, 2)
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 547, in get_urls_from_page_menu
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 566, in get_urls_from_page
  File "calibre_plugins.fanficfare_plugin.fanficfare.geturls", line 81, in get_urls_from_page
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1325, in _fetchUrl
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1314, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1215, in _fetchUrlOpened
HTTPError: HTTP Error 400: Bad Request
```

I think all info you might need is in the trace, but if you need anything more just ask.

EDIT:
I've been trying some options, and it seems like you get the same webpage as reply back when you don't use the tick emoji, but you do need to keep the utf8 url parameter in the url.

**Comment by matjojo** [comment]
I ran it in debug mode as well, to see if the log would show more info. Nothing that I'd recognize. But it might help you a bit.


```
calibre Debug log
calibre 3.48 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.15+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: FanFicFare (3, 11, 0) && Count Pages (1, 8, 2)
calibre 3.48 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.15+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: FanFicFare (3, 11, 0) && Count Pages (1, 8, 2)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.238993711 x 102.358208955
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.11] splash screen shown
[0.11] Initializing db...
[0.47] db initialized
[0.47] Constructing main UI...
FFF: DEBUG: 2019-09-15 17:23:56,315: calibre_plugins.fanficfare_plugin.fff_plugin(207): Plugin FanFicFare macmenuhack file_path:C:\Users\User\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
[2.91] main UI initialized...
[2.91] Hiding splash screen
[33.00] splash screen hidden
[33.00] Started up in 33.00 seconds with 9107 books
FFF: DEBUG: 2019-09-15 17:24:53,957: calibre_plugins.fanficfare_plugin.fff_plugin(560): get_urls_from_page URL:https://archiveofourown.org/works?utf8=✓&work_search[sort_column]=revised_at&work_search[other_tag_names]=&work_search[excluded_tag_names]=&work_search[crossover]=&work_search[complete]=&work_search[words_from]=&work_search[words_to]=&work_search[date_from]=&work_search[date_to]=&work_search[query]=&work_search[language_id]=1&commit=Sort+and+Filter&tag_id=Passengers+(2016)
FFF: DEBUG: 2019-09-15 17:24:53,980: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1128): #####################################
pagecache(GET) MISS: https://archiveofourown.org/works?utf8=✓&work_search[sort_column]=revised_at&work_search[other_tag_names]=&work_search[excluded_tag_names]=&work_search[crossover]=&work_search[complete]=&work_search[words_from]=&work_search[words_to]=&work_search[date_from]=&work_search[date_to]=&work_search[query]=&work_search[language_id]=1&commit=Sort+and+Filter&tag_id=Passengers+(2016)
FFF: DEBUG: 2019-09-15 17:24:56,888: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1128): #####################################
pagecache(GET) MISS: https://archiveofourown.org/works?utf8=✓&work_search[sort_column]=revised_at&work_search[other_tag_names]=&work_search[excluded_tag_names]=&work_search[crossover]=&work_search[complete]=&work_search[words_from]=&work_search[words_to]=&work_search[date_from]=&work_search[date_to]=&work_search[query]=&work_search[language_id]=1&commit=Sort+and+Filter&tag_id=Passengers+(2016)
FFF: DEBUG: 2019-09-15 17:25:03,318: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1128): #####################################
pagecache(GET) MISS: https://archiveofourown.org/works?utf8=✓&work_search[sort_column]=revised_at&work_search[other_tag_names]=&work_search[excluded_tag_names]=&work_search[crossover]=&work_search[complete]=&work_search[words_from]=&work_search[words_to]=&work_search[date_from]=&work_search[date_to]=&work_search[query]=&work_search[language_id]=1&commit=Sort+and+Filter&tag_id=Passengers+(2016)
FFF: DEBUG: 2019-09-15 17:25:15,095: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1128): #####################################
pagecache(GET) MISS: https://archiveofourown.org/works?utf8=✓&work_search[sort_column]=revised_at&work_search[other_tag_names]=&work_search[excluded_tag_names]=&work_search[crossover]=&work_search[complete]=&work_search[words_from]=&work_search[words_to]=&work_search[date_from]=&work_search[date_to]=&work_search[query]=&work_search[language_id]=1&commit=Sort+and+Filter&tag_id=Passengers+(2016)
FFF: DEBUG: 2019-09-15 17:25:17,512: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1213): Giving up on https://archiveofourown.org/works?utf8=✓&work_search[sort_column]=revised_at&work_search[other_tag_names]=&work_search[excluded_tag_names]=&work_search[crossover]=&work_search[complete]=&work_search[words_from]=&work_search[words_to]=&work_search[date_from]=&work_search[date_to]=&work_search[query]=&work_search[language_id]=1&commit=Sort+and+Filter&tag_id=Passengers+(2016)
FFF: DEBUG: 2019-09-15 17:25:17,512: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1214): HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1201, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1160, in _fetchUrlRawOpened
  File "urllib2.py", line 435, in open
  File "urllib2.py", line 548, in http_response
  File "urllib2.py", line 473, in error
  File "urllib2.py", line 407, in _call_chain
  File "urllib2.py", line 556, in http_error_default
HTTPError: HTTP Error 400: Bad Request
calibre 3.48 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.15+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: FanFicFare (3, 11, 0) && Count Pages (1, 8, 2)
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 547, in get_urls_from_page_menu
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 566, in get_urls_from_page
  File "calibre_plugins.fanficfare_plugin.fanficfare.geturls", line 81, in get_urls_from_page
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1325, in _fetchUrl
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1314, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1215, in _fetchUrlOpened
HTTPError: HTTP Error 400: Bad Request

```

**Comment by JimmXinu** [comment]
I do see this error as well.

It works if `utf8=✓` is encoded as `utf8=%E2%9C%93`--which is what Firefox does for me if I copy the given link from URL bar while on the page.  Given URL also works for me in Win10 in CLI--in Python2, but not py3.

This is one of those joyous problems that I can solve in py2 or py3 or calibre, but fixing it with the same code in _all_ of them is a tedious matter of trial and error.  I think I have a fix, though.

**Comment by JimmXinu** [comment]
New test version posted in the [usual place](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2).

**Comment by JimmXinu** [comment]
63d3d235f2295b6c8ceb06d90d72a96b45642e7a
