### ISSUE TITLE
Image  not found! exception on AO3

### ISSUE THREAD

**Issue by mcepl** [JimmXinu/FanFicFare#442]
```python
fanfiction@stitny$ fanficfare -u **/*Weight*
Updating The Weight of the After-ao3_8449852.epub, URL: https://archiveofourown.org/works/8449852
..FFF: WARNING: 2019-10-25 07:40:16,079: epubutils.py(145): Image  not found!
(originally:)
FFF: WARNING: 2019-10-25 07:40:16,079: epubutils.py(146): Exception: 'src'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/fanficfare/epubutils.py", line 132, in get_update_data
    newsrc=get_path_part(href)+img['src']
  File "/usr/lib/python3.7/site-packages/bs4/element.py", line 971, in __getitem__
    return self.attrs[key]
KeyError: 'src'
Do update - epub(5) vs url(6)
.fanfiction@stitny$
```
When downloading the EPub fresh, the exception doesn't happen.

**Comment by JimmXinu** [comment]
I cannot reproduce this.  Can you attach the epub that you're seeing the problem with?

**Comment by mcepl** [comment]
Oh well, I cannot reproduce it either. Oh well.
