### ISSUE TITLE
Questionable Questing bug on 24h time-format (https://forum.questionablequesting.com)(base_xenforoforum)

### ISSUE THREAD

**Issue by tr13dm03** [JimmXinu/FanFicFare#445]
Downloading stories from QuestionableQuesting fails if the account preferences have time display set to 24h.

```
FFF: DEBUG: 2019-11-11 04:30:49,470: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1001): Encoding:utf8
FFF: INFO: 2019-11-11 04:30:49,473: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter(432): use useurl: https://forum.questionablequesting.com/threads/stuck-in-youkai-academy-rosario-vampire-omamori-himari-friendinsert.10822/#post-2965348
FFF: DEBUG: 2019-11-11 04:30:51,789: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter(649): No date found in <a class="datePermalink" href="threads/stuck-in-youkai-academy-rosario-vampire-omamori-himari-friendinsert.10822/" title="Permalink"><abbr class="DateTime" data-datestring="Nov 9, 2019" data-diff="117583" data-time="1573329057" data-timestring="19:50">Nov 9, 2019 at 19:50</abbr></a>, going on without
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter", line 647, in make_date
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 624, in makeDate
  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '11 09, 2019 at 19:50' does not match format '%m %d, %Y at %I:%M '
FFF: DEBUG: 2019-11-11 04:30:51,894: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter(649): No date found in None, going on without
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter", line 637, in make_date
AttributeError: 'NoneType' object has no attribute 'find'
FFF: INFO: 2019-11-11 04:30:52,438: calibre_plugins.fanficfare_plugin.jobs(248): write to /tmp/calibre_3.39.1_tmp_Lgq2Fc/fanficfare_7zrqio/Stuck in Youkai Academy-Ricrod-GUjoA9.epub
FFF: INFO: 2019-11-11 04:30:52,444: calibre_plugins.fanficfare_plugin.fanficfare.writers.base_writer(183): Save directly to file: /tmp/calibre_3.39.1_tmp_Lgq2Fc/fanficfare_7zrqio/Stuck in Youkai Academy-Ricrod-GUjoA9.epub
FFF: DEBUG: 2019-11-11 04:30:52,449: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter(673): Getting chapter text for: https://forum.questionablequesting.com/posts/2965348/ index: 0
FFF: DEBUG: 2019-11-11 04:30:52,449: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter(709): DON'T USE READER MODE
FFF: DEBUG: 2019-11-11 04:30:57,569: calibre_plugins.fanficfare_plugin.wordcount(59): 	Word count - count_words method:9102
FFF: INFO: 2019-11-11 04:30:57,570: calibre_plugins.fanficfare_plugin.jobs(311): get_word_count:9102
FFF: INFO: 2019-11-11 04:30:57,580: calibre_plugins.fanficfare_plugin.fanficfare.writers.base_writer(183): Save directly to file: /tmp/calibre_3.39.1_tmp_Lgq2Fc/fanficfare_7zrqio/Stuck in Youkai Academy-Ricrod-GUjoA9.epub

FFF: INFO: 2019-11-11 04:30:58,875: calibre_plugins.fanficfare_plugin.jobs(98): 
Download Results:
Add https://forum.questionablequesting.com/posts/2965348/ Download epub completed, 1 chapters.
```

Replacing `'%m %d, %Y at %I:%M '` with `'%m %d, %Y at %H:%M '` works, so a fallback that tries 24h if 12h fails would probably fix it.

**Comment by JimmXinu** [comment]
Usually I would tell you that FFF only supports the default settings for each supported site.

But given that 12 vs 24 hr clock times already has some special code in FFF due to locale issues, it's not an extraordinary ask.

8d2f9198c2b5aa3b2ee481718223b6b6f55db8c6  

[Test version plugin posted](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2).
