### ISSUE TITLE
SB and sv dl failure

### ISSUE THREAD

**Issue by kyoam** [JimmXinu/FanFicFare#488]
HTTP Error 503: Service Temporarily Unavailable
https://forums.spacebattles.com/threads/ghost-in-the-flesh-worm-love-death-and-robots.819108/
HTTP Error 503: Service Temporarily Unavailable
https://forums.sufficientvelocity.com/threads/hybrid-hive-eat-shard-worm-mgln.55056/
HTTP Error 503: Service Temporarily Unavailable
https://forums.sufficientvelocity.com/threads/magical-girl-escalation-taylor-worm-nanoha.28074/
HTTP Error 503: Service Temporarily Unavailable
https://forums.spacebattles.com/threads/amazing-fantasy-my-hero-academia-spider-man.703948/
HTTP Error 503: Service Temporarily Unavailable
https://forums.spacebattles.com/threads/trailblazer-worm-gundam-au.680881/

might be caused by anti ddos services now being used by both sites

could not attach debug log will paste below

calibre Debug log
calibre 4.14 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: FanFicFare (3, 18, 0)
calibre 4.14 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: FanFicFare (3, 18, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 70.8837209302 x 70.7010309278
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.56] splash screen shown
[0.56] Initializing db...
[0.58] db initialized
[0.58] Constructing main UI...
FFF: DEBUG: 2020-04-30 01:28:13,979: calibre_plugins.fanficfare_plugin.fff_plugin(209): Plugin FanFicFare macmenuhack file_path:C:\Users\Owner\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
[1.95] main UI initialized...
[1.95] Hiding splash screen
[66.02] splash screen hidden
[66.02] Started up in 66.02 seconds with 67 books
FFF: DEBUG: 2020-04-30 01:29:23,687: calibre_plugins.fanficfare_plugin.fff_plugin(968): add_tag:None
FFF: DEBUG: 2020-04-30 01:29:23,723: calibre_plugins.fanficfare_plugin.fff_plugin(978): FanFicFare v3.18.0
FFF: DEBUG: 2020-04-30 01:29:23,767: calibre_plugins.fanficfare_plugin.fff_plugin(1092): url:https://forums.spacebattles.com/threads/ghost-in-the-flesh-worm-love-death-and-robots.819108/
FFF: INFO: 2020-04-30 01:29:23,767: calibre_plugins.fanficfare_plugin.prefs(208): Attempting to read settings from predecessor--FFDL
FFF: INFO: 2020-04-30 01:29:23,767: calibre_plugins.fanficfare_plugin.prefs(213): Using default settings
FFF: INFO: 2020-04-30 01:29:23,802: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter(417): url: https://forums.spacebattles.com/threads/ghost-in-the-flesh-worm-love-death-and-robots.819108/
FFF: DEBUG: 2020-04-30 01:29:23,803: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1128): #####################################
pagecache(GET) MISS: https://forums.spacebattles.com/threads/ghost-in-the-flesh-worm-love-death-and-robots.819108/
FFF: DEBUG: 2020-04-30 01:29:31,826: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1128): #####################################
pagecache(GET) MISS: https://forums.spacebattles.com/threads/ghost-in-the-flesh-worm-love-death-and-robots.819108/
FFF: DEBUG: 2020-04-30 01:29:42,006: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1128): #####################################
pagecache(GET) MISS: https://forums.spacebattles.com/threads/ghost-in-the-flesh-worm-love-death-and-robots.819108/
FFF: DEBUG: 2020-04-30 01:29:57,194: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1128): #####################################
pagecache(GET) MISS: https://forums.spacebattles.com/threads/ghost-in-the-flesh-worm-love-death-and-robots.819108/
FFF: DEBUG: 2020-04-30 01:30:03,375: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1221): Giving up on https://forums.spacebattles.com/threads/ghost-in-the-flesh-worm-love-death-and-robots.819108/
FFF: DEBUG: 2020-04-30 01:30:03,375: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1222): HTTP Error 503: Service Temporarily Unavailable
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1203, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1162, in _fetchUrlRawOpened
  File "urllib2.py", line 435, in open
  File "urllib2.py", line 548, in http_response
  File "urllib2.py", line 473, in error
  File "urllib2.py", line 407, in _call_chain
  File "urllib2.py", line 556, in http_error_default
HTTPError: HTTP Error 503: Service Temporarily Unavailable
FFF: ERROR: 2020-04-30 01:30:03,375: calibre_plugins.fanficfare_plugin.dialogs(711): Exception: {u'calibre_id': None, u'listorder': 0, u'added': False, u'author_sort': [u'Unknown'], u'url': u'https://forums.spacebattles.com/threads/ghost-in-the-flesh-worm-love-death-and-robots.819108/', u'uniqueurl': u'https://forums.spacebattles.com/threads/ghost-in-the-flesh-worm-love-death-and-robots.819108/[None-None]', u'showerror': True, u'good': False, u'comment': u'HTTP Error 503: Service Temporarily Unavailable', u'site': 'forums.spacebattles.com', u'author': [u'Unknown'], u'status': u'Error', u'collision': u'Add New Book', u'comments': u'', u'end': None, u'begin': None, u'title': u'Unknown', u'pubdate': None, u'publisher': None, u'series': u''}:HTTP Error 503: Service Temporarily Unavailable
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.dialogs", line 698, in do_loop
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1177, in prep_download_loop
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1059, in get_story_metadata_only
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 297, in getStoryMetadataOnly
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 381, in doExtractChapterUrlsAndMetadata
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter", line 420, in extractChapterUrlsAndMetadata
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter", line 103, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1322, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1223, in _fetchUrlOpened
HTTPError: HTTP Error 503: Service Temporarily Unavailable
FFF: DEBUG: 2020-04-30 01:30:03,434: calibre_plugins.fanficfare_plugin.fff_plugin(1092): url:https://forums.sufficientvelocity.com/threads/hybrid-hive-eat-shard-worm-mgln.55056/
FFF: INFO: 2020-04-30 01:30:03,463: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter(417): url: https://forums.sufficientvelocity.com/threads/hybrid-hive-eat-shard-worm-mgln.55056/
FFF: DEBUG: 2020-04-30 01:30:03,463: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1128): #####################################
pagecache(GET) MISS: https://forums.sufficientvelocity.com/threads/hybrid-hive-eat-shard-worm-mgln.55056/
FFF: DEBUG: 2020-04-30 01:30:11,374: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1128): #####################################
pagecache(GET) MISS: https://forums.sufficientvelocity.com/threads/hybrid-hive-eat-shard-worm-mgln.55056/
FFF: DEBUG: 2020-04-30 01:30:21,533: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1128): #####################################
pagecache(GET) MISS: https://forums.sufficientvelocity.com/threads/hybrid-hive-eat-shard-worm-mgln.55056/
FFF: DEBUG: 2020-04-30 01:30:36,691: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1128): #####################################
pagecache(GET) MISS: https://forums.sufficientvelocity.com/threads/hybrid-hive-eat-shard-worm-mgln.55056/
FFF: DEBUG: 2020-04-30 01:30:42,845: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1221): Giving up on https://forums.sufficientvelocity.com/threads/hybrid-hive-eat-shard-worm-mgln.55056/
FFF: DEBUG: 2020-04-30 01:30:42,845: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1222): HTTP Error 503: Service Temporarily Unavailable
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1203, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1162, in _fetchUrlRawOpened
  File "urllib2.py", line 435, in open
  File "urllib2.py", line 548, in http_response
  File "urllib2.py", line 473, in error
  File "urllib2.py", line 407, in _call_chain
  File "urllib2.py", line 556, in http_error_default
HTTPError: HTTP Error 503: Service Temporarily Unavailable
FFF: ERROR: 2020-04-30 01:30:42,845: calibre_plugins.fanficfare_plugin.dialogs(711): Exception: {u'calibre_id': None, u'listorder': 1, u'added': False, u'author_sort': [u'Unknown'], u'url': u'https://forums.sufficientvelocity.com/threads/hybrid-hive-eat-shard-worm-mgln.55056/', u'uniqueurl': u'https://forums.sufficientvelocity.com/threads/hybrid-hive-eat-shard-worm-mgln.55056/[None-None]', u'showerror': True, u'good': False, u'comment': u'HTTP Error 503: Service Temporarily Unavailable', u'site': 'forums.sufficientvelocity.com', u'author': [u'Unknown'], u'status': u'Error', u'collision': u'Add New Book', u'comments': u'', u'end': None, u'begin': None, u'title': u'Unknown', u'pubdate': None, u'publisher': None, u'series': u''}:HTTP Error 503: Service Temporarily Unavailable
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.dialogs", line 698, in do_loop
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1177, in prep_download_loop
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1059, in get_story_metadata_only
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 297, in getStoryMetadataOnly
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 381, in doExtractChapterUrlsAndMetadata
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter", line 420, in extractChapterUrlsAndMetadata
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter", line 103, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1322, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1223, in _fetchUrlOpened
HTTPError: HTTP Error 503: Service Temporarily Unavailable
FFF: DEBUG: 2020-04-30 01:30:42,872: calibre_plugins.fanficfare_plugin.fff_plugin(1092): url:https://forums.sufficientvelocity.com/threads/magical-girl-escalation-taylor-worm-nanoha.28074/
FFF: INFO: 2020-04-30 01:30:42,901: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter(417): url: https://forums.sufficientvelocity.com/threads/magical-girl-escalation-taylor-worm-nanoha.28074/
FFF: DEBUG: 2020-04-30 01:30:42,901: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1128): #####################################
pagecache(GET) MISS: https://forums.sufficientvelocity.com/threads/magical-girl-escalation-taylor-worm-nanoha.28074/
FFF: DEBUG: 2020-04-30 01:30:49,552: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1128): #####################################
pagecache(GET) MISS: https://forums.sufficientvelocity.com/threads/magical-girl-escalation-taylor-worm-nanoha.28074/
FFF: DEBUG: 2020-04-30 01:30:59,736: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1128): #####################################
pagecache(GET) MISS: https://forums.sufficientvelocity.com/threads/magical-girl-escalation-taylor-worm-nanoha.28074/
FFF: DEBUG: 2020-04-30 01:31:14,894: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1128): #####################################
pagecache(GET) MISS: https://forums.sufficientvelocity.com/threads/magical-girl-escalation-taylor-worm-nanoha.28074/
FFF: DEBUG: 2020-04-30 01:31:21,063: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1221): Giving up on https://forums.sufficientvelocity.com/threads/magical-girl-escalation-taylor-worm-nanoha.28074/
FFF: DEBUG: 2020-04-30 01:31:21,063: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1222): HTTP Error 503: Service Temporarily Unavailable
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1203, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1162, in _fetchUrlRawOpened
  File "urllib2.py", line 435, in open
  File "urllib2.py", line 548, in http_response
  File "urllib2.py", line 473, in error
  File "urllib2.py", line 407, in _call_chain
  File "urllib2.py", line 556, in http_error_default
HTTPError: HTTP Error 503: Service Temporarily Unavailable
FFF: ERROR: 2020-04-30 01:31:21,065: calibre_plugins.fanficfare_plugin.dialogs(711): Exception: {u'calibre_id': None, u'listorder': 2, u'added': False, u'author_sort': [u'Unknown'], u'url': u'https://forums.sufficientvelocity.com/threads/magical-girl-escalation-taylor-worm-nanoha.28074/', u'uniqueurl': u'https://forums.sufficientvelocity.com/threads/magical-girl-escalation-taylor-worm-nanoha.28074/[None-None]', u'showerror': True, u'good': False, u'comment': u'HTTP Error 503: Service Temporarily Unavailable', u'site': 'forums.sufficientvelocity.com', u'author': [u'Unknown'], u'status': u'Error', u'collision': u'Add New Book', u'comments': u'', u'end': None, u'begin': None, u'title': u'Unknown', u'pubdate': None, u'publisher': None, u'series': u''}:HTTP Error 503: Service Temporarily Unavailable
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.dialogs", line 698, in do_loop
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1177, in prep_download_loop
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1059, in get_story_metadata_only
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 297, in getStoryMetadataOnly
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 381, in doExtractChapterUrlsAndMetadata
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter", line 420, in extractChapterUrlsAndMetadata
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter", line 103, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1322, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1223, in _fetchUrlOpened
HTTPError: HTTP Error 503: Service Temporarily Unavailable
FFF: DEBUG: 2020-04-30 01:31:21,102: calibre_plugins.fanficfare_plugin.fff_plugin(1092): url:https://forums.spacebattles.com/threads/amazing-fantasy-my-hero-academia-spider-man.703948/
FFF: INFO: 2020-04-30 01:31:21,131: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter(417): url: https://forums.spacebattles.com/threads/amazing-fantasy-my-hero-academia-spider-man.703948/
FFF: DEBUG: 2020-04-30 01:31:21,131: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1128): #####################################
pagecache(GET) MISS: https://forums.spacebattles.com/threads/amazing-fantasy-my-hero-academia-spider-man.703948/
FFF: DEBUG: 2020-04-30 01:31:27,818: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1128): #####################################
pagecache(GET) MISS: https://forums.spacebattles.com/threads/amazing-fantasy-my-hero-academia-spider-man.703948/
FFF: DEBUG: 2020-04-30 01:31:37,996: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1128): #####################################
pagecache(GET) MISS: https://forums.spacebattles.com/threads/amazing-fantasy-my-hero-academia-spider-man.703948/
FFF: DEBUG: 2020-04-30 01:31:53,186: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1128): #####################################
pagecache(GET) MISS: https://forums.spacebattles.com/threads/amazing-fantasy-my-hero-academia-spider-man.703948/
FFF: DEBUG: 2020-04-30 01:31:59,392: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1221): Giving up on https://forums.spacebattles.com/threads/amazing-fantasy-my-hero-academia-spider-man.703948/
FFF: DEBUG: 2020-04-30 01:31:59,392: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1222): HTTP Error 503: Service Temporarily Unavailable
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1203, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1162, in _fetchUrlRawOpened
  File "urllib2.py", line 435, in open
  File "urllib2.py", line 548, in http_response
  File "urllib2.py", line 473, in error
  File "urllib2.py", line 407, in _call_chain
  File "urllib2.py", line 556, in http_error_default
HTTPError: HTTP Error 503: Service Temporarily Unavailable
FFF: ERROR: 2020-04-30 01:31:59,394: calibre_plugins.fanficfare_plugin.dialogs(711): Exception: {u'calibre_id': None, u'listorder': 3, u'added': False, u'author_sort': [u'Unknown'], u'url': u'https://forums.spacebattles.com/threads/amazing-fantasy-my-hero-academia-spider-man.703948/', u'uniqueurl': u'https://forums.spacebattles.com/threads/amazing-fantasy-my-hero-academia-spider-man.703948/[None-None]', u'showerror': True, u'good': False, u'comment': u'HTTP Error 503: Service Temporarily Unavailable', u'site': 'forums.spacebattles.com', u'author': [u'Unknown'], u'status': u'Error', u'collision': u'Add New Book', u'comments': u'', u'end': None, u'begin': None, u'title': u'Unknown', u'pubdate': None, u'publisher': None, u'series': u''}:HTTP Error 503: Service Temporarily Unavailable
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.dialogs", line 698, in do_loop
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1177, in prep_download_loop
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1059, in get_story_metadata_only
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 297, in getStoryMetadataOnly
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 381, in doExtractChapterUrlsAndMetadata
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter", line 420, in extractChapterUrlsAndMetadata
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter", line 103, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1322, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1223, in _fetchUrlOpened
HTTPError: HTTP Error 503: Service Temporarily Unavailable
FFF: DEBUG: 2020-04-30 01:31:59,407: calibre_plugins.fanficfare_plugin.fff_plugin(1092): url:https://forums.spacebattles.com/threads/trailblazer-worm-gundam-au.680881/
FFF: INFO: 2020-04-30 01:31:59,434: calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter(417): url: https://forums.spacebattles.com/threads/trailblazer-worm-gundam-au.680881/
FFF: DEBUG: 2020-04-30 01:31:59,434: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1128): #####################################
pagecache(GET) MISS: https://forums.spacebattles.com/threads/trailblazer-worm-gundam-au.680881/
FFF: DEBUG: 2020-04-30 01:32:06,108: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1128): #####################################
pagecache(GET) MISS: https://forums.spacebattles.com/threads/trailblazer-worm-gundam-au.680881/
FFF: DEBUG: 2020-04-30 01:32:16,301: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1128): #####################################
pagecache(GET) MISS: https://forums.spacebattles.com/threads/trailblazer-worm-gundam-au.680881/
FFF: DEBUG: 2020-04-30 01:32:31,479: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1128): #####################################
pagecache(GET) MISS: https://forums.spacebattles.com/threads/trailblazer-worm-gundam-au.680881/
FFF: DEBUG: 2020-04-30 01:32:37,660: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1221): Giving up on https://forums.spacebattles.com/threads/trailblazer-worm-gundam-au.680881/
FFF: DEBUG: 2020-04-30 01:32:37,660: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1222): HTTP Error 503: Service Temporarily Unavailable
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1203, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1162, in _fetchUrlRawOpened
  File "urllib2.py", line 435, in open
  File "urllib2.py", line 548, in http_response
  File "urllib2.py", line 473, in error
  File "urllib2.py", line 407, in _call_chain
  File "urllib2.py", line 556, in http_error_default
HTTPError: HTTP Error 503: Service Temporarily Unavailable
FFF: ERROR: 2020-04-30 01:32:37,660: calibre_plugins.fanficfare_plugin.dialogs(711): Exception: {u'calibre_id': None, u'listorder': 4, u'added': False, u'author_sort': [u'Unknown'], u'url': u'https://forums.spacebattles.com/threads/trailblazer-worm-gundam-au.680881/', u'uniqueurl': u'https://forums.spacebattles.com/threads/trailblazer-worm-gundam-au.680881/[None-None]', u'showerror': True, u'good': False, u'comment': u'HTTP Error 503: Service Temporarily Unavailable', u'site': 'forums.spacebattles.com', u'author': [u'Unknown'], u'status': u'Error', u'collision': u'Add New Book', u'comments': u'', u'end': None, u'begin': None, u'title': u'Unknown', u'pubdate': None, u'publisher': None, u'series': u''}:HTTP Error 503: Service Temporarily Unavailable
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.dialogs", line 698, in do_loop
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1177, in prep_download_loop
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1059, in get_story_metadata_only
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 297, in getStoryMetadataOnly
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 381, in doExtractChapterUrlsAndMetadata
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter", line 420, in extractChapterUrlsAndMetadata
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter", line 103, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1322, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1223, in _fetchUrlOpened
HTTPError: HTTP Error 503: Service Temporarily Unavailable

**Comment by JimmXinu** [comment]
I'm able to successfully download from both sites now.

`HTTP Error 503: Service Temporarily Unavailable` could well be just that--a temporary service issue.

However, since I know that SB/SV will block you if you download 'too much' at once, that could be what happened.

How many downloads were you doing?  Where you browsing the site at the same time?  I've been denied access for that before.

**Comment by kyoam** [comment]
5 4 from sb 1 from sv

**Comment by JimmXinu** [comment]
As I said, it may have truly been a temporary service issue.

However, if you are still seeing it, all I can offer you is the option to put longer sleeps between network reqs with a `personal.ini` setting, like:

```
[base_xenforoforum]
slow_down_sleep_time:8
```

...or reducing the number of parallel jobs by changing Calibre's Max BG jobs setting under Calibre's Preferences > Misc

**Comment by Thirsk** [comment]
Every time I actually try to access SB in a browser I run into a page for Cloudfare's DDoS protection, and every single download request through FFF (For SB/SV) returns with  Error 503. I'm no expert, but the two feel related. 
![ddos protection](https://user-images.githubusercontent.com/16472201/80848736-1d086c00-8bc9-11ea-871a-78609137cdef.png)

**Comment by JimmXinu** [comment]
If you can't access those sites from _browser_, then you definitely have a problem that is beyond FFF.

I would speculate that you (or someone on your network) was hitting the site hard enough to get on a black list.  Or that your network has been preemptively black listed.  Or that you are using an anonymizer, proxy, or VPN that looks funny or has been black listed.

Regardless, I don't think it's not an issue I can do anything about in FanFicFare.

**Comment by Thirsk** [comment]
Perhaps I misrepresented the issue. I am not blocked from accessing the site. 
As the screenshot shows, Cloudfare's DDoS protection runs a quick script that delays you for a couple of seconds before allowing you to access the site. A very large portion of the internet uses Cloudfare's services, so it seems a bit strange to me that you would declare that it's impossible to deal with the problem and just close the issue.

**Comment by JimmXinu** [comment]
I don't recall, and cannot find mention of, any other FFF users having trouble with Cloudflare such as you report.  So while, yes, Cloudflare is used by lots of sites, as far as FFF is concerned it's been entirely invisible up to this point.

Which, just like I said before, suggests your IP/computer/network is on a list somewhere.  Why and how, I can't say.  If you see this visiting a lot of sites, you might want to follow up and see if you can find out why and how to fix it.

As for why I'm declaring it 'impossible':
- FFF has no ability to run Javascript--nor am I interested in adding it.
- Without seeing the issue myself, it's very difficult to implement a work around even if I wanted to.

If I start seeing it myself, or if more users start reporting it, I will revisit it.
