### ISSUE TITLE
A 403 error?

### ISSUE THREAD

**Issue by DragoLord19D** [JimmXinu/FanFicFare#490]
When i try to get story URL from webpage from AH
https://www.alternatehistory.com/forum/threads/1944-us-isot-to-the-world-of-the-two-georges.338072/post-10438813

calibre, version 4.15.0
ERROR: Unhandled exception: <b>HTTPError</b>:HTTP Error 403: Forbidden

calibre 4.15 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 31, 0) && EpubMerge (2, 9, 0) && FanFicFare (3, 19, 0) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0)
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 566, in get_urls_from_page_menu
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 585, in get_urls_from_page
  File "calibre_plugins.fanficfare_plugin.fanficfare.geturls", line 81, in get_urls_from_page
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1338, in _fetchUrl
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_xenforoforum_adapter", line 103, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1327, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1228, in _fetchUrlOpened
HTTPError: HTTP Error 403: Forbidden

**Comment by JimmXinu** [comment]
I'm not seeing that error, but that page does require login.  Both `username`/`password` settings and entering user/pass when prompted worked for me.

That particular 5 year old post doesn't work well anyway because it's mostly outdated links that don't work anymore.  Such as https://www.alternatehistory.com/discussion/showthread.php?p=11410452#post11410452

`www.alternatehistory.com/discussion` isn't a valid URL path anymore.
