### ISSUE TITLE
URLError?

### ISSUE THREAD

**Issue by cybergipsy2020** [JimmXinu/FanFicFare#536]
I'm having URLError I don't know what to do with it. Please help.

```
calibre, version 4.23.0
ERROR: Unhandled exception: <b>URLError</b>:<urlopen error timed out>

calibre 4.23  embedded-python: True is64bit: True
Darwin-19.3.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.3.0', 'Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: EpubMerge (2, 10, 0) && F_rating (3, 2, 0) && FanFicFare (3, 22, 1)
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 568, in get_urls_from_page_menu
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 587, in get_urls_from_page
  File "calibre_plugins.fanficfare_plugin.fanficfare.geturls", line 65, in get_urls_from_page
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1346, in _fetchUrl
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1335, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1216, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1175, in _fetchUrlRawOpened
  File "lib/python2.7/urllib2.py", line 429, in open
  File "lib/python2.7/urllib2.py", line 447, in _open
  File "lib/python2.7/urllib2.py", line 407, in _call_chain
  File "lib/python2.7/urllib2.py", line 1241, in https_open
  File "lib/python2.7/urllib2.py", line 1198, in do_open
URLError: <urlopen error timed out>
```

**Comment by JimmXinu** [comment]
`URLError: <urlopen error timed out>` usually indicates that the problem is in the network or the site server.

If you give me the URL you're trying to use, I can try it and see what happens for me.

**Comment by cybergipsy2020** [comment]
Any random ao3 link seems not working for me. For example `https://archiveofourown.org/works/26115676`.

**Comment by JimmXinu** [comment]
Works fine for me.  And trust me; if FFF wasn't working with AO3 across the board, I'd be hearing about it from everybody.

So something in your network chain is failing.  If you are able to view the same URLs in browser without issue, it's possible that AO3 has decided you (or someone sharing your network at some level) is generating too much traffic and starting throttling or blocking you.  It's also possible that you have an anti-malware package or firewall that is 'helpfully' blocking FFF from going out.

I don't have a specific fix for you, nor is it really a problem with FFF itself.  Sorry.
