### ISSUE TITLE
novelupdates.cc KeyError: 'href'

### ISSUE THREAD

**Issue by JimmXinu** [JimmXinu/FanFicFare#555]
@ElminsterAU, can you look into this?

There's a [problem report](https://www.mobileread.com/forums/showthread.php?p=4035484#post4035484) on novelupdates.cc already.  I see it happen too:

```
FFF: DEBUG: 2020-09-16 14:54:56,965: calibre_plugins.fanficfare_plugin.fff_plugin(979): FanFicFare v3.23.3
FFF: DEBUG: 2020-09-16 14:54:56,996: calibre_plugins.fanficfare_plugin.fff_plugin(1093): url:https://www.novelupdates.cc/The-Legendary-Mechanic/
FFF: DEBUG: 2020-09-16 14:54:57,018: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_novelupdatescc(73): URL: https://www.novelupdates.cc/The-Legendary-Mechanic/
FFF: DEBUG: 2020-09-16 14:54:57,018: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1152): #####################################
pagecache(GET) MISS: https://www.novelupdates.cc/The-Legendary-Mechanic/
FFF: DEBUG: 2020-09-16 14:54:58,569: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1010): Encoding:utf8
FFF: DEBUG: 2020-09-16 14:54:59,023: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1152): #####################################
pagecache(GET) MISS: http://img.novelupdates.cc/BookFiles/BookImages/The-Legendary-Mechanic.jpg
FFF: ERROR: 2020-09-16 14:54:59,524: calibre_plugins.fanficfare_plugin.dialogs(714): Exception: {'title': 'Unknown', 'author_sort': ['Unknown'], 'author': ['Unknown'], 'comments': '', 'good': False, 'status': 'Error', 'showerror': True, 'calibre_id': None, 'begin': None, 'end': '5', 'comment': "'href'", 'url': 'https://www.novelupdates.cc/The-Legendary-Mechanic/', 'site': 'www.novelupdates.cc', 'series': '', 'added': False, 'pubdate': None, 'publisher': None, 'uniqueurl': 'https://www.novelupdates.cc/The-Legendary-Mechanic/[None-5]', 'listorder': 0, 'collision': 'Update EPUB if New Chapters'}:'href'
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.dialogs", line 701, in do_loop
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1178, in prep_download_loop
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1060, in get_story_metadata_only
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 297, in getStoryMetadataOnly
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 381, in doExtractChapterUrlsAndMetadata
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_novelupdatescc", line 90, in extractChapterUrlsAndMetadata
  File "site-packages\bs4\element.py", line 1401, in __getitem__
KeyError: 'href'
```

**Comment by ElminsterAU** [comment]
It's caused by the authorUrl change you made to the wuxiaworld.co adapter which I copied without checking (because I had calibre running in the middle of an 8h download at that time).

That change doesn't just break the novelupdates.cc adapter, I can also not download anything I tried from wuxiaworld.co anymore either with this latest test version.

do you want a PR that comments out 
```
        #self.story.setMetadata('authorUrl', author['href'])
```
in the 2 adapters or are you going to fix it yourself?

**Comment by JimmXinu** [comment]
Interesting.  I may have conflated wuxiaworld.site with wuxiaworld.co when I tested that earlier today.
