### ISSUE TITLE
[RoyalRoad]: Metadata extractor broken

### ISSUE THREAD

**Issue by hseg** [JimmXinu/FanFicFare#565]
URL tried: https://www.royalroad.com/fiction/31429
Fanficfare version: 3.23.15
```
Traceback (most recent call last):
  File "/usr/bin/fanficfare", line 33, in <module>
    sys.exit(load_entry_point('FanFicFare==3.23.15', 'console_scripts', 'fanficfare')())
  File "/usr/lib/python3.8/site-packages/fanficfare/cli.py", line 324, in main
    do_download(url,
  File "/usr/lib/python3.8/site-packages/fanficfare/cli.py", line 421, in do_download
    adapter.getStoryMetadataOnly()
  File "/usr/lib/python3.8/site-packages/fanficfare/adapters/base_adapter.py", line 297, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "/usr/lib/python3.8/site-packages/fanficfare/adapters/base_adapter.py", line 381, in doExtractChapterUrlsAndMetadata
    return self.extractChapterUrlsAndMetadata()
  File "/usr/lib/python3.8/site-packages/fanficfare/adapters/adapter_royalroadcom.py", line 177, in extractChapterUrlsAndMetadata
    author_link = mt_card_social('a')[-1]
TypeError: 'NoneType' object is not callable
```

**Comment by hseg** [comment]
A quick check of the relevant page suggests the issue might be due to the multiple `mt-card-social` divs, but I haven't played around with the code enough to be sure

**Comment by hseg** [comment]
OK, playing around with BeautifulSoup here suggests BS.find has changed semantics so that passing an empty string for the name parameter searches for children whose tag is literally the empty string. The correct value for no filtering is `None`, by my testing. Checking docs to make sure.
