### ISSUE TITLE
beautiful-soup4 version 4.9.3 (20201003) breaks fanficfare 3.23.1

### ISSUE THREAD

**Issue by jtwill** [JimmXinu/FanFicFare#567]
I just updated beautiful-soup4 to version 4.9.3 (20201003) and it broke fanficfare version 3.23.1

I verified that downgrading BS4 to 4.9.2 eliminated the problem.

Whenever I try to update an EPUB file from royalroad.com I get error messages like this:

Traceback (most recent call last):
  File ".../bin/fanficfare", line 8, in <module>
    sys.exit(main())  File ".../lib/python3.8/site-packages/fanficfare/cli.py", line 316, in main
    do_download(url,
  File ".../lib/python3.8/site-packages/fanficfare/cli.py", line 432, in do_download
    adapter.getStoryMetadataOnly()
  File ".../lib/python3.8/site-packages/fanficfare/adapters/base_adapter.py", line 297, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File ".../lib/python3.8/site-packages/fanficfare/adapters/base_adapter.py", line 381, in doExtractChapterUrlsAndMetadata
    return self.extractChapterUrlsAndMetadata()
  File ".../lib/python3.8/site-packages/fanficfare/adapters/adapter_royalroadcom.py", line 177, in extractChapterUrlsAndMetadata
    author_link = mt_card_social('a')[-1]
TypeError: 'NoneType' object is not callable

**Comment by JimmXinu** [comment]
Already reported in #565 and fixed in #566 

Test version of CLI is available in the testpypi repository.  This works for me on Debian:

`pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare` 

(In future, when reporting _any_ problem for FFF, please include a story URL that exhibits the problem.  Just because you see it everywhere, doesn't mean I will.)
