### ISSUE TITLE
Error HTTP:430

### ISSUE THREAD

**Issue by Moonaarita** [JimmXinu/FanFicFare#599]
When I tried to download a story from Wattpad from this link: https://www.wattpad.com/story/213950137-k%C3%ADnh-v%E1%BA%A1n-hoa-ch%E1%BA%BFt-ch%C3%B3c,  I got a message said HTTP Error 403.

Here is the message from the error:

calibre, version 5.5.0
ERROR: Unhandled exception: <b>HTTPError</b>:HTTP Error 403: Forbidden

calibre 5.5  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: EpubMerge (2, 11, 0) && FanFicFare (3, 25, 5)
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 667, in get_urls_from_page_menu
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 690, in get_urls_from_page
  File "calibre_plugins.fanficfare_plugin.fanficfare.geturls", line 46, in get_urls_from_page
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 414, in get_urls_from_page
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1355, in _fetchUrl
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1344, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1249, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1225, in _fetchUrlOpened
  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1186, in _fetchUrlRawOpened
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

This happened to every link of Wattpad since the last 2 updates. Please help me.

**Comment by JimmXinu** [comment]
Working for me, so I don't think there's anything wrong with FFF.

You're probably getting blocked by the site.  We see that happen when a site decides your IP is 'dangerous' or it's on a 'badlist' somewhere; or when you're downloading "too much".  Unfortunately, we don't know how much is "too much" for different sites. 

Usually, waiting a few days will clear it if you were blocked for "too much" traffic.  If you can change your out facing IP, or access via a different network or a VPN, you can frequently get around these blocks, but not always.

You can try to prevent it in future by setting a larger `slow_down_sleep_time` value in `personal.ini`.  Default for wattpad is 2.
