### ISSUE TITLE
Support for SoFurry.com

### ISSUE THREAD

**Issue by DarkYuan** [JimmXinu/FanFicFare#600]
This seems like it'd be simple because they have their own ePub exporting function, which includes all chapters of the given story as well. Some works may require login access however, not sure. But I don't know how to write the adapter myself.

Example story: [https://www.sofurry.com/view/1652851](https://www.sofurry.com/view/1652851)
Example's export link: [https://www.sofurry.com/export/ePub?id=1652851](https://www.sofurry.com/export/ePub?id=1652851)

**Comment by Denor78** [comment]
the Epub exporting function on the site doesn't work properly. it cant process parts that have unsupported formatting and most of the time it downloads just first chapter instead of the whole story.

there is still need to add support for SoFurry.com

**Comment by Anangaya** [comment]
Would be awesome if support for sofurry.com is added. +1

**Comment by digital1dragon** [comment]
What is needed to support the site? +1

**Comment by JimmXinu** [comment]
HTML fails to parse.  Site change?  Or different for different stories?

Example: https://sofurry.com/s/ek5K2rWn  
Reported here: https://www.mobileread.com/forums/showthread.php?p=4596482&postcount=12171

@dbhmw, can you take a look at this?

```
FFF: DEBUG: 2026-07-06 09:03:28,263: cli.py(231):     OS Version:Windows-10-10.0.19045-SP0
FFF: DEBUG: 2026-07-06 09:03:28,264: cli.py(232): Python Version:3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]
FFF: DEBUG: 2026-07-06 09:03:28,272: cli.py(233):    FFF Version:4.59.1
FFF: DEBUG: 2026-07-06 09:03:28,275: configurable.py(565): config site:sofurry.com
FFF: DEBUG: 2026-07-06 09:03:28,304: configurable.py(1055): use_browser_cache:
FFF: DEBUG: 2026-07-06 09:03:28,304: configurable.py(1076): use_basic_cache:False
FFF: INFO: 2026-07-06 09:03:28,321: adapter_sofurrycom.py(97): url: https://sofurry.com/s/ek5K2rWn
FFF: DEBUG: 2026-07-06 09:03:28,324: fetcher_requests.py(114):
---------- REQ (GET) RequestsFetcher
https://sofurry.com/s/ek5K2rWn
FFF: DEBUG: 2026-07-06 09:03:28,978: fetcher_requests.py(127): response code:200
FFF: DEBUG: 2026-07-06 09:03:28,981: decorators.py(118): fromcache:False
FFF: DEBUG: 2026-07-06 09:03:28,989: requestable.py(55): Encoding:utf8
Traceback (most recent call last):
  File "C:\Users\myuser\Desktop\nook\FanFicFare\fanficfare\cli.py", line 710, in <module>
    main()
  File "C:\Users\myuser\Desktop\nook\FanFicFare\fanficfare\cli.py", line 347, in main
    dispatch(options, urls, passed_defaultsini, passed_personalini, warn, fail)
  File "C:\Users\myuser\Desktop\nook\FanFicFare\fanficfare\cli.py", line 323, in dispatch
    do_download(url,
  File "C:\Users\myuser\Desktop\nook\FanFicFare\fanficfare\fff_profile.py", line 43, in profiled_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myuser\Desktop\nook\FanFicFare\fanficfare\cli.py", line 444, in do_download
    adapter.getStoryMetadataOnly()
  File "C:\Users\myuser\Desktop\nook\FanFicFare\fanficfare\adapters\base_adapter.py", line 378, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "C:\Users\myuser\Desktop\nook\FanFicFare\fanficfare\adapters\adapter_sofurrycom.py", line 109, in doExtractChapterUrlsAndMetadata
    self.story.setMetadata('author', stripHTML(soup.select_one('h3.username')))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myuser\Desktop\nook\FanFicFare\fanficfare\htmlcleanup.py", line 77, in stripHTML
    retval = soup.get_text(strip=True)
             ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_text'
```

**Comment by dbhmw** [comment]
This was a total site overhaul, the text is being fetched with javascript so this will take longer to fix. I have downloading working for single stories. Folders are still not working.

**Comment by JimmXinu** [comment]
Hopefully addressed in #1384
