### ISSUE TITLE
Fiction.live "can only concatenate str (not "bool") to str"

### ISSUE THREAD

**Issue by akunohomu** [JimmXinu/FanFicFare#604]
Story: https://fiction.live/stories/How-To-Be-A-Vampire/FQzwiQAFdWK6u2Ztc

Calibre 5.6, FanFicFare test plugin 3.25.14.

```
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.jobs", line 248, in do_download_for_worker
  File "calibre_plugins.fanficfare_plugin.fanficfare.writers.base_writer", line 201, in writeStory
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 237, in getStory
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 389, in getChapterTextNum
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_fictionlive", line 294, in getChapterText
  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_fictionlive", line 507, in format_readerposts
TypeError: can only concatenate str (not "bool") to str
```

**Comment by JimmXinu** [comment]
@HazelSh, can you take a look at this?
