### ISSUE TITLE
error webnovel

### ISSUE THREAD

**Issue by tom221-e** [JimmXinu/FanFicFare#644]
Hello I get the error:
HTTP Error 404: Not Found
Could someone repair it?

FFF: DEBUG: 2021-01-27 19:54:54,726: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_webnovelcom(227): Getting chapter text from: https://www.webnovel.com/book/i-was-a-summoner-in-another-world_19067176406281505/51457533780491484

FFF: DEBUG: 2021-01-27 19:54:54,727: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1209): #####################################

pagecache(GET) MISS: https://www.webnovel.com/apiajax/chapter/GetContent?_csrfToken=cyUFXvoPEK2DBti3cAzHpXFsQb8ayM842v3puLYc&bookId=19067176406281505&chapterId=51457533780491484&_=1611788094727

FFF: DEBUG: 2021-01-27 19:54:55,011: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1321): Caught an exception reading URL: https://www.webnovel.com/apiajax/chapter/GetContent?_csrfToken=cyUFXvoPEK2DBti3cAzHpXFsQb8ayM842v3puLYc&bookId=19067176406281505&chapterId=51457533780491484&_=1611788094727  Exception HTTP Error 404: Not Found.

FFF: DEBUG: 2021-01-27 19:54:55,011: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1340): Giving up on https://www.webnovel.com/apiajax/chapter/GetContent?_csrfToken=cyUFXvoPEK2DBti3cAzHpXFsQb8ayM842v3puLYc&bookId=19067176406281505&chapterId=51457533780491484&_=1611788094727

FFF: DEBUG: 2021-01-27 19:54:55,011: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1341): HTTP Error 404: Not Found

NoneType: None

FFF: INFO: 2021-01-27 19:54:55,012: calibre_plugins.fanficfare_plugin.jobs(364): Exception: {'title': 'I WAS A SUMMONER IN ANOTHER WORLD', 'author_sort': ['BRUH_ITS_FANFIC'], 'author': ['BRUH_ITS_FANFIC'], 'comments': '<p class="c_000">[Ding!]<br/>[You have awakened the great summoning system!]<br/>[Do you want to bind it with your soul!]<br/>\'\'Eh?\'\'<br/>\'\'Wait!\'\'<br/>\'\'Where am I!\'\'<br/><br/>First World: Douluo Dalu 1<br/>Ps: I don\'t own any character or world in this story except my original creation!!</p>', 'good': False, 'status': 'Error', 'showerror': True, 'calibre_id': 2553, 'begin': None, 'end': None, 'comment': 'HTTP Error 404: Not Found', 'url': 'https://www.webnovel.com/book/i-was-a-summoner-in-another-world_19067176406281505', 'site': 'www.webnovel.com', 'series': '', 'added': False, 'pubdate': None, 'publisher': 'www.webnovel.com', 'listorder': 6, 'collision': 'Actualizar EPUB si hay nuevos capítulos', 'uniqueurl': 'https://www.webnovel.com/book/i-was-a-summoner-in-another-world_19067176406281505[None-None]', 'is_adult': False, 'username': 'NoneGiven', 'password': '', 'icon': 'dialog_error.png', 'epub_for_update': 'C:\\Users\\TomasE\\AppData\\Local\\Temp\\calibre_759xpwie\\fanficfare_ic77qxei\\old-2553-heces_wz.epub', 'calibre_columns': {}, 'outfile': 'C:\\Users\\TomasE\\AppData\\Local\\Temp\\calibre_759xpwie\\fanficfare_ic77qxei\\bgmeta-l2a8gs1_.epub', 'tags': ['In-Progress', 'FanFiction'], 'updatedate': datetime.datetime(2021, 1, 27, 17, 54, 50, 866514, tzinfo=SafeLocalTimeZone()), 'timestamp': datetime.datetime(2021, 1, 27, 19, 54, 49, 174039, tzinfo=SafeLocalTimeZone())}:HTTP Error 404: Not Found

Traceback (most recent call last):

  File "calibre_plugins.fanficfare_plugin.jobs", line 307, in do_download_for_worker

  File "calibre_plugins.fanficfare_plugin.fanficfare.writers.base_writer", line 201, in writeStory

  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 237, in getStory

  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.base_adapter", line 402, in getChapterTextNum

  File "calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_webnovelcom", line 233, in getChapterText

  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1448, in _fetchUrl

  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1437, in _fetchUrlOpened

  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1342, in _fetchUrlOpened

  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1312, in _fetchUrlOpened

  File "calibre_plugins.fanficfare_plugin.fanficfare.configurable", line 1263, in _fetchUrlRawOpened

  File "urllib\request.py", line 531, in open

  File "urllib\request.py", line 640, in http_response

  File "urllib\request.py", line 569, in error

  File "urllib\request.py", line 502, in _call_chain

  File "urllib\request.py", line 649, in http_error_default

urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by Chibba-dev** [comment]
some for me, the new test version also didn't help

**Comment by tom221-e** [comment]
Hello, could someone repair this error?

**Comment by Anangaya** [comment]
I ran in to the same issue with webnovel. Hope someone fixes it.

**Comment by tom221-e** [comment]
Hello I wanted to inform that apparently someone has already solved the problem of the api in another project but I do not know how to import it to this one! Could someone do it, the project is:
https://github.com/mHaisham/webnovelbot
