### ISSUE TITLE
FFF broken (ModuleNotFoundError)

### ISSUE THREAD

**Issue by Edocsil** [JimmXinu/FanFicFare#649]
I just updated to the latest test version and got this error after trying to download a story. Even just typing `fanficfare` gives this error.

```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/fanficfare/cli.py", line 47, in <module>
    from calibre_plugins.fanficfare_plugin.fanficfare import adapters, writers, exceptions
ModuleNotFoundError: No module named 'calibre_plugins'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/fanficfare", line 5, in <module>
    from fanficfare.cli import main
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/fanficfare/cli.py", line 55, in <module>
    from fanficfare import adapters, writers, exceptions
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/fanficfare/adapters/__init__.py", line 29, in <module>
    from .. import configurable as configurable
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/fanficfare/configurable.py", line 46, in <module>
    from .browsercache import BrowserCache
ModuleNotFoundError: No module named 'fanficfare.browsercache'
```

For now i have to downgrade as it doesn't work at all.

Edit: This is the last version working fine for me. `pip install -i https://test.pypi.org/simple/ FanFicFare==3.29.6`, the one showing as `FanFicFare 3.99.8 ` doesn't.

**Comment by JimmXinu** [comment]
My bad--I forgot that new packages (AKA directories) need to be added to `setup.py` to be included in the pip distro.

It's updated now on test.pypi.org.  Sorry about that.
