### ISSUE TITLE
NameError: name 're' is not defined

### ISSUE THREAD

**Issue by wombley** [JimmXinu/FanFicFare#662]
On a macbook:

$ fanficfare -f html https://forums.spacebattles.com/threads/training-trip-can-you-really-go-home-again-having-seen-the-world.912768/reader/
............Traceback (most recent call last):
  File "/usr/local/bin/fanficfare", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/fanficfare/cli.py", line 300, in main
    passed_personalini)
  File "/usr/local/lib/python3.7/site-packages/fanficfare/cli.py", line 463, in do_download
    metaonly=options.metaonly, nooutput=options.nooutput)
  File "/usr/local/lib/python3.7/site-packages/fanficfare/cli.py", line 71, in write_story
    writer.writeStory(outstream=outstream, metaonly=metaonly)
  File "/usr/local/lib/python3.7/site-packages/fanficfare/writers/base_writer.py", line 226, in writeStory
    self.writeStoryImpl(outstream)
  File "/usr/local/lib/python3.7/site-packages/fanficfare/writers/writer_html.py", line 161, in writeStoryImpl
    chap_data = re.sub(r"</?(html|head|body)[^>]*>\r?\n?","",chap_data)
NameError: name 're' is not `defined`

$ pip3 install --upgrade fanficfare
Requirement already up-to-date: fanficfare in /usr/local/lib/python3.7/site-packages (4.0.2)
Requirement already satisfied, skipping upgrade: html5lib in /usr/local/lib/python3.7/site-packages (from fanficfare) (1.0.1)
Requirement already satisfied, skipping upgrade: html2text in /usr/local/lib/python3.7/site-packages (from fanficfare) (2020.1.16)
Requirement already satisfied, skipping upgrade: cloudscraper in /usr/local/lib/python3.7/site-packages (from fanficfare) (1.2.50)
Requirement already satisfied, skipping upgrade: chardet in /usr/local/lib/python3.7/site-packages (from fanficfare) (3.0.4)
Requirement already satisfied, skipping upgrade: requests>=2.25.1 in /usr/local/lib/python3.7/site-packages (from fanficfare) (2.25.1)
Requirement already satisfied, skipping upgrade: requests-file in /usr/local/lib/python3.7/site-packages (from fanficfare) (1.5.1)
Requirement already satisfied, skipping upgrade: brotli in /usr/local/lib/python3.7/site-packages (from fanficfare) (1.0.9)
Requirement already satisfied, skipping upgrade: beautifulsoup4 in /usr/local/lib/python3.7/site-packages (from fanficfare) (4.9.1)
Requirement already satisfied, skipping upgrade: urllib3>=1.26.2 in /usr/local/lib/python3.7/site-packages (from fanficfare) (1.26.2)
Requirement already satisfied, skipping upgrade: six>=1.9 in /usr/local/lib/python3.7/site-packages (from html5lib->fanficfare) (1.15.0)
Requirement already satisfied, skipping upgrade: webencodings in /usr/local/lib/python3.7/site-packages (from html5lib->fanficfare) (0.5.1)
Requirement already satisfied, skipping upgrade: pyparsing>=2.4.7 in /usr/local/lib/python3.7/site-packages (from cloudscraper->fanficfare) (2.4.7)
Requirement already satisfied, skipping upgrade: requests-toolbelt>=0.9.1 in /usr/local/lib/python3.7/site-packages (from cloudscraper->fanficfare) (0.9.1)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests>=2.25.1->fanficfare) (2020.12.5)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests>=2.25.1->fanficfare) (2.10)
Requirement already satisfied, skipping upgrade: soupsieve>1.2 in /usr/local/lib/python3.7/site-packages (from beautifulsoup4->fanficfare) (2.0.1)

**Comment by JimmXinu** [comment]
b9f8d4e3142b2ba1b39e8d7cfa36d8d4d23eabe3

Test versions posted in the usual places:

http://www.mobileread.com/forums/showthread.php?p=3084025#post3084025

Test version of CLI for pip install:  You'll have to get it from the
testpypi repository.  This works for me on Debian:

> `pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare`
