### ISSUE TITLE
Failure to download a story from the browser cache ... struct.error: unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by mcepl** [JimmXinu/FanFicFare#706]
After downloading https://www.fanfiction.net/s/12744735/1/The-Last-Peverell with WebToEpub I tried to download it again from cache with FanFicFare and the result was not good (using 4.3.0 with Python 3.8, Firefox 88.0.1).

```
tmp@stitny$ fanficfare -o use_browser_cache=true -o use_browser_cache_only=true https://www.fanfiction.net/s/12744735/1/The-Last-Peverell
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/fanficfare/browsercache/basebrowsercache.py", line 179, in get_key_mapping
    self.do_map_cache_keys()
  File "/usr/lib/python3.8/site-packages/fanficfare/browsercache/basebrowsercache.py", line 51, in profiled_func
    result = func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/fanficfare/browsercache/basebrowsercache.py", line 120, in do_map_cache_keys
    self.map_cache_keys()
  File "/usr/lib/python3.8/site-packages/fanficfare/browsercache/firefoxcache2.py", line 82, in map_cache_keys
    self.do_cache_key_entry(entry.path,entry.stat())
  File "/usr/lib/python3.8/site-packages/fanficfare/browsercache/firefoxcache2.py", line 92, in do_cache_key_entry
    (cache_url,created) = _get_entry_file_created(path)
  File "/usr/lib/python3.8/site-packages/fanficfare/browsercache/firefoxcache2.py", line 140, in _get_entry_file_created
    metadata = _read_entry_headers(entry_file)
  File "/usr/lib/python3.8/site-packages/fanficfare/browsercache/firefoxcache2.py", line 167, in _read_entry_headers
    version = struct.unpack('>I', entry_file.read(4))[0]
struct.error: unpack requires a buffer of 4 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/fanficfare", line 11, in <module>
    load_entry_point('FanFicFare==4.3.0', 'console_scripts', 'fanficfare')()
  File "/usr/lib/python3.8/site-packages/fanficfare/cli.py", line 310, in main
    do_download(url,
  File "/usr/lib/python3.8/site-packages/fanficfare/cli.py", line 410, in do_download
    adapter.getStoryMetadataOnly()
  File "/usr/lib/python3.8/site-packages/fanficfare/adapters/base_adapter.py", line 308, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "/usr/lib/python3.8/site-packages/fanficfare/adapters/adapter_fanfictionnet.py", line 114, in doExtractChapterUrlsAndMetadata
    data = self.get_request(url)
  File "/usr/lib/python3.8/site-packages/fanficfare/requestable.py", line 114, in get_request
    return self.get_request_redirected(url,
  File "/usr/lib/python3.8/site-packages/fanficfare/requestable.py", line 106, in get_request_redirected
    (data,rurl) = self.configuration.get_fetcher().get_request_redirected(
  File "/usr/lib/python3.8/site-packages/fanficfare/fetcher.py", line 390, in get_request_redirected
    fetchresp = self.do_request('GET',
  File "/usr/lib/python3.8/site-packages/fanficfare/fetcher.py", line 102, in fetcher_do_request
    fetchresp = chainfn(
  File "/usr/lib/python3.8/site-packages/fanficfare/fetcher.py", line 240, in fetcher_do_request
    fetchresp = chainfn(
  File "/usr/lib/python3.8/site-packages/fanficfare/fetcher.py", line 272, in fetcher_do_request
    d = self.cache.get_data(url)
  File "/usr/lib/python3.8/site-packages/fanficfare/browsercache/__init__.py", line 29, in get_data
    d = self.browser_cache.get_data(url)
  File "/usr/lib/python3.8/site-packages/fanficfare/browsercache/basebrowsercache.py", line 187, in get_data
    key = self.get_key_mapping(self.minimal_url(url))
  File "/usr/lib/python3.8/site-packages/fanficfare/browsercache/basebrowsercache.py", line 182, in get_key_mapping
    raise BrowserCacheException("Browser Cache Failed to Load with error '%s'"%e)
fanficfare.browsercache.basebrowsercache.BrowserCacheException: Browser Cache Failed to Load with error 'unpack requires a buffer of 4 bytes'
tmp@stitny$
```

**Comment by mcepl** [comment]
Hmm, somehow, it works now.

**Comment by mcepl** [comment]
And then it shows up again:
```
tmp@stitny$ ff_cache https://www.fanfiction.net/s/12531290/2/Birds-become-Dragons
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/fanficfare/browsercache/basebrowsercache.py", line 179, in get_key_mapping
    self.do_map_cache_keys()
  File "/usr/lib/python3.8/site-packages/fanficfare/browsercache/basebrowsercache.py", line 51, in profiled_func
    result = func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/fanficfare/browsercache/basebrowsercache.py", line 120, in do_map_cache_keys
    self.map_cache_keys()
  File "/usr/lib/python3.8/site-packages/fanficfare/browsercache/firefoxcache2.py", line 82, in map_cache_keys
    self.do_cache_key_entry(entry.path,entry.stat())
  File "/usr/lib/python3.8/site-packages/fanficfare/browsercache/firefoxcache2.py", line 92, in do_cache_key_entry
    (cache_url,created) = _get_entry_file_created(path)
  File "/usr/lib/python3.8/site-packages/fanficfare/browsercache/firefoxcache2.py", line 140, in _get_entry_file_created
    metadata = _read_entry_headers(entry_file)
  File "/usr/lib/python3.8/site-packages/fanficfare/browsercache/firefoxcache2.py", line 167, in _read_entry_headers
    version = struct.unpack('>I', entry_file.read(4))[0]
struct.error: unpack requires a buffer of 4 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/fanficfare", line 11, in <module>
    load_entry_point('FanFicFare==4.3.0', 'console_scripts', 'fanficfare')()
  File "/usr/lib/python3.8/site-packages/fanficfare/cli.py", line 310, in main
    do_download(url,
  File "/usr/lib/python3.8/site-packages/fanficfare/cli.py", line 410, in do_download
    adapter.getStoryMetadataOnly()
  File "/usr/lib/python3.8/site-packages/fanficfare/adapters/base_adapter.py", line 308, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "/usr/lib/python3.8/site-packages/fanficfare/adapters/adapter_fanfictionnet.py", line 114, in doExtractChapterUrlsAndMetadata
    data = self.get_request(url)
  File "/usr/lib/python3.8/site-packages/fanficfare/requestable.py", line 114, in get_request
    return self.get_request_redirected(url,
  File "/usr/lib/python3.8/site-packages/fanficfare/requestable.py", line 106, in get_request_redirected
    (data,rurl) = self.configuration.get_fetcher().get_request_redirected(
  File "/usr/lib/python3.8/site-packages/fanficfare/fetcher.py", line 390, in get_request_redirected
    fetchresp = self.do_request('GET',
  File "/usr/lib/python3.8/site-packages/fanficfare/fetcher.py", line 102, in fetcher_do_request
    fetchresp = chainfn(
  File "/usr/lib/python3.8/site-packages/fanficfare/fetcher.py", line 240, in fetcher_do_request
    fetchresp = chainfn(
  File "/usr/lib/python3.8/site-packages/fanficfare/fetcher.py", line 272, in fetcher_do_request
    d = self.cache.get_data(url)
  File "/usr/lib/python3.8/site-packages/fanficfare/browsercache/__init__.py", line 29, in get_data
    d = self.browser_cache.get_data(url)
  File "/usr/lib/python3.8/site-packages/fanficfare/browsercache/basebrowsercache.py", line 187, in get_data
    key = self.get_key_mapping(self.minimal_url(url))
  File "/usr/lib/python3.8/site-packages/fanficfare/browsercache/basebrowsercache.py", line 182, in get_key_mapping
    raise BrowserCacheException("Browser Cache Failed to Load with error '%s'"%e)
fanficfare.browsercache.basebrowsercache.BrowserCacheException: Browser Cache Failed to Load with error 'unpack requires a buffer of 4 bytes'
tmp@stitny$
```
Probably at least some investigation (Firefox 89) is probably necessary. Sometimes it works, then (without changing a browser or anything else significant) it doesn't.

**Comment by kido5217** [comment]
Downloading from cache only works for me if I specify URL of the first chapter.

**Comment by JimmXinu** [comment]
I've posted a test version to pypitest that may help.

There's a couple things going on.

1) FFF has to read all of the cache entries (with age limit) and look at their URL for these cache types. So it's trying to read all of them, even the non-ffnet ones. (As I recall, the 'chromagnon' cache has an index instead.)

2) It's entirely possible that our cobbled together Python code for reading browser caches is buggy in corner cases.

So the low-hanging-fruit answer is to just skip entries that don't load correctly and hope they aren't the ffnet pages.

An extremely similar error, except for Chrome has been [reported](https://www.mobileread.com/forums/showthread.php?p=4130555#post4130555), too.

If you do see this error again, please run with `--debug` and post the results.  And if you can attach a zip file of the cache file that fails, it may also help.

**Comment by mcepl** [comment]
yes, the last commit from master (872644cb) works just fine.

**Comment by mcepl** [comment]
Hmm, not always fine:
```
tmp@stitny$ ff_cache https://www.fanfiction.net/s/7181871/1/Foolish
FFF: WARNING: 2021-06-18 09:14:16,348: firefoxcache2.py(99): Cache file /home/matej/.cache/mozilla/firefox/uxi2c7cz.default/cache2/entries/9C836B1B56FD22D47F9137D453E185B35A5E74AD failed to load, skipping.
Traceback (most recent call last):
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/browsercache/firefoxcache2.py", line 93, in do_cache_key_entry
    (cache_url,created) = _get_entry_file_created(path)
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/browsercache/firefoxcache2.py", line 144, in _get_entry_file_created
    metadata = _read_entry_headers(entry_file)
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/browsercache/firefoxcache2.py", line 171, in _read_entry_headers
    version = struct.unpack('>I', entry_file.read(4))[0]
struct.error: unpack requires a buffer of 4 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/browsercache/basebrowsercache.py", line 179, in get_key_mapping
    self.do_map_cache_keys()
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/browsercache/basebrowsercache.py", line 51, in profiled_func
    result = func(*args, **kwargs)
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/browsercache/basebrowsercache.py", line 120, in do_map_cache_keys
    self.map_cache_keys()
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/browsercache/firefoxcache2.py", line 82, in map_cache_keys
    self.do_cache_key_entry(entry.path,entry.stat())
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/browsercache/firefoxcache2.py", line 100, in do_cache_key_entry
    logger.debug(traceback.format_exc())
NameError: name 'traceback' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matej/.local/bin/fanficfare", line 11, in <module>
    load_entry_point('FanFicFare', 'console_scripts', 'fanficfare')()
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/cli.py", line 310, in main
    do_download(url,
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/cli.py", line 410, in do_download
    adapter.getStoryMetadataOnly()
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/adapters/base_adapter.py", line 308, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/adapters/adapter_fanfictionnet.py", line 114, in doExtractChapterUrlsAndMetadata
    data = self.get_request(url)
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/requestable.py", line 114, in get_request
    return self.get_request_redirected(url,
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/requestable.py", line 106, in get_request_redirected
    (data,rurl) = self.configuration.get_fetcher().get_request_redirected(
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/fetcher.py", line 390, in get_request_redirected
    fetchresp = self.do_request('GET',
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/fetcher.py", line 102, in fetcher_do_request
    fetchresp = chainfn(
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/fetcher.py", line 240, in fetcher_do_request
    fetchresp = chainfn(
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/fetcher.py", line 272, in fetcher_do_request
    d = self.cache.get_data(url)
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/browsercache/__init__.py", line 29, in get_data
    d = self.browser_cache.get_data(url)
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/browsercache/basebrowsercache.py", line 187, in get_data
    key = self.get_key_mapping(self.minimal_url(url))
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/browsercache/basebrowsercache.py", line 182, in get_key_mapping
    raise BrowserCacheException("Browser Cache Failed to Load with error '%s'"%e)
fanficfare.browsercache.basebrowsercache.BrowserCacheException: Browser Cache Failed to Load with error 'name 'traceback' is not defined'
tmp@stitny$ fanf
fanficfare      fanficfare-3.8
tmp@stitny$ fanficfare --version
Version: 4.3.4
tmp@stitny$
```

**Comment by mcepl** [comment]
Hmm, 4.3.5 (or `master` of the git repo) seems better:
```
tmp@stitny$ fanficfare --version
Version: 4.3.5
tmp@stitny$ ff_cache https://www.fanfiction.net/s/7181871/1/Foolish
FFF: WARNING: 2021-06-18 09:16:27,595: firefoxcache2.py(100): Cache file /home/matej/.cache/mozilla/firefox/uxi2c7cz.default/cache2/entries/9C836B1B56FD22D47F9137D453E185B35A5E74AD failed to load, skipping.
.FFF: WARNING: 2021-06-18 09:16:27,769: adapter_fanfictionnet.py(343): Caught exception in skip_author_cover: HTTP Error in FFF 'Page not found or expired in Browser Cache (see FFF setting browser_cache_age_limit)'(428) URL:'https://www.fanfiction.net/u/2742999/Tonksaholic'.
.........................tmp@stitny$
```

**Comment by JimmXinu** [comment]
Yeah, not being able to see those errors myself to test, I made a basic mistake and forgot the import `traceback` at first.

**Comment by mcepl** [comment]
It seems like fixed now, thank you!
