### ISSUE TITLE
[bug] Error downloading specific SufficientVelocity story

### ISSUE THREAD

**Issue by dakswiggin** [JimmXinu/FanFicFare#713]
Using 4.3.9 version FanficFare, CLI
Trying to download https://forums.sufficientvelocity.com/threads/nuka-girl-the-lone-teleporter-or-that-time-taylor-found-herself-in-the-fallout-universe.53339

Getting following trace:
`Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/fanficfare", line 33, in <module>
    sys.exit(load_entry_point('FanFicFare==4.3.9', 'console_scripts', 'fanficfare')())
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/fanficfare/cli.py", line 310, in main
    do_download(url,
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/fanficfare/cli.py", line 468, in do_download
    output_filename = write_story(configuration, adapter, 'epub',
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/fanficfare/cli.py", line 62, in write_story
    writer.writeStory(outstream=outstream, metaonly=metaonly)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/fanficfare/writers/base_writer.py", line 204, in writeStory
    self.story = self.adapter.getStory(notification)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/fanficfare/adapters/base_adapter.py", line 240, in getStory
    data = self.getChapterTextNum(url,index)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/fanficfare/adapters/base_xenforoforum_adapter.py", line 695, in getChapterTextNum
    topsoup = self.make_soup(self.get_request(reader_url))
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/fanficfare/adapters/base_xenforoforum_adapter.py", line 232, in make_soup
    img['src'] = img['data-src']
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/bs4/element.py", line 1406, in __getitem__
    return self.attrs[key]
KeyError: 'data-src'`

Presumably  happens due to following chapter: https://forums.sufficientvelocity.com/threads/nuka-girl-the-lone-teleporter-or-that-time-taylor-found-herself-in-the-fallout-universe.53339/page-38#post-20608393

**Comment by dakswiggin** [comment]
Same error for https://forums.sufficientvelocity.com/threads/hereafter-worm-x-fate-grand-order.90656/threadmarks however for this fic there are no images in latest updates.

**Comment by Chirishman** [comment]
Hey please reopen this issue, I'm also seeing the data-src error and **a complete failure to retrieve new chapters** on a bunch of SV fics which I know to have more chapters than are in my local copy.

I've been seeing this error only since 7/10

I've identified 19 separate stories for which this error is occurring when checking for new chapters, but here are the three that have updated most recently:

https://forums.sufficientvelocity.com/threads/hatching-a-heist-worm-story-version.89760/
https://forums.sufficientvelocity.com/threads/kind-steel-foz-si.90353/
https://forums.sufficientvelocity.com/threads/bootstrapping-multi-cross-book-1-highschool-dxd.87200/

For these stories my local copies show the chapter/threadmark counts at 63, 8, and 10 respectively and when I run the check for updates I get a return of 0 new chapters found and "data-src" as the only error return.

If they were properly updating I would expect to see 67, 10, and 92 chapters on these three fics.

**Comment by dakswiggin** [comment]
Dear @Chirishman 
Seems you're using 4.3.0 version of FFF from 2021-05l30.
Bug was fixed in test version from 2021-07-10, I'd advise to try it.

**Comment by JimmXinu** [comment]
Already fixed.  New version will be released shortly since it's actually a bit over due.
