### ISSUE TITLE
Failure in Sufficient Velocity when downloading stories that have multiple categories

### ISSUE THREAD

**Issue by drossqfd** [JimmXinu/FanFicFare#717]
I am getting the following trace when trying to download stories from Sufficient Velocity that have a media tab. I have tried 4.4 and the latest beta.

```
FFF: DEBUG: 2021-07-18 06:20:58,572: fetcher.py(441): 
---------- REQ (GET) RequestsFetcher
https://forums.sufficientvelocity.com/threads/scaling-up-au-alt-power-op-taylor-dragons-d-d-mangled-mythology.57243/reader/page-1?threadmark_category=3
FFF: DEBUG: 2021-07-18 06:20:58,843: fetcher.py(447): response code:200
FFF: DEBUG: 2021-07-18 06:20:58,843: fetcher.py(156): random sleep(0.05-0.15):0.14
FFF: DEBUG: 2021-07-18 06:20:58,993: requestable.py(50): Encoding:utf8
Traceback (most recent call last):
  File "/usr/local/bin/fanficfare", line 33, in <module>
    sys.exit(load_entry_point('FanFicFare==4.4.1', 'console_scripts', 'fanficfare')())
  File "/usr/local/lib/python3.9/site-packages/fanficfare/cli.py", line 310, in main
    do_download(url,
  File "/usr/local/lib/python3.9/site-packages/fanficfare/cli.py", line 468, in do_download
    output_filename = write_story(configuration, adapter, 'epub',
  File "/usr/local/lib/python3.9/site-packages/fanficfare/cli.py", line 62, in write_story
    writer.writeStory(outstream=outstream, metaonly=metaonly)
  File "/usr/local/lib/python3.9/site-packages/fanficfare/writers/base_writer.py", line 204, in writeStory
    self.story = self.adapter.getStory(notification)
  File "/usr/local/lib/python3.9/site-packages/fanficfare/adapters/base_adapter.py", line 240, in getStory
    data = self.getChapterTextNum(url,index)
  File "/usr/local/lib/python3.9/site-packages/fanficfare/adapters/base_xenforoforum_adapter.py", line 684, in getChapterTextNum
    topsoup = self.make_soup(self.get_request(reader_url))
  File "/usr/local/lib/python3.9/site-packages/fanficfare/adapters/base_xenforoforum_adapter.py", line 232, in make_soup
    img['src'] = img['data-src']
  File "/usr/local/lib/python3.9/site-packages/bs4/element.py", line 1406, in __getitem__
    return self.attrs[key]
KeyError: 'data-src'
```

**Comment by JimmXinu** [comment]
Are you _sure_ you're using the latest version?  

Because that exact error was already reported and fixed in #713.  And I follow and download that story myself.  And successfully just downloaded it all again.  And the issue has to do with images, not multiple categories.

**Comment by drossqfd** [comment]
Since 4.4.0 isn't showing up on pip, I tried to install from source. I got the entrypoint script to update, but the actual code did not.

I ran `./setup.py install` and it did not throw any errors.

I probably should have just made an issue that the latest version wasn't on pip and then tried via the known working way to update.

**Comment by Edocsil** [comment]
`pip install -i https://test.pypi.org/simple/ FanFicFare`

I'm also subscribed to that story and it updates without any issue.

**Comment by JimmXinu** [comment]
I apparently uploaded 4.4.0 to testpypi, not pypi.  I've now uploaded 4.4.1 to pypi.
