### ISSUE TITLE
fictionmania.tv blocking access

### ISSUE THREAD

**Issue by JimmXinu** [JimmXinu/FanFicFare#718]
```
Traceback (most recent call last):
  File "C:\Users\jimm\Desktop\nook\FanFicFare\fanficfare\cli.py", line 650, in <module>
    main()
  File "C:\Users\jimm\Desktop\nook\FanFicFare\fanficfare\cli.py", line 310, in main
    do_download(url,
  File "C:\Users\jimm\Desktop\nook\FanFicFare\fanficfare\cli.py", line 410, in do_download
    adapter.getStoryMetadataOnly()
  File "C:\Users\jimm\Desktop\nook\FanFicFare\fanficfare\adapters\base_adapter.py", line 308, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "C:\Users\jimm\Desktop\nook\FanFicFare\fanficfare\adapters\base_adapter.py", line 412, in doExtractChapterUrlsAndMetadata
    return self.extractChapterUrlsAndMetadata()
  File "C:\Users\jimm\Desktop\nook\FanFicFare\fanficfare\adapters\adapter_fictionmaniatv.py", line 60, in extractChapterUrlsAndMetadata
    soup = self.make_soup(self.get_request(url))
  File "C:\Users\jimm\Desktop\nook\FanFicFare\fanficfare\requestable.py", line 114, in get_request
    return self.get_request_redirected(url,
  File "C:\Users\jimm\Desktop\nook\FanFicFare\fanficfare\requestable.py", line 106, in get_request_redirected
    (data,rurl) = self.configuration.get_fetcher().get_request_redirected(
  File "C:\Users\jimm\Desktop\nook\FanFicFare\fanficfare\fetcher.py", line 390, in get_request_redirected
    fetchresp = self.do_request('GET',
  File "C:\Users\jimm\Desktop\nook\FanFicFare\fanficfare\fetcher.py", line 240, in fetcher_do_request
    fetchresp = chainfn(
  File "C:\Users\jimm\Desktop\nook\FanFicFare\fanficfare\fetcher.py", line 136, in fetcher_do_request
    fetchresp = chainfn(
  File "C:\Users\jimm\Desktop\nook\FanFicFare\fanficfare\fetcher.py", line 363, in do_request
    fetchresp = self.request(method,url,
  File "C:\Users\jimm\Desktop\nook\FanFicFare\fanficfare\fetcher.py", line 531, in request
    return super(CloudScraperFetcher,self).request(method,url,headers,parameters)
  File "C:\Users\jimm\Desktop\nook\FanFicFare\fanficfare\fetcher.py", line 463, in request
    resp = self.get_requests_session().request(method, url,
  File "C:\Users\jimm\AppData\Roaming\Python\Python39\site-packages\cloudscraper\__init__.py", line 263, in request
    self.perform_request(method, url, *args, **kwargs)
  File "C:\Users\jimm\AppData\Roaming\Python\Python39\site-packages\cloudscraper\__init__.py", line 182, in perform_request
    return super(CloudScraper, self).request(method, url, *args, **kwargs)
  File "C:\Users\jimm\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\jimm\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\jimm\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='fictionmania.tv', port=443): Max retries exceeded with url: /stories/details.html?storyID=1626741255624707705 (Caused by ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))
```

Turning on `use_cloudscraper:true` doesn't appear to help.

I'm opening this issue to record it; I don't have the energy right now to attempt to work around another site that is blocking us.

**Comment by mcepl** [comment]
This doesn't look like the equivalent of https://github.com/JimmXinu/FanFicFare/issues/703. More likely you have tried too many downloads. Perhaps increasing value of `slow_down_sleep_time` may help?

**Comment by JimmXinu** [comment]
Changing the adapter to use http instead of https seems to have cleared it. 89c6d45786cbe34156fd93b169f39e99d925e615
