### ISSUE TITLE
SB not working now?

### ISSUE THREAD

**Issue by DragoLord19D** [JimmXinu/FanFicFare#749]
Is it going the way of FF.net? I'm getting a 404 error when I try...

**Comment by JimmXinu** [comment]
Works fine for me.  Story URL and debug log?

**Comment by JimmXinu** [comment]
That story downloads fine for me.  

It is possible you are being blocked if you've been downloading a lot, but I haven't heard anything from anyone else.  We do know that SB uses CF, but the ffnet CF blocking presents itself very evidently as CF.

It's also possible the site is having problems on some servers that you are hitting and I am not due to location, time or just chance.

A debug log might tell me more.  Without it, I have no further help to offer.

FYI, 404 != 503.  There are real differences between different HTTP status codes.

**Comment by DragoLord19D** [comment]
My apologies about the wrong code, heres the debug

EpubMerge: DEBUG: 2021-10-20 19:38:22,966: calibre_plugins.epubmerge.epubmerge_plugin(158): macmenuhack file_path:C:\Users\Dragolord19d\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
FFF: DEBUG: 2021-10-20 19:38:23,059: calibre_plugins.fanficfare_plugin.fff_plugin(221): Plugin FanFicFare macmenuhack file_path:C:\Users\Dragolord19d\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
calibre Debug log
calibre 5.29 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 44, 0) && Package KFX (from KFX Input) (1, 44, 0) && EpubMerge (2, 11, 0) && FanFicFare (4, 6, 0) && KFX metadata reader (from KFX Input) (1, 44, 0) && KFX Input (1, 44, 0) && Set KFX metadata (from KFX Output) (1, 56, 0) && KFX Output (1, 56, 0)
calibre 5.29 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 44, 0) && Package KFX (from KFX Input) (1, 44, 0) && EpubMerge (2, 11, 0) && FanFicFare (4, 6, 0) && KFX metadata reader (from KFX Input) (1, 44, 0) && KFX Input (1, 44, 0) && Set KFX metadata (from KFX Output) (1, 56, 0) && KFX Output (1, 56, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.7674418604651 x 141.4020618556701
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.69] splash screen shown
[0.69] Initializing db...
[0.91] db initialized
[0.91] Constructing main UI...
[5.69] main UI initialized...
[5.69] Hiding splash screen
Starting QuickView
FFF: DEBUG: 2021-10-20 19:38:36,839: calibre_plugins.fanficfare_plugin.dialogs(504): self.extraoptions['anthology_url']:NOT FOUND
FFF: DEBUG: 2021-10-20 19:38:36,844: calibre_plugins.fanficfare_plugin.fff_plugin(1116): FanFicFare v4.6.0
FFF: DEBUG: 2021-10-20 19:38:36,916: configurable.py(1023): use_browser_cache:
FFF: DEBUG: 2021-10-20 19:38:36,917: configurable.py(1037): use_basic_cache:true
FFF: INFO: 2021-10-20 19:38:36,918: base_xenforoforum_adapter.py(451): url: https://forums.sufficientvelocity.com/threads/but-i-dont-speak-german-an-isot.40582/
FFF: DEBUG: 2021-10-20 19:38:36,919: fetcher.py(234): 
========== MISS (GET) BasicCache
https://forums.sufficientvelocity.com/threads/but-i-dont-speak-german-an-isot.40582/
FFF: DEBUG: 2021-10-20 19:38:36,919: fetcher.py(462): 
---------- REQ (GET) RequestsFetcher
https://forums.sufficientvelocity.com/threads/but-i-dont-speak-german-an-isot.40582/
FFF: DEBUG: 2021-10-20 19:39:05,994: fetcher.py(469): response code:503
FFF: ERROR: 2021-10-20 19:39:05,995: calibre_plugins.fanficfare_plugin.dialogs(721): Exception: {'title': 'Unknown', 'author_sort': ['Unknown'], 'author': ['Unknown'], 'comments': '', 'good': False, 'status': 'Error', 'showerror': True, 'calibre_id': None, 'begin': None, 'end': None, 'comment': "HTTP Error in FFF '503 Server Error: Service Temporarily Unavailable for url: https://forums.sufficientvelocity.com/threads/but-i-dont-speak-german-an-isot.40582/'(503)", 'url': 'https://forums.sufficientvelocity.com/threads/but-i-dont-speak-german-an-isot.40582/', 'site': 'forums.sufficientvelocity.com', 'series': '', 'added': False, 'pubdate': None, 'publisher': None, 'uniqueurl': 'https://forums.sufficientvelocity.com/threads/but-i-dont-speak-german-an-isot.40582/[None-None]', 'listorder': 0, 'collision': 'Update EPUB if New Chapters'}:HTTP Error in FFF '503 Server Error: Service Temporarily Unavailable for url: https://forums.sufficientvelocity.com/threads/but-i-dont-speak-german-an-isot.40582/'(503)
Traceback (most recent call last):
  File "C:\Users\Dragolord19d\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\fetcher.py", line 470, in request
  File "C:\Users\Dragolord19d\AppData\Roaming\calibre\plugins\FanFicFare.zip\requests\models.py", line 943, in raise_for_status
requests.exceptions.HTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://forums.sufficientvelocity.com/threads/but-i-dont-speak-german-an-isot.40582/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.dialogs", line 708, in do_loop
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1330, in prep_download_loop
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1202, in get_story_metadata_only
  File "C:\Users\Dragolord19d\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\adapters\base_adapter.py", line 308, in getStoryMetadataOnly
  File "C:\Users\Dragolord19d\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\adapters\base_adapter.py", line 412, in doExtractChapterUrlsAndMetadata
  File "C:\Users\Dragolord19d\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\adapters\base_xenforoforum_adapter.py", line 454, in extractChapterUrlsAndMetadata
  File "C:\Users\Dragolord19d\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\requestable.py", line 106, in get_request_redirected
  File "C:\Users\Dragolord19d\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\fetcher.py", line 391, in get_request_redirected
  File "C:\Users\Dragolord19d\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\fetcher.py", line 240, in fetcher_do_request
  File "C:\Users\Dragolord19d\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\fetcher.py", line 136, in fetcher_do_request
  File "C:\Users\Dragolord19d\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\fetcher.py", line 364, in do_request
  File "C:\Users\Dragolord19d\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\fetcher.py", line 491, in request
fanficfare.exceptions.HTTPErrorFFF: HTTP Error in FFF '503 Server Error: Service Temporarily Unavailable for url: https://forums.sufficientvelocity.com/threads/but-i-dont-speak-german-an-isot.40582/'(503)

**Comment by JimmXinu** [comment]
In this case, the debug log doesn't tell me anything useful.  It's failing on the first request.  And that story also downloads fine for me.

Assuming you aren't having trouble with those pages in your browser, some kind of blocking does seem more likely.

You could try setting `use_cloudscraper:true` for `[forums.spacebattles.com]`.  I don't know if that would help or not.

You could try using a different network or a VPN or something.  Clearing your DNS cache could conceivably help.

Regardless, I don't think it's a problem with FFF itself.
