### ISSUE TITLE
Error downloading from ScribbleHub

### ISSUE THREAD

**Issue by dakswiggin** [JimmXinu/FanFicFare#778]
Win10, Calibre 5.33.2, Fanficfare 4.8.0

'NoneType' object has no attribute 'decompose' error when downloading (https://www.scribblehub.com/series/214686/weird-shift/)
So far this is only fic with this error from 80+ SH fic i'm regularly checking

<details><summary>Log here</summary>

```
EpubMerge: DEBUG: 2021-12-10 15:09:49,762: calibre_plugins.epubmerge.epubmerge_plugin(158): macmenuhack file_path:D:\Daks\Calibre\Calibre Portable\Calibre Settings\plugins\fanficfare_macmenuhack.txt
FFF: DEBUG: 2021-12-10 15:09:49,770: calibre_plugins.fanficfare_plugin.fff_plugin(221): Plugin FanFicFare macmenuhack file_path:D:\Daks\Calibre\Calibre Portable\Calibre Settings\plugins\fanficfare_macmenuhack.txt
calibre Debug log
calibre 5.33.2 Portable embedded-python: True is64bit: False
Windows-10-10.0.22000 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.22000')
Python 3.8.5
Windows: ('10', '10.0.22000', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Count Pages (1, 11, 1) && EpubMerge (2, 11, 0) && FanFicFare (4, 8, 0) && Generate Cover (2, 0, 2)
calibre 5.33.2 Portable embedded-python: True is64bit: False
Windows-10-10.0.22000 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.22000')
Python 3.8.5
Windows: ('10', '10.0.22000', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Count Pages (1, 11, 1) && EpubMerge (2, 11, 0) && FanFicFare (4, 8, 0) && Generate Cover (2, 0, 2)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 91.84180790960451 x 91.89949748743719
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.44] splash screen shown
[0.44] Initializing db...
[0.88] db initialized
[0.88] Constructing main UI...
[2.94] main UI initialized...
[2.94] Hiding splash screen
Starting QuickView
FFF: DEBUG: 2021-12-10 15:10:19,027: calibre_plugins.fanficfare_plugin.dialogs(504): self.extraoptions['anthology_url']:NOT FOUND
FFF: DEBUG: 2021-12-10 15:10:19,029: calibre_plugins.fanficfare_plugin.fff_plugin(1116): FanFicFare v4.8.0
FFF: DEBUG: 2021-12-10 15:10:19,065: configurable.py(1028): use_browser_cache:
FFF: DEBUG: 2021-12-10 15:10:19,065: configurable.py(1042): use_basic_cache:true
FFF: DEBUG: 2021-12-10 15:10:19,065: adapter_scribblehubcom.py(118): URL: https://www.scribblehub.com/series/214686/weird-shift/
FFF: DEBUG: 2021-12-10 15:10:19,066: fetcher.py(234): 
========== MISS (GET) BasicCache
https://www.scribblehub.com/series/214686/weird-shift/
FFF: DEBUG: 2021-12-10 15:10:19,066: fetcher.py(462): 
...
part of log related to consecutive chapters download removed
...
---------- REQ (GET) RequestsFetcher

https://www.scribblehub.com/read/214686-weird-shift/chapter/387131/

FFF: DEBUG: 2021-12-10 15:11:13,945: fetcher.py(469): response code:200

FFF: DEBUG: 2021-12-10 15:11:13,946: requestable.py(50): Encoding:utf8

FFF: DEBUG: 2021-12-10 15:11:14,125: adapter_scribblehubcom.py(259): Getting chapter text from: https://www.scribblehub.com/read/214686-weird-shift/chapter/387132/

FFF: DEBUG: 2021-12-10 15:11:14,126: fetcher.py(234): 

========== MISS (GET) BasicCache

https://www.scribblehub.com/read/214686-weird-shift/chapter/387132/

FFF: DEBUG: 2021-12-10 15:11:14,126: fetcher.py(462): 

---------- REQ (GET) RequestsFetcher

https://www.scribblehub.com/read/214686-weird-shift/chapter/387132/

FFF: DEBUG: 2021-12-10 15:11:14,709: fetcher.py(469): response code:200

FFF: DEBUG: 2021-12-10 15:11:14,709: requestable.py(50): Encoding:utf8

FFF: INFO: 2021-12-10 15:11:14,890: calibre_plugins.fanficfare_plugin.jobs(439): Exception: {'title': 'Weird Shift', 'author_sort': ['Malonymous'], 'author': ['Malonymous'], 'comments': '<div class="wi_fic_desc"><p>The deal: Beryl the self-proclaimed \'god-tier\' gamer is offered one thousand years of paradise for reincarnating into a fantasy world and slaying the Demon King.<br/>\nThe plan: Pretending to be a girl in online games worked to get him tons of free gold. What could go wrong doing it for real this time?<br/>\nThe catch: Something feels very \'off\' about this world. Why is it starting to seem like everyone here is some kind of weirdo? And even the Demon King, he’s… he’s…!<br/>\n“For the love of God, is there ANYONE in this world who isn’t a pervert?!”</p>\n<p>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~<br/>\nGirls\' Love scenes start in Arc 2!! Foxy begins in Arc 3 ♡ Also futa in Arc 3 ;)<br/>\nDiscord server:<br/>\nhttps://discord.gg/chcZZYbUBU</p>\n</div>', 'good': False, 'status': 'Error', 'showerror': True, 'calibre_id': None, 'begin': None, 'end': None, 'comment': "'NoneType' object has no attribute 'decompose'", 'url': 'https://www.scribblehub.com/series/214686/weird-shift/', 'site': 'www.scribblehub.com', 'series': '', 'added': False, 'pubdate': datetime.datetime(2020, 12, 27, 0, 0, tzinfo=SafeLocalTimeZone()), 'publisher': 'www.scribblehub.com', 'uniqueurl': 'https://www.scribblehub.com/series/214686/weird-shift/[None-None]', 'listorder': 0, 'collision': 'Update EPUB if New Chapters', 'is_adult': False, 'username': 'NoneGiven', 'password': '', 'icon': 'dialog_error.png', 'all_metadata': {'category': "Anti-Magic, Antihero Protagonist, Beautiful Female Lead, Character Growth, Death, Demon Lord, Demons, Fantasy World, Fast Learner, Female Protagonist, Fox Spirits, Futanari, Girl's Love Subplot, Magic, Male to Female, Money Grubber, Narcissistic Protagonist, Nobles, Nudity, Quirky Characters, R-18, Satire, Shameless Protagonist, Sudden Wealth, Weak to Strong", 'genre': 'Action, Adventure, Comedy, Ecchi, Fantasy, Gender Bender, Isekai, Mature, Psychological', 'characters': '', 'ships': '', 'warnings': 'Gore, Sexual Content, Strong Language', 'extratags': 'FanFiction', 'author': 'Malonymous', 'authorId': 'Malonymous', 'authorUrl': 'https://www.scribblehub.com/profile/43280/malonymous/', 'lastupdate': 'Last Update Year/Month: 2021/12, Last Update: 2021/12/04', 'series': '', 'seriesUrl': '', 'language': '', 'status': 'In-Progress', 'datePublished': '2020-12-27', 'dateUpdated': '2021-12-04', 'dateCreated': '2021-12-10 15:10:19', 'rating': 'Mature', 'numChapters': '61', 'numWords': '121,828', 'words_added': '', 'site': 'www.scribblehub.com', 'publisher': 'www.scribblehub.com', 'storyId': '214686', 'title': 'Weird Shift', 'titleHTML': "<a class='titlelink' href='https://www.scribblehub.com/series/214686/weird-shift/'>Weird Shift</a>", 'storyUrl': 'https://www.scribblehub.com/series/214686/weird-shift/', 'sectionUrl': 'https://www.scribblehub.com/series/214686/weird-shift/', 'description': '<div class="wi_fic_desc"><p>The deal: Beryl the self-proclaimed \'god-tier\' gamer is offered one thousand years of paradise for reincarnating into a fantasy world and slaying the Demon King.<br/>\nThe plan: Pretending to be a girl in online games worked to get him tons of free gold. What could go wrong doing it for real this time?<br/>\nThe catch: Something feels very \'off\' about this world. Why is it starting to seem like everyone here is some kind of weirdo? And even the Demon King, he’s… he’s…!<br/>\n“For the love of God, is there ANYONE in this world who isn’t a pervert?!”</p>\n<p>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~<br/>\nGirls\' Love scenes start in Arc 2!! Foxy begins in Arc 3 ♡ Also futa in Arc 3 ;)<br/>\nDiscord server:<br/>\nhttps://discord.gg/chcZZYbUBU</p>\n</div>', 'formatname': '', 'formatext': '', 'siteabbrev': 'scrhub', 'version': 'FanFicFare v4.8.0', 'authorHTML': "<a class='authorlink' href='https://www.scribblehub.com/profile/43280/malonymous/'>Malonymous</a>", 'seriesHTML': '', 'langcode': '', 'output_css': '', 'cover_image': 'specific', 'views': '179,166', 'averageWords': '1,997', 'fandoms': ''}, 'tags': ['Death', 'Gender Bender', 'Character Growth', 'Futanari', 'Sudden Wealth', 'In-Progress', 'Narcissistic Protagonist', 'FanFiction', "Girl's Love Subplot", 'Beautiful Female Lead', 'Action', 'Magic', 'Adventure', 'Shameless Protagonist', 'Quirky Characters', 'Male to Female', 'Demon Lord', 'Anti-Magic', 'Isekai', 'Satire', 'Fantasy World', 'Fast Learner', 'Female Protagonist', 'Demons', 'Ecchi', 'R-18', 'Fantasy', 'Comedy', 'Nudity', 'Mature', 'Antihero Protagonist', 'Psychological', 'Weak to Strong', 'Nobles', 'Fox Spirits', 'Money Grubber'], 'updatedate': datetime.datetime(2021, 12, 4, 0, 0, tzinfo=SafeLocalTimeZone()), 'timestamp': datetime.datetime(2021, 12, 10, 15, 10, 23, 851633, tzinfo=SafeLocalTimeZone()), 'calibre_columns': {}, 'outfile': 'C:\\Users\\Daks\\AppData\\Local\\Temp\\calibre_e8qt_rbx\\fanficfare_zjy6btf5\\Weird Shift-Malonymous-3z1p3n8q.epub'}:'NoneType' object has no attribute 'decompose'

Traceback (most recent call last):

  File "calibre_plugins.fanficfare_plugin.jobs", line 313, in do_download_for_worker

  File "D:\Daks\Calibre\Calibre Portable\Calibre Settings\plugins\FanFicFare.zip\fanficfare\writers\base_writer.py", line 204, in writeStory

  File "D:\Daks\Calibre\Calibre Portable\Calibre Settings\plugins\FanFicFare.zip\fanficfare\adapters\base_adapter.py", line 240, in getStory

  File "D:\Daks\Calibre\Calibre Portable\Calibre Settings\plugins\FanFicFare.zip\fanficfare\adapters\base_adapter.py", line 419, in getChapterTextNum

  File "D:\Daks\Calibre\Calibre Portable\Calibre Settings\plugins\FanFicFare.zip\fanficfare\adapters\adapter_scribblehubcom.py", line 336, in getChapterText

AttributeError: 'NoneType' object has no attribute 'decompose'



FFF: INFO: 2021-12-10 15:11:15,125: calibre_plugins.fanficfare_plugin.jobs(142): 

Download Results:

Error https://www.scribblehub.com/series/214686/weird-shift/ 'NoneType' object has no attribute 'decompose'



FFF: INFO: 2021-12-10 15:11:15,126: calibre_plugins.fanficfare_plugin.jobs(166): 

Error

https://www.scribblehub.com/series/214686/weird-shift/

	

```

</details>

**Comment by JimmXinu** [comment]
Test version posted in [the usual place](https://www.mobileread.com/forums/showthread.php?p=3084025&postcount=2).
