### ISSUE TITLE
fictionhunt doesn't need login always

### ISSUE THREAD

**Issue by mcepl** [JimmXinu/FanFicFare#784]
When trying to download https://fictionhunt.com/stories/p7wnx17/twentyone-days stock fanficfare ends up like this:
```
FanFicFare@stitny (main)$ fanficfare --debug https://fictionhunt.com/stories/p7wnx17/twentyone-days
FFF: DEBUG: 2021-12-22 11:16:27,264: cli.py(223):     OS Version:Linux-5.15.8-1-default-x86_64-with-glibc2.34
FFF: DEBUG: 2021-12-22 11:16:27,264: cli.py(224): Python Version:3.8.12 (default, Aug 31 2021, 01:23:42) [GCC]
FFF: DEBUG: 2021-12-22 11:16:27,264: cli.py(225):    FFF Version:4.8.6
FFF: DEBUG: 2021-12-22 11:16:27,279: configurable.py(1029): use_browser_cache:
FFF: DEBUG: 2021-12-22 11:16:27,279: configurable.py(1043): use_basic_cache:true
FFF: DEBUG: 2021-12-22 11:16:27,286: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days
FFF: DEBUG: 2021-12-22 11:16:27,286: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days
FFF: DEBUG: 2021-12-22 11:16:27,663: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:16:27,664: requestable.py(50): Encoding:utf8
FFF: INFO: 2021-12-22 11:16:27,666: adapter_fictionhuntcom.py(98): This site requires login.
Login Failed, Need Username/Password.
^CUsername: Traceback (most recent call last):
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/cli.py", line 428, in do_download
    adapter.getStoryMetadataOnly()
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/adapters/base_adapter.py", line 308, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/adapters/adapter_fictionhuntcom.py", line 127, in doExtractChapterUrlsAndMetadata
    self.performLogin(url)
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/adapters/adapter_fictionhuntcom.py", line 99, in performLogin
    raise exceptions.FailedToLogin(url,params['identifier'])
fanficfare.exceptions.FailedToLogin: Failed to Login for URL: (https://fictionhunt.com/stories/p7wnx17/twentyone-days) with username: ()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matej/.local/bin/fanficfare", line 11, in <module>
    load_entry_point('FanFicFare', 'console_scripts', 'fanficfare')()
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/cli.py", line 337, in main
    dispatch(options, urls, passed_defaultsini, passed_personalini, warn, fail)
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/cli.py", line 313, in dispatch
    do_download(url,
  File "/home/matej/archiv/knihovna/repos/tmp/FanFicFare/fanficfare/cli.py", line 438, in do_download
    adapter.username = sys.stdin.readline().strip()
KeyboardInterrupt

FanFicFare@stitny (main)$
```
However, when I comment out `needToLoginCheck` method (which is certainly NOT the right solution, it is just to illustrate the point), everything works just fine:
```
FanFicFare@stitny (fictionhunt_login)$ fanficfare --debug https://fictionhunt.com/stories/p7wnx17/twentyone-days
FFF: DEBUG: 2021-12-22 11:17:47,223: cli.py(223):     OS Version:Linux-5.15.8-1-default-x86_64-with-glibc2.34
FFF: DEBUG: 2021-12-22 11:17:47,223: cli.py(224): Python Version:3.8.12 (default, Aug 31 2021, 01:23:42) [GCC]
FFF: DEBUG: 2021-12-22 11:17:47,223: cli.py(225):    FFF Version:4.8.6
FFF: DEBUG: 2021-12-22 11:17:47,236: configurable.py(1029): use_browser_cache:
FFF: DEBUG: 2021-12-22 11:17:47,236: configurable.py(1043): use_basic_cache:true
FFF: DEBUG: 2021-12-22 11:17:47,242: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days
FFF: DEBUG: 2021-12-22 11:17:47,242: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days
FFF: DEBUG: 2021-12-22 11:17:47,503: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:47,503: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:47,611: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/users/nd6kq5/evil-minded
FFF: DEBUG: 2021-12-22 11:17:47,611: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/users/nd6kq5/evil-minded
FFF: DEBUG: 2021-12-22 11:17:47,809: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:47,810: requestable.py(50): Encoding:utf8
FFF: INFO: 2021-12-22 11:17:48,028: base_writer.py(183): Save directly to file: Twentyone days-fichunt_p7wnx17.epub
FFF: DEBUG: 2021-12-22 11:17:48,029: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/1
FFF: DEBUG: 2021-12-22 11:17:48,029: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/1
FFF: DEBUG: 2021-12-22 11:17:48,029: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/1
FFF: DEBUG: 2021-12-22 11:17:48,154: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:48,155: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:48,303: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/2
FFF: DEBUG: 2021-12-22 11:17:48,304: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/2
FFF: DEBUG: 2021-12-22 11:17:48,304: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/2
FFF: DEBUG: 2021-12-22 11:17:48,458: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:48,459: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:48,655: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/3
FFF: DEBUG: 2021-12-22 11:17:48,655: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/3
FFF: DEBUG: 2021-12-22 11:17:48,655: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/3
FFF: DEBUG: 2021-12-22 11:17:48,857: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:48,859: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:49,053: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/4
FFF: DEBUG: 2021-12-22 11:17:49,053: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/4
FFF: DEBUG: 2021-12-22 11:17:49,053: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/4
FFF: DEBUG: 2021-12-22 11:17:49,289: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:49,290: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:49,480: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/5
FFF: DEBUG: 2021-12-22 11:17:49,480: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/5
FFF: DEBUG: 2021-12-22 11:17:49,480: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/5
FFF: DEBUG: 2021-12-22 11:17:49,655: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:49,657: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:49,925: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/6
FFF: DEBUG: 2021-12-22 11:17:49,925: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/6
FFF: DEBUG: 2021-12-22 11:17:49,925: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/6
FFF: DEBUG: 2021-12-22 11:17:50,121: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:50,123: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:50,353: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/7
FFF: DEBUG: 2021-12-22 11:17:50,353: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/7
FFF: DEBUG: 2021-12-22 11:17:50,353: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/7
FFF: DEBUG: 2021-12-22 11:17:50,539: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:50,539: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:50,802: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/8
FFF: DEBUG: 2021-12-22 11:17:50,802: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/8
FFF: DEBUG: 2021-12-22 11:17:50,803: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/8
FFF: DEBUG: 2021-12-22 11:17:50,986: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:50,987: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:51,319: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/9
FFF: DEBUG: 2021-12-22 11:17:51,319: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/9
FFF: DEBUG: 2021-12-22 11:17:51,320: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/9
FFF: DEBUG: 2021-12-22 11:17:51,543: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:51,544: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:51,942: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/10
FFF: DEBUG: 2021-12-22 11:17:51,942: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/10
FFF: DEBUG: 2021-12-22 11:17:51,943: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/10
FFF: DEBUG: 2021-12-22 11:17:52,260: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:52,261: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:52,550: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/11
FFF: DEBUG: 2021-12-22 11:17:52,550: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/11
FFF: DEBUG: 2021-12-22 11:17:52,550: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/11
FFF: DEBUG: 2021-12-22 11:17:52,725: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:52,727: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:52,980: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/12
FFF: DEBUG: 2021-12-22 11:17:52,980: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/12
FFF: DEBUG: 2021-12-22 11:17:52,980: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/12
FFF: DEBUG: 2021-12-22 11:17:53,182: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:53,183: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:53,404: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/13
FFF: DEBUG: 2021-12-22 11:17:53,404: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/13
FFF: DEBUG: 2021-12-22 11:17:53,405: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/13
FFF: DEBUG: 2021-12-22 11:17:53,581: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:53,583: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:53,960: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/14
FFF: DEBUG: 2021-12-22 11:17:53,960: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/14
FFF: DEBUG: 2021-12-22 11:17:53,960: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/14
FFF: DEBUG: 2021-12-22 11:17:54,115: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:54,116: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:54,341: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/15
FFF: DEBUG: 2021-12-22 11:17:54,341: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/15
FFF: DEBUG: 2021-12-22 11:17:54,342: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/15
FFF: DEBUG: 2021-12-22 11:17:54,544: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:54,546: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:54,930: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/16
FFF: DEBUG: 2021-12-22 11:17:54,930: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/16
FFF: DEBUG: 2021-12-22 11:17:54,931: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/16
FFF: DEBUG: 2021-12-22 11:17:55,093: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:55,094: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:55,340: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/17
FFF: DEBUG: 2021-12-22 11:17:55,341: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/17
FFF: DEBUG: 2021-12-22 11:17:55,341: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/17
FFF: DEBUG: 2021-12-22 11:17:55,481: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:55,484: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:55,733: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/18
FFF: DEBUG: 2021-12-22 11:17:55,734: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/18
FFF: DEBUG: 2021-12-22 11:17:55,734: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/18
FFF: DEBUG: 2021-12-22 11:17:55,874: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:55,877: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:56,170: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/19
FFF: DEBUG: 2021-12-22 11:17:56,170: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/19
FFF: DEBUG: 2021-12-22 11:17:56,170: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/19
FFF: DEBUG: 2021-12-22 11:17:56,337: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:56,337: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:56,589: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/20
FFF: DEBUG: 2021-12-22 11:17:56,589: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/20
FFF: DEBUG: 2021-12-22 11:17:56,589: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/20
FFF: DEBUG: 2021-12-22 11:17:56,729: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:56,730: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:56,953: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/21
FFF: DEBUG: 2021-12-22 11:17:56,953: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/21
FFF: DEBUG: 2021-12-22 11:17:56,953: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/21
FFF: DEBUG: 2021-12-22 11:17:57,097: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:57,099: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:57,365: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/22
FFF: DEBUG: 2021-12-22 11:17:57,366: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/22
FFF: DEBUG: 2021-12-22 11:17:57,366: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/22
FFF: DEBUG: 2021-12-22 11:17:57,517: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:57,519: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:57,733: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/23
FFF: DEBUG: 2021-12-22 11:17:57,734: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/23
FFF: DEBUG: 2021-12-22 11:17:57,734: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/23
FFF: DEBUG: 2021-12-22 11:17:57,854: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:57,856: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:58,075: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/24
FFF: DEBUG: 2021-12-22 11:17:58,075: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/24
FFF: DEBUG: 2021-12-22 11:17:58,075: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/24
FFF: DEBUG: 2021-12-22 11:17:58,215: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:58,217: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:58,471: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/25
FFF: DEBUG: 2021-12-22 11:17:58,471: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/25
FFF: DEBUG: 2021-12-22 11:17:58,471: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/25
FFF: DEBUG: 2021-12-22 11:17:58,600: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:58,601: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:58,867: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/26
FFF: DEBUG: 2021-12-22 11:17:58,868: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/26
FFF: DEBUG: 2021-12-22 11:17:58,868: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/26
FFF: DEBUG: 2021-12-22 11:17:58,994: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:58,995: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:59,220: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/27
FFF: DEBUG: 2021-12-22 11:17:59,220: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/27
FFF: DEBUG: 2021-12-22 11:17:59,220: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/27
FFF: DEBUG: 2021-12-22 11:17:59,357: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:59,359: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:17:59,641: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/28
FFF: DEBUG: 2021-12-22 11:17:59,641: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/28
FFF: DEBUG: 2021-12-22 11:17:59,641: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/28
FFF: DEBUG: 2021-12-22 11:17:59,774: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:17:59,775: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:18:00,188: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/29
FFF: DEBUG: 2021-12-22 11:18:00,188: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/29
FFF: DEBUG: 2021-12-22 11:18:00,188: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/29
FFF: DEBUG: 2021-12-22 11:18:00,336: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:18:00,337: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:18:00,617: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/30
FFF: DEBUG: 2021-12-22 11:18:00,617: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/30
FFF: DEBUG: 2021-12-22 11:18:00,617: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/30
FFF: DEBUG: 2021-12-22 11:18:00,806: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:18:00,807: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2021-12-22 11:18:01,034: adapter_fictionhuntcom.py(218): Getting chapter text from: https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/31
FFF: DEBUG: 2021-12-22 11:18:01,035: fetcher.py(234):
========== MISS (GET) BasicCache
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/31
FFF: DEBUG: 2021-12-22 11:18:01,035: fetcher.py(462):
---------- REQ (GET) RequestsFetcher
https://fictionhunt.com/stories/p7wnx17/twentyone-days/chapters/31
FFF: DEBUG: 2021-12-22 11:18:01,164: fetcher.py(469): response code:200
.FFF: DEBUG: 2021-12-22 11:18:01,166: requestable.py(50): Encoding:utf8
FFF: INFO: 2021-12-22 11:18:01,278: writer_epub.py(360): Saving EPUB Version 2.0
FFF: DEBUG: 2021-12-22 11:18:01,989: cli.py(63): Successfully wrote 'Twentyone days-fichunt_p7wnx17.epub'
FanFicFare@stitny (fictionhunt_login)$ rm Twentyone\ days-fichunt_p7wnx17.epub
```

**Comment by JimmXinu** [comment]
Nov 2019 (720e6f088e5484260d70ae686be4ed9a9721461e) fictionhunt started requiring login to see any chapter, so FFF changed accordingly.

Do you have any examples of stories that do still require login?  I'm not finding any, but I don't read fictionhunt.

**Comment by mcepl** [comment]
Hmm, it doesn’t look like there are any. I just browsed through M-rated ones and they seem to be all open (including some rather steamy ones). But perhaps it is just temporary. And no, I don't usually read fictionhunt myself, but this is the only full-length copy of this story on the Internet I can find.
