### ISSUE TITLE
find_all on NoneType with Spacebattles after code update

### ISSUE THREAD

**Issue by HowardJeng** [JimmXinu/FanFicFare#830]
Spacebattles recently did a code update and it looks like it broke the adapter. I'm getting errors that look like this with FFF 4.12.0.

```
FFF: INFO: 2022-04-30 01:53:17,258: base_xenforoforum_adapter.py(455): use useurl: https://forums.spacebattles.com/threads/all-wo-rk-and-no-play-an-abyssals-trials-in-the-job-market-kc.737809/
FFF: INFO: 2022-04-30 01:53:18,021: calibre_plugins.fanficfare_plugin.jobs(439): Exception: {'title': "All Wo-rk and No Play: An Abyssal's Trials in the Job Market", 'author_sort': 'PyrrhicSteel', 'author': ['PyrrhicSteel'], 'comments': '', 'good': False, 'status': 'Error', 'showerror': True, 'calibre_id': 2626, 'begin': None, 'end': None, 'comment': "'NoneType' object has no attribute 'find_all'", 'url': 'https://forums.spacebattles.com/threads/all-wo-rk-and-no-play-an-abyssals-trials-in-the-job-market-kc.737809/', 'site': 'forums.spacebattles.com', 'series': '', 'added': False, 'pubdate': None, 'publisher': 'forums.spacebattles.com', 'listorder': 8, 'collision': 'Update EPUB if New Chapters', 'uniqueurl': 'https://forums.spacebattles.com/threads/all-wo-rk-and-no-play-an-abyssals-trials-in-the-job-market-kc.737809/[None-None]', 'is_adult': False, 'username': 'NoneGiven', 'password': '', 'icon': 'dialog_error.png', 'epub_for_update': 'C:\\Users\\hjeng\\AppData\\Local\\Temp\\calibre_d5fvewqy\\fanficfare_pjv1efhv\\old-2626-wo6et9y8.epub', 'calibre_columns': {}, 'outfile': 'C:\\Users\\hjeng\\AppData\\Local\\Temp\\calibre_d5fvewqy\\fanficfare_pjv1efhv\\bgmeta-vx7y4pd3.epub'}:'NoneType' object has no attribute 'find_all'
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.jobs", line 260, in do_download_for_worker
  File "C:\Users\hjeng\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\adapters\base_adapter.py", line 308, in getStoryMetadataOnly
  File "C:\Users\hjeng\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\adapters\base_adapter.py", line 412, in doExtractChapterUrlsAndMetadata
  File "C:\Users\hjeng\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\adapters\base_xenforoforum_adapter.py", line 477, in extractChapterUrlsAndMetadata
  File "C:\Users\hjeng\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\adapters\base_xenforo2forum_adapter.py", line 93, in parse_title
AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Comment by JimmXinu** [comment]
Already addressed in 6e3055e75303bb0cc4b7c03475034a7f03f9810c

Test versions are out in [the usual places](https://github.com/JimmXinu/FanFicFare#test-versions).

I will leave this issue open for now for others to see.

**Comment by gille90** [comment]
For some reason, the test version won't load. It says to restart Calibre. When I do that fanficfare disappears from the plugins. If I search in the plugin settings it's still there, but it says to restart Calibre ???? how do I get out of this loop, restart the computer? didn't have to do that all the time before when I instaled the test version.

**Comment by JimmXinu** [comment]
Download the test plugin again.  If it still doesn't work, run Calibre in debug mode, the debug log tells you a lot.

**Comment by gille90** [comment]
got this. No Id what it  means, not a programmer just a fan.

calibre Foutopsporingslog
calibre 3.48 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.15+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: nl
Successfully initialized third party plugins: FanFicFare (4, 12, 2)
calibre 3.48 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.15+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: nl
Successfully initialized third party plugins: FanFicFare (4, 12, 2)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 72.035450517 x 72.0
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.05] splash screen shown
[0.05] Initializing db...
[0.11] db initialized
[0.11] Constructing main UI...
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2q  20 Nov 2018) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected Captcha or cloudflare 1020 blocks.
Traceback (most recent call last):
  File "site-packages\calibre\gui2\ui.py", line 157, in __init__
  File "site-packages\calibre\gui2\ui.py", line 171, in init_iaction
  File "calibre_plugins.fanficfare_plugin.__init__", line 121, in load_actual_plugin
  File "site-packages\calibre\customize\__init__.py", line 612, in load_actual_plugin
  File "importlib\__init__.py", line 37, in import_module
  File "site-packages\calibre\customize\zipplugin.py", line 185, in load_module
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 80, in <module>
  File "C:\Users\francy\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\adapters\__init__.py", line 72, in <module>
  File "C:\Users\francy\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\adapters\adapter_finestoriescom.py", line 24, in <module>
  File "C:\Users\francy\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\adapters\adapter_storiesonlinenet.py", line 471
    url = f"https://{self.getSiteDomain()}/res/responders/tl.php?r={random.randint(1, 100001)}"
                                                                                              ^
SyntaxError: invalid syntax
Loaded cached store plugin for: ManyBooks at version: 2
Loaded cached store plugin for: Kobo at version: 8
Loaded cached store plugin for: XinXii at version: 2
Loaded cached store plugin for: Project Gutenberg at version: 8
[1.93] main UI initialized...
[1.93] Hiding splash screen
[43.10] splash screen hidden
[43.10] Started up in 43.10 seconds with 1013 books
Loaded cached store plugin for: ManyBooks at version: 2
Loaded cached store plugin for: Kobo at version: 8
Loaded cached store plugin for: XinXii at version: 2
Loaded cached store plugin for: Project Gutenberg at version: 8
Loaded cached store plugin for: ManyBooks at version: 2
Loaded cached store plugin for: Kobo at version: 8
Loaded cached store plugin for: XinXii at version: 2
Loaded cached store plugin for: Project Gutenberg at version: 8

**Comment by JimmXinu** [comment]
#829 made a storiesonline.net change that isn't py2 compatible, which Calibre v3 needs.

@mvlcek, can you address this, or do I need to?

**Comment by mvlcek** [comment]
See https://github.com/JimmXinu/FanFicFare/pull/832
