### ISSUE TITLE
Type Error Comparing Int to NoneType when 'Marking' updates/new stories

### ISSUE THREAD

**Issue by Chirishman** [JimmXinu/FanFicFare#833]
Since the latest update to both Calibre and FFF I get the following error when adding new stories. Doesn't seem to occur when updating existing books at least as far as I've been able to tell. This particular one occurred when saving content from RoyalRoad, I can provide story URLs if that would b helpful.

```
calibre, version 5.42.0
ERROR: Unhandled exception: <b>TypeError</b>:'&lt;' not supported between instances of 'int' and 'NoneType'

calibre 5.42 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17763 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 3.8.5
Windows: ('10', '10.0.17763', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 48, 0) && DeDRM (7, 0, 0) && Package KFX (from KFX Input) (1, 48, 0) && BookFusion Plugin (0, 6, 3) && Count Pages (1, 11, 2) && Embed Comic Metadata (1, 6, 1) && English Noun Frequency (1, 0, 13) && EpubMerge (2, 13, 0) && FanFicFare (4, 12, 4) && Find Duplicates (1, 9, 5) && Generate Cover (2, 1, 0) && Goodreads (1, 5, 3) && Goodreads More Tags (1, 2, 1) && Goodreads Sync (1, 15, 1) && Job Spy (1, 0, 190) && KFX metadata reader (from KFX Input) (1, 48, 0) && KFX Input (1, 48, 0) && Set KFX metadata (from KFX Output) (1, 61, 0) && KFX Output (1, 61, 0) && Kindle Collections (1, 7, 29) && KyBook3 Sync (1, 0, 12) && Library Codes (1, 0, 50) && Mass Search-Replace (1, 4, 2) && Media File Importer (1, 0, 24) && MultiColumnSearch (1, 0, 87) && Open With (1, 7, 0) && Overdrive Link (2, 51, 0) && Reading List (1, 9, 0) && Save Composite Custom Columns (1, 1, 1) && TTS to MP3 (0, 5, 9) && WordDumb (3, 20, 1) && X-Ray Creator (3, 2, 1) && Overdrive Link Metadata Source (2, 51, 0)
Traceback (most recent call last):
  File "calibre\gui2\proceed.py", line 208, in do_ask_question
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 2126, in do_download_list_update
  File "calibre_plugins.fanficfare_plugin.dialogs", line 639, in LoopProgressDialog
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1887, in update_books_finish
  File "calibre\db\view.py", line 393, in set_marked_ids
  File "calibre\gui2\__init__.py", line 585, in __call__
  File "calibre\gui2\library\views.py", line 968, in marked_changed
  File "calibre\gui2\library\models.py", line 400, in refresh_rows
  File "calibre\gui2\library\models.py", line 74, in group_numbers
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```

**Comment by JimmXinu** [comment]
This was previously [reported in mobileread](https://www.mobileread.com/forums/showthread.php?p=4216230&postcount=7049).  It was [determined](https://www.mobileread.com/forums/showthread.php?p=4216336&postcount=7057) to be a corner case issue with recent changes to Calibre 'Mark' feature.  

I haven't heard since anything since.  To the best of my knowledge, it's not something I can fix in FFF and I can't reproduce it.  

You may need to turn off the 'Mark' and 'Show Marked' features in FFF in the meantime.

I'll leave this issue open for the time being.

**Comment by JimmXinu** [comment]
Test version posted in the usual place.  I think this should fix the issue.  Further discussion [here](https://www.mobileread.com/forums/showthread.php?p=4224432#post4224432).
