### ISSUE TITLE
Can't download story on QQ if author's account is guest/deleted

### ISSUE THREAD

**Issue by kido5217** [JimmXinu/FanFicFare#852]
Story example: [https://forum.questionablequesting.com/threads/greg-the-hero.16576/](https://forum.questionablequesting.com/threads/greg-the-hero.16576/)

Error:

```python
fanficfare 'https://forum.questionablequesting.com/threads/greg-the-hero.16576/'
Traceback (most recent call last):
  File "/usr/bin/fanficfare", line 33, in <module>
    sys.exit(load_entry_point('FanFicFare==4.13.2', 'console_scripts', 'fanficfare')())
  File "/usr/lib/python3.10/site-packages/fanficfare/cli.py", line 344, in main
    dispatch(options, urls, passed_defaultsini, passed_personalini, warn, fail)
  File "/usr/lib/python3.10/site-packages/fanficfare/cli.py", line 320, in dispatch
    do_download(url,
  File "/usr/lib/python3.10/site-packages/fanficfare/cli.py", line 435, in do_download
    adapter.getStoryMetadataOnly()
  File "/usr/lib/python3.10/site-packages/fanficfare/adapters/base_adapter.py", line 308, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "/usr/lib/python3.10/site-packages/fanficfare/adapters/base_adapter.py", line 412, in doExtractChapterUrlsAndMetadata
    return self.extractChapterUrlsAndMetadata()
  File "/usr/lib/python3.10/site-packages/fanficfare/adapters/base_xenforoforum_adapter.py", line 565, in extractChapterUrlsAndMetadata
    self.parse_author(souptag)
  File "/usr/lib/python3.10/site-packages/fanficfare/adapters/base_xenforoforum_adapter.py", line 621, in parse_author
    self.story.addToList('authorId',a['href'].split('/')[1])
  File "/usr/lib/python3.10/site-packages/bs4/element.py", line 1486, in __getitem__
    return self.attrs[key]
KeyError: 'href'
```

**Comment by JimmXinu** [comment]
New test versions posted as usual.

**Comment by kido5217** [comment]
Works for me. Thank you.
