### ISSUE TITLE
unable to run fanficfare CLI on windows 10

### ISSUE THREAD

**Issue by mhussaincov93** [JimmXinu/FanFicFare#853]
hi,
fresh install of win 10.
unable to run fanficfare cli after pip install.
details.
python version=3.10
pip is up to date.
I installed latest calibre from the site incase it may change this error but still the error.
brotli is installed.
I would be greatful for assistence.
error message below.

fanficfare -d https://www.royalroad.com/fiction/18225/molting-the-mortal-coil
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\fanficfare\browsercache\basebrowsercache.py", line 10, in <module>
    import brotli
  File "C:\Program Files\Python310\lib\site-packages\brotli.py", line 8, in <module>
    import _brotli
ImportError: DLL load failed while importing _brotli: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\Scripts\fanficfare-script.py", line 33, in <module>
    sys.exit(load_entry_point('FanFicFare==4.13.0', 'console_scripts', 'fanficfare')())
  File "C:\Program Files\Python310\Scripts\fanficfare-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Program Files\Python310\lib\importlib\metadata\__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "C:\Program Files\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Program Files\Python310\lib\site-packages\fanficfare\cli.py", line 46, in <module>
    from fanficfare import adapters, writers, exceptions
  File "C:\Program Files\Python310\lib\site-packages\fanficfare\adapters\__init__.py", line 29, in <module>
    from .. import configurable as configurable
  File "C:\Program Files\Python310\lib\site-packages\fanficfare\configurable.py", line 48, in <module>
    from .browsercache import BrowserCache
  File "C:\Program Files\Python310\lib\site-packages\fanficfare\browsercache\__init__.py", line 2, in <module>
    from .basebrowsercache import BrowserCacheException, BaseBrowserCache
  File "C:\Program Files\Python310\lib\site-packages\fanficfare\browsercache\basebrowsercache.py", line 14, in <module>
    from calibre_plugins.fanficfare_plugin import brotlidecpy as brotli
ModuleNotFoundError: No module named 'calibre_plugins'
thanks,
Majid

**Comment by JimmXinu** [comment]
Your `brotli` package install isn't working.  The important part is:
```
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\fanficfare\browsercache\basebrowsercache.py", line 10, in <module>
    import brotli
  File "C:\Program Files\Python310\lib\site-packages\brotli.py", line 8, in <module>
    import _brotli
ImportError: DLL load failed while importing _brotli: The specified module could not be found.
```
It looks like you're missing a DLL that `brotli` needs.

Everything after `During handling of the above exception, another exception occurred:` is because FFF attempts to import  your installed `brotli` first and only if that fails looks for `brotlidecpy` in the plugin (shared code between CLI and plugin).  

All I can suggest is that you uninstall/reinstall the `brotli` package, see if that helps.  Does `pip` have a debug mode?

**Comment by mhussaincov93** [comment]
hi,
removed the system install of fanficfare and installed to user dir.
not sure if that was the issue but i've got it working :)
thank you for your help sir :)
too used to linux.
Majid
