### ISSUE TITLE
Spacebattles fic failing to download

### ISSUE THREAD

**Issue by Hate9** [JimmXinu/FanFicFare#857]
```
$ fanficfare https://forums.spacebattles.com/threads/bloody-tinkers-worm-bloodborne-crackfic-complete.628423/
Traceback (most recent call last):
  File "/usr/bin/fanficfare", line 33, in <module>
    sys.exit(load_entry_point('FanFicFare==4.10.0', 'console_scripts', 'fanficfare')())
  File "/usr/lib/python3.10/site-packages/fanficfare/cli.py", line 337, in main
    dispatch(options, urls, passed_defaultsini, passed_personalini, warn, fail)
  File "/usr/lib/python3.10/site-packages/fanficfare/cli.py", line 313, in dispatch
    do_download(url,
  File "/usr/lib/python3.10/site-packages/fanficfare/cli.py", line 428, in do_download
    adapter.getStoryMetadataOnly()
  File "/usr/lib/python3.10/site-packages/fanficfare/adapters/base_adapter.py", line 308, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "/usr/lib/python3.10/site-packages/fanficfare/adapters/base_adapter.py", line 412, in doExtractChapterUrlsAndMetadata
    return self.extractChapterUrlsAndMetadata()
  File "/usr/lib/python3.10/site-packages/fanficfare/adapters/base_xenforoforum_adapter.py", line 477, in extractChapterUrlsAndMetadata
    self.parse_title(topsoup)
  File "/usr/lib/python3.10/site-packages/fanficfare/adapters/base_xenforo2forum_adapter.py", line 93, in parse_title
    for tag in h1.find_all('span',{'class':'label'}):
AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Comment by JimmXinu** [comment]
Your error message indicates you are using an older version (`FanFicFare==4.10.0`) from Feb 2022.  This issue has since been fixed.  Current FFF release is v4.13.0.

**Comment by Hate9** [comment]
Ah. In that case, it would appear that the issue is the AUR package being out of date, and the arch os repo version not apparently existing.

**Comment by kido5217** [comment]
In arch [fanficfare-git](https://aur.archlinux.org/packages/fanficfare-git) from AUR works fine for me.

**Comment by Hate9** [comment]
Huh. It wasn't for me. I reinstalled it and now it works fine. Weird.
