### ISSUE TITLE
asianfanfics.com IndexError: list index out of range

### ISSUE THREAD

**Issue by himlayyy** [JimmXinu/FanFicFare#862]
Tried downloading this https://www.asianfanfics.com/story/view/1480275/sterling-notebook-bawal-basahin but I'm getting IndexError: list index out of range

Similar issue  with #738 

Fanficfare cli version 4.13.0

Traceback:
Traceback (most recent call last):
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python38\Scripts\fanficfare-script.py", line 11, in <module>
    load_entry_point('FanFicFare==3.18.0', 'console_scripts', 'fanficfare')()
  File "c:\users\asus\appdata\local\programs\python\python38\lib\site-packages\fanficfare\cli.py", line 305, in main
    do_download(url,
  File "c:\users\asus\appdata\local\programs\python\python38\lib\site-packages\fanficfare\cli.py", line 490, in do_download
    output_filename = write_story(configuration, adapter, options.format,
  File "c:\users\asus\appdata\local\programs\python\python38\lib\site-packages\fanficfare\cli.py", line 85, in write_story
    writer.writeStory(outstream=outstream, metaonly=metaonly)
  File "c:\users\asus\appdata\local\programs\python\python38\lib\site-packages\fanficfare\writers\base_writer.py", line 231, in writeStory
    self.writeStoryImpl(outstream)
  File "c:\users\asus\appdata\local\programs\python\python38\lib\site-packages\fanficfare\writers\writer_epub.py", line 351, in writeStoryImpl
    self.story.getList('authorId')[0],
IndexError: list index out of range

**Comment by JimmXinu** [comment]
Actually, it looks like you have FFF version 3.18.0.  From above:
` load_entry_point('FanFicFare==3.18.0', 'console_scripts', 'fanficfare')()`

What does `fanficfare -v` report?

I'm not seeing any problem with the current version.
