### ISSUE TITLE
Fimfiction.net is showing an error on download

### ISSUE THREAD

**Issue by Kirtai** [JimmXinu/FanFicFare#898]
The page
```
https://www.fimfiction.net/story/439925/a-pony-named-nope
```
is giving the error message
```
calibre, version 6.9.0 (linux, embedded-python: True)
Failed to Download Stories: Failed: Download 1 FanFiction Book(s)

Download 1 FanFiction Book(s)
FFF: INFO: 2022-12-14 10:45:31,809: calibre_plugins.fanficfare_plugin.jobs(49): CPUs:3
FFF: INFO: 2022-12-14 10:45:31,809: calibre_plugins.fanficfare_plugin.jobs(52): FanFicFare v4.18.0
FFF: INFO: 2022-12-14 10:45:31,809: calibre_plugins.fanficfare_plugin.jobs(68): Launch background process for site www.fimfiction.net:
https://www.fimfiction.net/story/439925/
FFF: INFO: 2022-12-14 10:45:38,417: calibre_plugins.fanficfare_plugin.jobs(130): 

================================================================================ site:(www.fimfiction.net)
FFF: INFO: 2022-12-14 10:45:33,159: calibre_plugins.fanficfare_plugin.jobs(211): 

-------------------------------------------------------------------------------- https://www.fimfiction.net/story/439925/
FFF: DEBUG: 2022-12-14 10:45:33,179: configurable.py(1059): use_browser_cache:
FFF: DEBUG: 2022-12-14 10:45:33,179: configurable.py(1073): use_basic_cache:true
FFF: DEBUG: 2022-12-14 10:45:33,180: fetcher.py(234): 
========== HIT (GET) BasicCache
https://www.fimfiction.net/story/439925/
FFF: DEBUG: 2022-12-14 10:45:33,181: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2022-12-14 10:45:34,095: base_adapter.py(577): setCoverImage(https://www.fimfiction.net/story/439925/,https://cdn-img.fimfiction.net/story/zzha-1613608499-439925-full)
FFF: DEBUG: 2022-12-14 10:45:34,095: story.py(1417): addImgUrl(parenturl=https://www.fimfiction.net/story/439925/,url=https://cdn-img.fimfiction.net/story/zzha-1613608499-439925-full,cover=True,coverexclusion=/images/emoticons/
FFF: DEBUG: 2022-12-14 10:45:34,095: fetcher.py(234): 
========== MISS (GET) BasicCache
https://cdn-img.fimfiction.net/story/zzha-1613608499-439925-full
FFF: DEBUG: 2022-12-14 10:45:34,095: fetcher.py(479): 
---------- REQ (GET) RequestsFetcher
https://cdn-img.fimfiction.net/story/zzha-1613608499-439925-full
FFF: DEBUG: 2022-12-14 10:45:34,301: fetcher.py(492): response code:200
FFF: INFO: 2022-12-14 10:45:34,302: story.py(188): no_convert_image url:https://cdn-img.fimfiction.net/story/zzha-1613608499-439925-full - no known extension -- using .jpg
FFF: INFO: 2022-12-14 10:45:34,652: calibre_plugins.fanficfare_plugin.jobs(367): Do update - epub(11) vs url(12)
FFF: INFO: 2022-12-14 10:45:34,652: calibre_plugins.fanficfare_plugin.jobs(368): write to /tmp/calibre_6.9.0_tmp_63dv6ism/fanficfare_aogvi63_/A Pony Named Nope-Nyerguds-ac5bku7j.epub
FFF: INFO: 2022-12-14 10:45:34,652: base_writer.py(183): Save directly to file: /tmp/calibre_6.9.0_tmp_63dv6ism/fanficfare_aogvi63_/A Pony Named Nope-Nyerguds-ac5bku7j.epub
FFF: DEBUG: 2022-12-14 10:45:34,797: story.py(1417): addImgUrl(parenturl=None,url=https://static.fimfiction.net/images/emoticons/moustache.png,cover=False,coverexclusion=/images/emoticons/
FFF: DEBUG: 2022-12-14 10:45:35,083: adapter_fimfictionnet.py(360): Getting chapter text from: https://www.fimfiction.net/story/439925/12/a-pony-named-nope/nopes-little-errands-a-hellish-affair
FFF: DEBUG: 2022-12-14 10:45:35,084: fetcher.py(234): 
========== MISS (GET) BasicCache
https://www.fimfiction.net/story/439925/12/a-pony-named-nope/nopes-little-errands-a-hellish-affair
FFF: DEBUG: 2022-12-14 10:45:35,084: fetcher.py(479): 
---------- REQ (GET) RequestsFetcher
https://www.fimfiction.net/story/439925/12/a-pony-named-nope/nopes-little-errands-a-hellish-affair
FFF: DEBUG: 2022-12-14 10:45:35,569: fetcher.py(492): response code:200
FFF: DEBUG: 2022-12-14 10:45:35,571: requestable.py(50): Encoding:utf8
FFF: DEBUG: 2022-12-14 10:45:36,794: story.py(1417): addImgUrl(parenturl=https://www.fimfiction.net/story/439925/12/a-pony-named-nope/nopes-little-errands-a-hellish-affair,url=https://static.fimfiction.net/images/emoticons/facehoof.png,cover=False,coverexclusion=/images/emoticons/
FFF: DEBUG: 2022-12-14 10:45:36,794: fetcher.py(234): 
========== MISS (GET) BasicCache
https://static.fimfiction.net/images/emoticons/facehoof.png
FFF: DEBUG: 2022-12-14 10:45:36,794: fetcher.py(479): 
---------- REQ (GET) RequestsFetcher
https://static.fimfiction.net/images/emoticons/facehoof.png
FFF: DEBUG: 2022-12-14 10:45:36,917: fetcher.py(492): response code:200
FFF: INFO: 2022-12-14 10:45:36,955: writer_epub.py(369): Saving EPUB Version 2.0

Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 47, in <module>
  File "site.py", line 43, in main
  File "calibre/utils/ipc/worker.py", line 215, in main
  File "calibre/utils/ipc/worker.py", line 150, in arbitrary_n
  File "calibre_plugins.fanficfare_plugin.jobs", line 134, in do_download_worker
TypeError: 'NoneType' object is not iterable
```
when trying to update the story.

**Comment by JimmXinu** [comment]
I cannot replicate this.  Nor can I think of any way it could happen.

Does this happen consistently or you, or was it a one off?

**Comment by Kirtai** [comment]
Must have been something wrong on the server side. It's working now.

Sorry for bothering you.

**Comment by JimmXinu** [comment]
Okay.  But FYI, I'd run a memory tester if you are having other weirdness happening.
