### ISSUE TITLE
None of the 1 URLs/stories given can be/ need to be downloaded.

### ISSUE THREAD

**Issue by abyssdaisy** [JimmXinu/FanFicFare#936]
for example:
https://www.wattpad.com/story/74601977-the-sea-wolf

here is logs：

https://www.wattpad.com/apiv2/getcategories
FFF: DEBUG: 2023-04-05 02:42:06,081: fetcher_requests.py(84): Calibre Proxies:{'http': '127.0.0.1:2080', 'https': '127.0.0.1:2080', 'ftp': '127.0.0.1:2080'}
FFF: DEBUG: 2023-04-05 02:42:06,081: fetcher_requests.py(95): Session Proxies After INI:{'http': '127.0.0.1:2080', 'https': '127.0.0.1:2080', 'ftp': '127.0.0.1:2080'}
FFF: WARNING: 2023-04-05 02:42:06,120: adapter_wattpadcom.py(53): API_GETCATEGORIES failed.
FFF: DEBUG: 2023-04-05 02:42:08,556: calibre_plugins.fanficfare_plugin.dialogs(493): self.extraoptions['anthology_url']:NOT FOUND
FFF: DEBUG: 2023-04-05 02:42:08,560: calibre_plugins.fanficfare_plugin.fff_plugin(1125): FanFicFare v4.22.1
FFF: DEBUG: 2023-04-05 02:42:08,676: configurable.py(1050): use_browser_cache:
FFF: DEBUG: 2023-04-05 02:42:08,677: configurable.py(1070): use_basic_cache:true
FFF: DEBUG: 2023-04-05 02:42:08,678: cache_basic.py(116): 
========== MISS (GET) BasicCache
https://www.wattpad.com/api/v3/stories/74601977
FFF: DEBUG: 2023-04-05 02:42:08,678: fetcher_requests.py(114): 
---------- REQ (GET) RequestsFetcher
https://www.wattpad.com/api/v3/stories/74601977
FFF: DEBUG: 2023-04-05 02:42:08,679: fetcher_requests.py(84): Calibre Proxies:{'http': '127.0.0.1:2080', 'https': '127.0.0.1:2080', 'ftp': '127.0.0.1:2080'}
FFF: DEBUG: 2023-04-05 02:42:08,679: fetcher_requests.py(95): Session Proxies After INI:{'http': '127.0.0.1:2080', 'https': '127.0.0.1:2080', 'ftp': '127.0.0.1:2080'}
FFF: ERROR: 2023-04-05 02:42:08,717: calibre_plugins.fanficfare_plugin.dialogs(725): Exception: {'title': 'Unknown', 'author_sort': ['Unknown'], 'author': ['Unknown'], 'comments': '', 'good': False, 'status': 'Error', 'showerror': True, 'calibre_id': None, 'begin': None, 'end': None, 'comment': 'Bad Story URL: (https://www.wattpad.com/story/74601977) for site: (www.wattpad.com) Example: (https://www.wattpad.com/story/9999999-story-title https://www.wattpad.com/story/9999999 https://www.wattpad.com/9999999-chapter-is-ok-too)', 'url': 'https://www.wattpad.com/story/74601977', 'site': 'www.wattpad.com', 'series': '', 'added': False, 'pubdate': None, 'publisher': None, 'uniqueurl': 'https://www.wattpad.com/story/74601977[None-None]', 'listorder': 0, 'collision': 'Update EPUB if New Chapters'}:Bad Story URL: (https://www.wattpad.com/story/74601977) for site: (www.wattpad.com) Example: (https://www.wattpad.com/story/9999999-story-title https://www.wattpad.com/story/9999999 https://www.wattpad.com/9999999-chapter-is-ok-too)
Traceback (most recent call last):
  File "C:\Users\endle\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\adapters\adapter_wattpadcom.py", line 104, in doExtractChapterUrlsAndMetadata
  File "C:\Users\endle\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\requestable.py", line 119, in get_request
  File "C:\Users\endle\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\requestable.py", line 111, in get_request_redirected
  File "C:\Users\endle\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\fetchers\base_fetcher.py", line 133, in get_request_redirected
  File "C:\Users\endle\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\fetchers\cache_basic.py", line 122, in fetcher_do_request
  File "C:\Users\endle\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\fetchers\decorators.py", line 102, in fetcher_do_request
  File "C:\Users\endle\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\fetchers\base_fetcher.py", line 106, in do_request
  File "C:\Users\endle\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\fetchers\fetcher_requests.py", line 121, in request
  File "C:\Users\endle\AppData\Roaming\calibre\plugins\FanFicFare.zip\requests\sessions.py", line 542, in request
  File "C:\Users\endle\AppData\Roaming\calibre\plugins\FanFicFare.zip\requests\sessions.py", line 655, in send
  File "C:\Users\endle\AppData\Roaming\calibre\plugins\FanFicFare.zip\requests\adapters.py", line 439, in send
  File "C:\Users\endle\AppData\Roaming\calibre\plugins\FanFicFare.zip\urllib3\connectionpool.py", line 696, in urlopen
  File "C:\Users\endle\AppData\Roaming\calibre\plugins\FanFicFare.zip\urllib3\connectionpool.py", line 964, in _prepare_proxy
  File "C:\Users\endle\AppData\Roaming\calibre\plugins\FanFicFare.zip\urllib3\connection.py", line 359, in connect
  File "C:\Users\endle\AppData\Roaming\calibre\plugins\FanFicFare.zip\urllib3\connection.py", line 500, in _connect_tls_proxy
  File "C:\Users\endle\AppData\Roaming\calibre\plugins\FanFicFare.zip\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "C:\Users\endle\AppData\Roaming\calibre\plugins\FanFicFare.zip\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 512, in wrap_socket
  File "ssl.py", line 1027, in _create
ValueError: check_hostname requires server_hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.dialogs

<a href='https://postimg.cc/sBy4BVYs' target='_blank'><img src='https://i.postimg.cc/sBy4BVYs/Snipaste-2023-04-05-02-30-27.png' border='0' alt='Snipaste-2023-04-05-02-30-27'/></a>

The link is absolutely correct, I've tried several other sites and it doesn't work, what's going on?
Could you help me? plz QAQ

**Comment by abyssdaisy** [comment]
> 
I get it.
tyvm!
Have a nice day.
