### ISSUE TITLE
Problem with ficbook.net

### ISSUE THREAD

**Issue by lntmeu** [JimmXinu/FanFicFare#973]
Trying to download some of the stories results in: `unconverted data remains:  г`
Fanficfare Version: 4.25.0
Example URLs:
> https://ficbook.net/readfic/12180744
> https://ficbook.net/readfic/13462933

```
FFF: DEBUG: 2023-07-04 20:25:12,886: cli.py(230):     OS Version:Linux-6.1.36-hardened1-1-hardened-x86_64-with-glibc2.37
FFF: DEBUG: 2023-07-04 20:25:12,886: cli.py(231): Python Version:3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429]
FFF: DEBUG: 2023-07-04 20:25:12,886: cli.py(232):    FFF Version:4.25.0
FFF: DEBUG: 2023-07-04 20:25:12,894: configurable.py(1068): use_browser_cache:true
FFF: DEBUG: 2023-07-04 20:25:12,894: configurable.py(1070): browser_cache_path:/home/x/.cache/librewolf/ejlsip3u.FanFicFare/cache2
FFF: DEBUG: 2023-07-04 20:25:12,895: browsercache_firefox2.py(45): Using FirefoxCache2
FFF: DEBUG: 2023-07-04 20:25:12,895: configurable.py(1088): use_basic_cache:true
FFF: DEBUG: 2023-07-04 20:25:12,901: adapter_ficbooknet.py(78): URL: https://ficbook.net/readfic/13462933
FFF: DEBUG: 2023-07-04 20:25:12,902: cache_basic.py(116): 
========== MISS (GET) BasicCache
https://ficbook.net/readfic/13462933
FFF: DEBUG: 2023-07-04 20:25:12,902: base_browsercache.py(85): Cache Key:O^partitionKey=%28https%2Cficbook.net%29,:https://ficbook.net/readfic/13462933
FFF: DEBUG: 2023-07-04 20:25:12,902: browsercache_firefox2.py(86): O^partitionKey=%28https%2Cficbook.net%29,:https://ficbook.net/readfic/13462933
FFF: DEBUG: 2023-07-04 20:25:12,902: browsercache_firefox2.py(90): /home/x/.cache/librewolf/ejlsip3u.FanFicFare/cache2/entries/ADAEEC252225B82AB21BDFA1471F3C38509CF9FA
FFF: DEBUG: 2023-07-04 20:25:12,903: base_browsercache.py(85): Cache Key::https://ficbook.net/readfic/13462933
FFF: DEBUG: 2023-07-04 20:25:12,903: browsercache_firefox2.py(86): :https://ficbook.net/readfic/13462933
FFF: DEBUG: 2023-07-04 20:25:12,903: browsercache_firefox2.py(90): /home/x/.cache/librewolf/ejlsip3u.FanFicFare/cache2/entries/2C01218049C886BD8C1ECDE075F935D27D49A9B7
FFF: DEBUG: 2023-07-04 20:25:12,903: base_browsercache.py(100): age:2023-07-04 20:10:33
FFF: DEBUG: 2023-07-04 20:25:12,903: base_browsercache.py(101): now:2023-07-04 20:25:12.903213
FFF: DEBUG: 2023-07-04 20:25:12,903: cache_browser.py(88): 
========== HIT (GET) BrowserCache
https://ficbook.net/readfic/13462933
FFF: DEBUG: 2023-07-04 20:25:12,903: cache_browser.py(92): domain_open_tries:{'ficbook.net': 0}:
FFF: DEBUG: 2023-07-04 20:25:12,903: cache_browser.py(93): fromcache:True
FFF: DEBUG: 2023-07-04 20:25:12,903: decorators.py(112): fromcache:True
FFF: DEBUG: 2023-07-04 20:25:12,903: requestable.py(55): Encoding:utf8
FFF: DEBUG: 2023-07-04 20:25:12,985: adapter_ficbooknet.py(98): Title: (Доктор Торондайк и его звери.)
FFF: DEBUG: 2023-07-04 20:25:12,986: adapter_ficbooknet.py(106): Author: (Мистер Пронька)
FFF: DEBUG: 2023-07-04 20:25:12,989: adapter_ficbooknet.py(127): numChapters: (6)
Traceback (most recent call last):
  File "/home/x/.local/bin/fanficfare", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/x/.local/lib/python3.11/site-packages/fanficfare/cli.py", line 344, in main
    dispatch(options, urls, passed_defaultsini, passed_personalini, warn, fail)
  File "/home/x/.local/lib/python3.11/site-packages/fanficfare/cli.py", line 320, in dispatch
    do_download(url,
  File "/home/x/.local/lib/python3.11/site-packages/fanficfare/cli.py", line 435, in do_download
    adapter.getStoryMetadataOnly()
  File "/home/x/.local/lib/python3.11/site-packages/fanficfare/adapters/base_adapter.py", line 327, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "/home/x/.local/lib/python3.11/site-packages/fanficfare/adapters/base_adapter.py", line 431, in doExtractChapterUrlsAndMetadata
    return self.extractChapterUrlsAndMetadata()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/.local/lib/python3.11/site-packages/fanficfare/adapters/adapter_ficbooknet.py", line 155, in extractChapterUrlsAndMetadata
    self.story.setMetadata('dateUpdated', makeDate(update, self.dateformat))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/.local/lib/python3.11/site-packages/fanficfare/dateutils.py", line 148, in makeDate
    date = datetime.strptime(string, dateform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains:  г.
```

**Comment by JimmXinu** [comment]
Test versions posted in the [usual places](https://github.com/JimmXinu/FanFicFare/#test-versions).

**Comment by lntmeu** [comment]
Thank you, everything works now.
