### ISSUE TITLE
InvalidURL on downloading from Fanfiction.net and AO3

### ISSUE THREAD

**Issue by neola-jah** [JimmXinu/FanFicFare#990]
Hi, I install FFF on Calibre today and I cant download a story (there are not private or protected for minor).
I tried those URL tonight (and others in the afternoon, same error) : https://archiveofourown.org/works/43655731 and https://www.fanfiction.net/s/8900471/1/Forgive-us-we-re-young

Here the error :
```
calibre, version 5.37.0
ERREUR : Exception non gérée: <b>InvalidURL</b>:Failed to parse: https://archiveofourown.org/works/43655731

calibre 5.37  embedded-python: False is64bit: True
Linux-5.15.0-78-lowlatency-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '5.15.0-78-lowlatency', '#85-Ubuntu SMP PREEMPT Tue Jul 11 07:51:28 UTC 2023')
Python 3.10.12
Interface language: fr
Successfully initialized third party plugins: FanFicFare (4, 26, 0) && Kobo Books (1, 9, 2)
Traceback (most recent call last):
  File "/home/jah/.local/lib/python3.10/site-packages/requests/models.py", line 434, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 394, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: https://archiveofourown.org/works/43655731

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 663, in get_urls_from_page_menu
    frompage = self.get_urls_from_page(url)
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 686, in get_urls_from_page
    return get_urls_from_page(url,configuration)
  File "/home/jah/.config/calibre/plugins/FanFicFare.zip/fanficfare/geturls.py", line 44, in get_urls_from_page
    return adapter.get_urls_from_page(url,normalize)
  File "/home/jah/.config/calibre/plugins/FanFicFare.zip/fanficfare/adapters/base_adapter.py", line 462, in get_urls_from_page
    data = self.get_request(url,usecache=False)
  File "/home/jah/.config/calibre/plugins/FanFicFare.zip/fanficfare/requestable.py", line 119, in get_request
    return self.get_request_redirected(url,
  File "/home/jah/.config/calibre/plugins/FanFicFare.zip/fanficfare/requestable.py", line 111, in get_request_redirected
    (data,rurl) = self.configuration.get_fetcher().get_request_redirected(
  File "/home/jah/.config/calibre/plugins/FanFicFare.zip/fanficfare/fetchers/base_fetcher.py", line 133, in get_request_redirected
    fetchresp = self.do_request('GET',
  File "/home/jah/.config/calibre/plugins/FanFicFare.zip/fanficfare/fetchers/cache_basic.py", line 122, in fetcher_do_request
    fetchresp = chainfn(
  File "/home/jah/.config/calibre/plugins/FanFicFare.zip/fanficfare/fetchers/decorators.py", line 102, in fetcher_do_request
    fetchresp = chainfn(
  File "/home/jah/.config/calibre/plugins/FanFicFare.zip/fanficfare/fetchers/base_fetcher.py", line 106, in do_request
    fetchresp = self.request(method,url,
  File "/home/jah/.config/calibre/plugins/FanFicFare.zip/fanficfare/fetchers/fetcher_requests.py", line 121, in request
    resp = self.get_requests_session().request(method, url,
  File "/home/jah/.local/lib/python3.10/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/home/jah/.local/lib/python3.10/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/jah/.local/lib/python3.10/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/jah/.local/lib/python3.10/site-packages/requests/models.py", line 436, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: https://archiveofourown.org/works/43655731

```
I dont find answer online, I hope it's ok to ask here.
Thanks for any help !

**Comment by JimmXinu** [comment]
Looks like something is broken in that Calibre install.

I only support the [official Calibre releases](https://calibre-ebook.com/download) , otherwise it's just too much of a moving target.  Use that instead of whatever your OS version packages.
